const l = (ru, en) => ({ ru, en })

const people = [
  'yo',
  'tú',
  'él / ella / usted',
  'nosotros',
  'vosotros',
  'ellos / ellas / ustedes',
]

export const grammarTablesContent = {
  bilingual: true,
  title: l('Грамматические таблицы', 'Grammar tables'),
  subtitle: l(
    'Тринадцать опорных схем: коротко, точно и с формами, которые используются в Испании.',
    'Thirteen essential references: concise, accurate and complete with the forms used in Spain.',
  ),
  desktopHint: l('Нажми на любую таблицу, чтобы развернуть её на весь экран.', 'Select any table to open it full screen.'),
  mobileHint: l('Выбери тему — на экране будет только одна таблица.', 'Choose a topic — only one table is shown at a time.'),
  expand: l('Развернуть', 'Open full screen'),
  close: l('Закрыть таблицу', 'Close table'),
  memoryLabel: l('Запомни', 'Remember'),
  tables: [
    {
      id: 'ser-estar',
      number: '01',
      type: 'ser-estar',
      shortTitle: 'SER / ESTAR',
      title: l('SER и ESTAR', 'SER and ESTAR'),
      subtitle: l('Прошедшее, настоящее и будущее', 'Past, present and future'),
      memory: l(
        'SER отвечает «кто/что это?», ESTAR — «где и в каком состоянии?». Это надёжнее правила «навсегда / временно».',
        'SER answers “what is it?”, ESTAR answers “where/how is it?”. This is more reliable than “permanent / temporary”.',
      ),
      tenses: [
        l('Прошедшее', 'Past'),
        l('Настоящее', 'Present'),
        l('Будущее', 'Future'),
      ],
      verbs: [
        {
          name: 'SER',
          tone: 'blue',
          rows: [
            ['fui', 'soy', 'seré'],
            ['fuiste', 'eres', 'serás'],
            ['fue', 'es', 'será'],
            ['fuimos', 'somos', 'seremos'],
            ['fuisteis', 'sois', 'seréis'],
            ['fueron', 'son', 'serán'],
          ],
          useTitle: l('SER: сущность и идентичность', 'SER: identity and essence'),
          uses: l('личность · происхождение · профессия · время и дата · характеристика', 'identity · origin · profession · time and date · characteristic'),
          examples: [
            ['Soy estudiante.', l('Я студент.', 'I am a student.')],
            ['Somos de Ucrania.', l('Мы из Украины.', 'We are from Ukraine.')],
          ],
        },
        {
          name: 'ESTAR',
          tone: 'green',
          rows: [
            ['estuve', 'estoy', 'estaré'],
            ['estuviste', 'estás', 'estarás'],
            ['estuvo', 'está', 'estará'],
            ['estuvimos', 'estamos', 'estaremos'],
            ['estuvisteis', 'estáis', 'estaréis'],
            ['estuvieron', 'están', 'estarán'],
          ],
          useTitle: l('ESTAR: место и состояние', 'ESTAR: location and state'),
          uses: l('местоположение · состояние · эмоция · результат действия', 'location · state · emotion · result of an action'),
          examples: [
            ['Estoy cansado.', l('Я устал.', 'I am tired.')],
            ['Estaremos en casa.', l('Мы будем дома.', 'We will be at home.')],
          ],
        },
      ],
      people,
    },
    {
      id: 'gerund',
      number: '02',
      type: 'gerund',
      shortTitle: l('Герундий', 'Gerund'),
      title: l('Герундий: действие сейчас', 'The gerund: action in progress'),
      subtitle: 'ESTAR + GERUNDIO',
      memory: l(
        'Сначала измени смысловой глагол, затем поставь перед ним нужную форму ESTAR: estoy estudiando, está leyendo.',
        'Change the action verb, then put the right form of ESTAR before it: estoy estudiando, está leyendo.',
      ),
      formula: l('ESTAR + герундий = действие, которое происходит сейчас', 'ESTAR + gerund = an action happening right now'),
      groups: [
        {
          ending: '-AR → -ANDO',
          tone: 'green',
          rule: l('Убери -ar и добавь -ando', 'Remove -ar and add -ando'),
          examples: [['hablar', 'hablando'], ['trabajar', 'trabajando'], ['caminar', 'caminando'], ['estudiar', 'estudiando']],
        },
        {
          ending: '-ER / -IR → -IENDO',
          tone: 'blue',
          rule: l('Убери -er / -ir и добавь -iendo', 'Remove -er / -ir and add -iendo'),
          examples: [['comer', 'comiendo'], ['vivir', 'viviendo'], ['escribir', 'escribiendo']],
        },
        {
          ending: l('После гласной → -YENDO', 'After a vowel → -YENDO'),
          tone: 'purple',
          rule: l('В некоторых формах i превращается в y', 'In some forms, i changes to y'),
          examples: [['leer', 'leyendo'], ['creer', 'creyendo'], ['traer', 'trayendo'], ['caer', 'cayendo'], ['oír', 'oyendo'], ['ir', 'yendo']],
        },
      ],
      stemTitle: l('Изменение корня в некоторых -IR', 'Stem changes in some -IR verbs'),
      stemExamples: [['dormir', 'durmiendo'], ['pedir', 'pidiendo'], ['decir', 'diciendo'], ['venir', 'viniendo'], ['poder', 'pudiendo']],
      progressExamples: [
        ['Estoy estudiando español.', l('Я сейчас учу испанский.', 'I am studying Spanish right now.')],
        ['Estáis comiendo.', l('Вы сейчас едите.', 'You are eating right now.')],
        ['Está lloviendo.', l('Сейчас идёт дождь.', 'It is raining.')],
      ],
      compare: [
        ['Estudio español.', l('Обычно / вообще изучаю испанский.', 'I study Spanish in general.')],
        ['Estoy estudiando español.', l('Занимаюсь этим прямо сейчас.', 'I am studying Spanish right now.')],
      ],
    },
    {
      id: 'demonstratives',
      number: '03',
      type: 'demonstratives',
      shortTitle: 'ESTE / ESTA / ESTO',
      title: 'ESTE, ESTA Y ESTO',
      subtitle: l('Три способа сказать «этот / эта / это»', 'Three ways to say “this”'),
      memory: l(
        'Назвал предмет — согласуй este/esta с родом. Не назвал предмет или говоришь об идее — используй esto.',
        'If you name the noun, match este/esta to its gender. If the noun is unnamed or it is an idea, use esto.',
      ),
      columns: [
        {
          name: 'ESTE',
          tone: 'green',
          heading: l('мужской род + существительное', 'masculine noun'),
          rule: l('Ставится перед существительным мужского рода.', 'Use before a masculine noun.'),
          examples: ['este libro', 'este ordenador', 'este profesor', 'este autobús'],
        },
        {
          name: 'ESTA',
          tone: 'blue',
          heading: l('женский род + существительное', 'feminine noun'),
          rule: l('Ставится перед существительным женского рода.', 'Use before a feminine noun.'),
          examples: ['esta mesa', 'esta silla', 'esta universidad', 'esta casa'],
        },
        {
          name: 'ESTO',
          tone: 'purple',
          heading: l('предмет или идея без названия', 'an unnamed thing or idea'),
          rule: l('Это местоимение: после него не ставят существительное.', 'This is a pronoun: a noun does not follow it.'),
          examples: ['¿Qué es esto?', 'Esto es importante.', 'No entiendo esto.', 'Me gusta esto.'],
        },
      ],
      plural: l('Во множественном числе: estos libros · estas mesas. У esto нет формы множественного числа.', 'Plural: estos libros · estas mesas. Esto has no plural form.'),
      accent: l('Не путай: esta mesa — «этот стол», но está aquí — «находится здесь». У формы глагола está есть ударение.', 'Do not confuse: esta mesa means “this table”, but está aquí means “is here”. The verb form está has an accent.'),
      wrong: l('Не говори: esto libro ✕. Правильно: este libro ✓.', 'Do not say: esto libro ✕. Say: este libro ✓.'),
    },
    {
      id: 'regular-present',
      number: '04',
      type: 'regular-present',
      shortTitle: l('Настоящее время', 'Present tense'),
      title: l('Правильные глаголы в настоящем', 'Regular verbs in the present'),
      subtitle: '-AR · -ER · -IR',
      memory: l(
        'Убери -ar, -er или -ir, сохрани корень и добавь окончание для нужного лица.',
        'Remove -ar, -er or -ir, keep the stem and add the ending for the right person.',
      ),
      people,
      families: [
        {
          infinitive: 'TRABAJAR',
          family: '-AR',
          tone: 'blue',
          endings: ['-o', '-as', '-a', '-amos', '-áis', '-an'],
          forms: ['trabajo', 'trabajas', 'trabaja', 'trabajamos', 'trabajáis', 'trabajan'],
        },
        {
          infinitive: 'APRENDER',
          family: '-ER',
          tone: 'green',
          endings: ['-o', '-es', '-e', '-emos', '-éis', '-en'],
          forms: ['aprendo', 'aprendes', 'aprende', 'aprendemos', 'aprendéis', 'aprenden'],
        },
        {
          infinitive: 'ABRIR',
          family: '-IR',
          tone: 'purple',
          endings: ['-o', '-es', '-e', '-imos', '-ís', '-en'],
          forms: ['abro', 'abres', 'abre', 'abrimos', 'abrís', 'abren'],
        },
      ],
      note: l(
        'Эта схема только для правильных глаголов. У неправильных глаголов и глаголов с изменением корня могут быть другие формы.',
        'This pattern is for regular verbs. Irregular and stem-changing verbs may use different forms.',
      ),
      spain: l('В Испании для неформального «вы» используется vosotros: trabajáis, aprendéis, abrís.', 'In Spain, informal plural “you” uses vosotros: trabajáis, aprendéis, abrís.'),
    },
    {
      id: 'regular-past',
      number: '05',
      type: 'regular-past',
      shortTitle: l('Прошедшее', 'Past tense'),
      title: l('Правильные глаголы в прошедшем', 'Regular verbs in the past'),
      subtitle: 'PRETÉRITO INDEFINIDO · -AR · -ER · -IR',
      memory: l(
        'Это время для завершённого события: ayer trabajé, la semana pasada aprendimos. Ударения в trabajé, trabajó, aprendí и aprendió обязательны.',
        'Use this tense for a completed event: ayer trabajé, la semana pasada aprendimos. The accents in trabajé, trabajó, aprendí and aprendió are required.',
      ),
      people,
      families: [
        {
          infinitive: 'TRABAJAR',
          family: '-AR',
          tone: 'blue',
          endings: ['-é', '-aste', '-ó', '-amos', '-asteis', '-aron'],
          forms: ['trabajé', 'trabajaste', 'trabajó', 'trabajamos', 'trabajasteis', 'trabajaron'],
        },
        {
          infinitive: 'APRENDER',
          family: '-ER',
          tone: 'green',
          endings: ['-í', '-iste', '-ió', '-imos', '-isteis', '-ieron'],
          forms: ['aprendí', 'aprendiste', 'aprendió', 'aprendimos', 'aprendisteis', 'aprendieron'],
        },
        {
          infinitive: 'ABRIR',
          family: '-IR',
          tone: 'purple',
          endings: ['-í', '-iste', '-ió', '-imos', '-isteis', '-ieron'],
          forms: ['abrí', 'abriste', 'abrió', 'abrimos', 'abristeis', 'abrieron'],
        },
      ],
      spain: l('Форма vosotros: trabajasteis, aprendisteis, abristeis. Перед -steis буква s только одна.', 'Vosotros forms: trabajasteis, aprendisteis, abristeis. There is only one s before -teis.'),
      contrast: l('Trabajamos и abrimos могут означать настоящее или прошлое — время понятно из контекста: hoy / ayer.', 'Trabajamos and abrimos can be present or past; context such as hoy / ayer makes the time clear.'),
      note: l(
        'Это схема правильных глаголов. У частых неправильных форм другая основа: tener → tuve, hacer → hice, ir / ser → fui.',
        'This pattern is for regular verbs. Common irregulars use different stems: tener → tuve, hacer → hice, ir / ser → fui.',
      ),
    },
    {
      id: 'regular-future',
      number: '06',
      type: 'regular-future',
      shortTitle: l('Будущее', 'Future tense'),
      title: l('Простое будущее время', 'The simple future tense'),
      subtitle: 'FUTURO SIMPLE · -AR · -ER · -IR',
      memory: l(
        'Не убирай -ar, -er или -ir: добавляй окончание к целому инфинитиву. Ударения в trabajaré, trabajarás, trabajará, trabajaréis и trabajarán обязательны.',
        'Keep the complete infinitive and add the ending after -ar, -er or -ir. The accents in trabajaré, trabajarás, trabajará, trabajaréis and trabajarán are required.',
      ),
      people,
      families: [
        {
          infinitive: 'TRABAJAR',
          family: '-AR',
          tone: 'blue',
          endings: ['-é', '-ás', '-á', '-emos', '-éis', '-án'],
          forms: ['trabajaré', 'trabajarás', 'trabajará', 'trabajaremos', 'trabajaréis', 'trabajarán'],
        },
        {
          infinitive: 'APRENDER',
          family: '-ER',
          tone: 'green',
          endings: ['-é', '-ás', '-á', '-emos', '-éis', '-án'],
          forms: ['aprenderé', 'aprenderás', 'aprenderá', 'aprenderemos', 'aprenderéis', 'aprenderán'],
        },
        {
          infinitive: 'ABRIR',
          family: '-IR',
          tone: 'purple',
          endings: ['-é', '-ás', '-á', '-emos', '-éis', '-án'],
          forms: ['abriré', 'abrirás', 'abrirá', 'abriremos', 'abriréis', 'abrirán'],
        },
      ],
      spain: l('Форма vosotros: trabajaréis, aprenderéis, abriréis. Во всех трёх формах есть ударение.', 'Vosotros forms: trabajaréis, aprenderéis, abriréis. All three forms carry a written accent.'),
      contrast: l('Voy a trabajar = «собираюсь работать», обычно ближайший план. Trabajaré = «буду работать», прогноз, обещание или более нейтральное будущее.', 'Voy a trabajar usually presents a near plan. Trabajaré is a prediction, promise or a more neutral future statement.'),
      note: l(
        'Окончания одинаковы для всех трёх типов, но у некоторых частых глаголов меняется основа: tener → tendré, hacer → haré, poder → podré, decir → diré.',
        'The endings are identical for all three families, but some common verbs change their stem: tener → tendré, hacer → haré, poder → podré, decir → diré.',
      ),
    },
    {
      id: 'reflexive-verbs',
      number: '07',
      type: 'reflexive',
      shortTitle: l('Возвратные', 'Reflexive'),
      title: l('Возвратные глаголы', 'Reflexive verbs'),
      subtitle: 'PRONOMBRE REFLEXIVO + VERBO CONJUGADO',
      memory: l(
        'Глагол спрягается как обычно, а возвратное местоимение меняется вместе с лицом: me, te, se, nos, os, se.',
        'Conjugate the verb normally and change the reflexive pronoun with the person: me, te, se, nos, os, se.',
      ),
      formulaLabel: l('Базовая формула', 'Basic formula'),
      formula: l('возвратное местоимение + спрягаемый глагол', 'reflexive pronoun + conjugated verb'),
      infinitiveNote: l(
        'В словаре форма оканчивается на -se: levantar + se = levantarse. При спряжении se ставится перед глаголом и меняется по лицам.',
        'The dictionary form ends in -se: levantar + se = levantarse. When conjugated, se moves before the verb and changes with the person.',
      ),
      people,
      pronouns: ['me', 'te', 'se', 'nos', 'os', 'se'],
      exampleVerb: 'LEVANTARSE',
      forms: [
        ['me', 'levanto'],
        ['te', 'levantas'],
        ['se', 'levanta'],
        ['nos', 'levantamos'],
        ['os', 'levantáis'],
        ['se', 'levantan'],
      ],
      examples: [
        ['Me ducho por la mañana.', l('Я принимаю душ по утрам.', 'I shower in the morning.')],
        ['Nos relajamos después de estudiar.', l('Мы отдыхаем после учёбы.', 'We relax after studying.')],
        ['Ella se acuesta a las diez.', l('Она ложится спать в десять.', 'She goes to bed at ten.')],
      ],
      spain: l(
        'В Испании обязательно запомни форму vosotros: os levantáis, os ducháis, os relajáis.',
        'For Spain, remember the vosotros form: os levantáis, os ducháis, os relajáis.',
      ),
    },
    {
      id: 'imperfect',
      number: '08',
      type: 'imperfect',
      shortTitle: l('Имперфект', 'Imperfect'),
      title: 'Pretérito imperfecto',
      subtitle: l('Привычки, фон и описания в прошлом', 'Past habits, background and descriptions'),
      memory: l(
        'Imperfecto показывает, как всё было или что обычно происходило, без акцента на завершении: de niño jugaba, antes vivía, la casa tenía.',
        'The imperfect shows how things were or what used to happen, without focusing on completion: de niño jugaba, antes vivía, la casa tenía.',
      ),
      useLabel: l('Когда использовать', 'When to use it'),
      use: l('повторяющиеся действия · описания · возраст · время · фон истории', 'repeated actions · descriptions · age · time · story background'),
      people,
      families: [
        {
          family: '-AR',
          instruction: l('Убери -ar и добавь окончание', 'Remove -ar and add the ending'),
          tone: 'green',
          endings: ['-aba', '-abas', '-aba', '-ábamos', '-abais', '-aban'],
          examples: [
            ['habl', 'aba'],
            ['habl', 'abas'],
            ['habl', 'aba'],
            ['habl', 'ábamos'],
            ['habl', 'abais'],
            ['habl', 'aban'],
          ],
          infinitive: 'HABLAR',
        },
        {
          family: '-ER / -IR',
          instruction: l('Убери -er / -ir и добавь окончание', 'Remove -er / -ir and add the ending'),
          tone: 'blue',
          endings: ['-ía', '-ías', '-ía', '-íamos', '-íais', '-ían'],
          examples: [
            ['com', 'ía'],
            ['com', 'ías'],
            ['com', 'ía'],
            ['com', 'íamos'],
            ['com', 'íais'],
            ['com', 'ían'],
          ],
          secondExamples: [
            ['viv', 'ía'],
            ['viv', 'ías'],
            ['viv', 'ía'],
            ['viv', 'íamos'],
            ['viv', 'íais'],
            ['viv', 'ían'],
          ],
          infinitive: 'COMER / VIVIR',
        },
      ],
      irregularTitle: l('Только 3 неправильных глагола', 'Only 3 irregular verbs'),
      irregulars: [
        { name: 'SER', tone: 'purple', forms: ['era', 'eras', 'era', 'éramos', 'erais', 'eran'] },
        { name: 'IR', tone: 'green', forms: ['iba', 'ibas', 'iba', 'íbamos', 'ibais', 'iban'] },
        { name: 'VER', tone: 'blue', forms: ['veía', 'veías', 'veía', 'veíamos', 'veíais', 'veían'] },
      ],
      examples: [
        ['Cuando era niño, jugaba todos los días.', l('Когда я был ребёнком, я играл каждый день.', 'When I was a child, I played every day.')],
        ['Antes vivía en Madrid.', l('Раньше я жил в Мадриде.', 'I used to live in Madrid.')],
        ['Mi barrio era tranquilo.', l('Мой район был спокойным.', 'My neighbourhood was quiet.')],
        ['La casa tenía un jardín grande.', l('У дома был большой сад.', 'The house had a large garden.')],
      ],
    },
    {
      id: 'estuve-gerundio',
      number: '09',
      type: 'estuve-gerundio',
      shortTitle: 'ESTUVE + -NDO',
      title: 'Estuve + gerundio',
      subtitle: l('Действие в течение завершённого периода', 'An activity during a completed time period'),
      memory: l(
        'Спрягай только ESTAR: estuve, estuviste, estuvo… Герундий не меняется ни по лицу, ни по числу.',
        'Only ESTAR is conjugated: estuve, estuviste, estuvo… The gerund does not change for person or number.',
      ),
      purpose: l(
        'Используй конструкцию, когда действие занимало определённый, уже законченный отрезок времени: два часа, всё утро, некоторое время.',
        'Use this construction when an activity occupied a defined time period that is now over: two hours, all morning, for a while.',
      ),
      formulaAuxiliary: l('ESTAR в pretérito indefinido', 'ESTAR in the preterite'),
      formulaGerund: l('герундий', 'gerund'),
      estarTitle: l('ESTAR в pretérito indefinido', 'ESTAR in the preterite'),
      people,
      estarForms: ['estuve', 'estuviste', 'estuvo', 'estuvimos', 'estuvisteis', 'estuvieron'],
      gerundTitle: l('Как образовать герундий', 'How to form the gerund'),
      gerundRules: [
        { family: '-AR', ending: '-ando', tone: 'green', examples: [['trabajar', 'trabajando']] },
        { family: '-ER / -IR', ending: '-iendo', tone: 'blue', examples: [['comer', 'comiendo'], ['vivir', 'viviendo']] },
      ],
      modelTitle: l('Пример спряжения: trabajar', 'Conjugation example: trabajar'),
      modelGerund: 'trabajando',
      compareTitle: l('Главное различие', 'The key difference'),
      compare: [
        {
          label: l('Действие шло в тот момент', 'In progress at that moment'),
          es: 'Estaba trabajando cuando llamaste.',
          meaning: l('Я работал, когда ты позвонил.', 'I was working when you called.'),
          tone: 'blue',
        },
        {
          label: l('Действие заняло законченный период', 'Activity over a completed period'),
          es: 'Estuve trabajando toda la mañana.',
          meaning: l('Я работал всё утро.', 'I worked all morning.'),
          tone: 'green',
        },
      ],
      examples: [
        ['Estuve estudiando durante dos horas.', l('Я занимался два часа.', 'I studied for two hours.')],
        ['Marta estuvo trabajando toda la mañana.', l('Марта работала всё утро.', 'Marta worked all morning.')],
        ['Estuvimos conversando un rato.', l('Мы некоторое время разговаривали.', 'We talked for a while.')],
        ['Estuvieron preparando la presentación de ocho a diez.', l('Они готовили презентацию с восьми до десяти.', 'They worked on the presentation from eight to ten.')],
      ],
    },
    {
      id: 'tener-forms',
      number: '10',
      type: 'tener-forms',
      shortTitle: 'TENER',
      title: l('Главные формы TENER', 'Essential forms of TENER'),
      subtitle: l('Иметь · возраст · состояния · обязанность', 'Possession · age · states · obligation'),
      memory: l(
        'У TENER меняется основа: tengo в настоящем, tuv- в законченном прошлом и tendr- в будущем. Учи каждую форму вместе с короткой фразой.',
        'TENER changes its stem: tengo in the present, tuv- in the preterite and tendr- in the future. Learn each form inside a short phrase.',
      ),
      people,
      forms: [
        {
          name: l('Инфинитив', 'Infinitive'),
          cue: l('базовая форма', 'base form'),
          tone: 'blue',
          featured: 'tener',
          example: ['Quiero tener más tiempo.', l('Я хочу иметь больше времени.', 'I want to have more time.')],
        },
        {
          name: l('Настоящее', 'Present'),
          cue: l('сейчас / обычно', 'now / usually'),
          tone: 'green',
          forms: ['tengo', 'tienes', 'tiene', 'tenemos', 'tenéis', 'tienen'],
          example: ['Hoy tengo tiempo.', l('Сегодня у меня есть время.', 'I have time today.')],
        },
        {
          name: 'Pretérito imperfecto',
          cue: l('раньше / обычно', 'used to / background'),
          tone: 'purple',
          forms: ['tenía', 'tenías', 'tenía', 'teníamos', 'teníais', 'tenían'],
          example: ['Antes tenía más tiempo.', l('Раньше у меня было больше времени.', 'I used to have more time.')],
        },
        {
          name: 'Pretérito indefinido',
          cue: l('законченное событие', 'completed event'),
          tone: 'orange',
          forms: ['tuve', 'tuviste', 'tuvo', 'tuvimos', 'tuvisteis', 'tuvieron'],
          example: ['Ayer tuve una reunión.', l('Вчера у меня была встреча.', 'I had a meeting yesterday.')],
        },
        {
          name: l('Будущее', 'Future'),
          cue: l('потом', 'later'),
          tone: 'blue',
          forms: ['tendré', 'tendrás', 'tendrá', 'tendremos', 'tendréis', 'tendrán'],
          example: ['Mañana tendré más tiempo.', l('Завтра у меня будет больше времени.', 'I will have more time tomorrow.')],
        },
        {
          name: l('Настоящее сослагательного', 'Present subjunctive'),
          cue: l('желание / сомнение', 'wish / doubt'),
          tone: 'pink',
          forms: ['tenga', 'tengas', 'tenga', 'tengamos', 'tengáis', 'tengan'],
          example: ['Espero que tengas tiempo.', l('Надеюсь, у тебя будет время.', 'I hope you have time.')],
        },
      ],
      quickTitle: l('Быстрые модели', 'Quick patterns'),
      patterns: [
        ['tener + objeto', l('иметь что-то', 'to have something'), 'Tengo un libro.'],
        ['tener + número + años', l('возраст', 'age'), 'Tengo 22 años.'],
        ['tener + hambre / sueño', l('состояние', 'a state'), 'Tengo hambre.'],
        ['tener que + infinitivo', l('необходимость', 'obligation'), 'Tengo que estudiar.'],
      ],
    },
    {
      id: 'haber-forms',
      number: '11',
      type: 'haber-forms',
      shortTitle: 'HABER',
      title: l('Главные формы HABER', 'Essential forms of HABER'),
      subtitle: 'HAY · HABÍA · HUBO · HABRÁ',
      memory: l(
        'В безличном значении формы hay, había, hubo и habrá не меняются во множественном числе: hay un problema / hay muchos problemas.',
        'In impersonal use, hay, había, hubo and habrá do not change in the plural: hay un problema / hay muchos problemas.',
      ),
      infinitive: {
        form: 'haber',
        cue: l('базовая форма', 'base form'),
        example: ['Puede haber un problema.', l('Может быть проблема.', 'There may be a problem.')],
      },
      timeline: [
        {
          form: 'hay',
          name: l('Настоящее', 'Present'),
          time: l('сейчас', 'now'),
          tone: 'green',
          use: l('говорим, что что-то существует или находится где-то сейчас', 'says that something exists or is present now'),
          examples: ['Hay un evento hoy.', 'Hay muchas personas aquí.'],
        },
        {
          form: 'había',
          name: 'Pretérito imperfecto',
          time: l('фон в прошлом', 'past background'),
          tone: 'purple',
          use: l('описываем то, что существовало или было фоном', 'describes what existed or formed the background'),
          examples: ['Había un parque cerca de mi casa.', 'Había muchas tiendas pequeñas.'],
        },
        {
          form: 'hubo',
          name: 'Pretérito indefinido',
          time: l('законченное событие', 'completed event'),
          tone: 'orange',
          use: l('сообщаем о конкретном завершённом событии', 'reports a specific completed event'),
          examples: ['Hubo una reunión ayer.', 'Hubo varios cambios.'],
        },
        {
          form: 'habrá',
          name: l('Будущее', 'Future'),
          time: l('потом', 'later'),
          tone: 'blue',
          use: l('говорим о том, что будет существовать или произойдёт', 'says what will exist or happen'),
          examples: ['Habrá un evento mañana.', 'Habrá muchos cambios.'],
        },
      ],
      contrastTitle: l('Одна форма для единственного и множественного числа', 'One form for singular and plural'),
      contrasts: [
        ['Hay un problema.', 'Hay muchos problemas.'],
        ['Había una persona.', 'Había muchas personas.'],
        ['Hubo un evento.', 'Hubo varios eventos.'],
        ['Habrá una reunión.', 'Habrá muchas reuniones.'],
      ],
    },
    {
      id: 'object-pronouns',
      number: '12',
      type: 'object-pronouns',
      shortTitle: 'OD / OI',
      title: l('Прямое и косвенное дополнение', 'Direct and indirect objects'),
      subtitle: 'OBJETO DIRECTO (OD) · OBJETO INDIRECTO (OI)',
      memory: l(
        'Сначала найди действие и спроси «что? / кого?» — это обычно OD. Затем спроси «кому? / для кого?» — это обычно OI. Важно понять роль в действии, а не только предлог a.',
        'First find the action and ask “what? / whom?” — that is usually the OD. Then ask “to whom? / for whom?” — that is usually the OI. Focus on the role in the action, not only the preposition a.',
      ),
      model: {
        start: 'Ana da',
        direct: 'un libro',
        connector: 'a',
        indirect: 'Pedro.',
      },
      definitions: [
        {
          key: 'OD',
          tone: 'blue',
          title: l('Прямое дополнение', 'Direct object'),
          text: l('Предмет или человек, на который действие направлено напрямую.', 'The thing or person directly affected by the action.'),
        },
        {
          key: 'OI',
          tone: 'green',
          title: l('Косвенное дополнение', 'Indirect object'),
          text: l('Получатель прямого дополнения или тот, для кого совершается действие.', 'The recipient of the direct object or the person for whom the action is done.'),
        },
      ],
      direct: {
        title: l('Как найти OD', 'How to find the OD'),
        question: l('Что даёт Ана?', 'What does Ana give?'),
        answer: 'un libro',
        pronoun: 'lo',
        result: 'Ana lo da.',
      },
      indirect: {
        title: l('Как найти OI', 'How to find the OI'),
        question: l('Кому Ана даёт книгу?', 'To whom does Ana give the book?'),
        answer: 'a Pedro',
        pronoun: 'le',
        result: 'Ana le da un libro.',
      },
      directTitle: l('Местоимения OD', 'OD pronouns'),
      directPronouns: [
        [l('мужской, ед. число', 'masculine singular'), 'lo'],
        [l('женский, ед. число', 'feminine singular'), 'la'],
        [l('мужской, мн. число', 'masculine plural'), 'los'],
        [l('женский, мн. число', 'feminine plural'), 'las'],
      ],
      indirectTitle: l('Местоимения OI', 'OI pronouns'),
      indirectPronouns: [
        ['a mí', 'me'],
        ['a ti', 'te'],
        ['a él / ella / usted', 'le'],
        ['a nosotros / nosotras', 'nos'],
        ['a vosotros / vosotras', 'os'],
        ['a ellos / ellas / ustedes', 'les'],
      ],
      togetherTitle: l('Когда OD и OI стоят вместе', 'When OD and OI appear together'),
      togetherSteps: ['un libro → lo', 'a Pedro → le', 'le + lo → se lo'],
      togetherResult: 'Ana se lo da.',
      togetherRule: 'le / les + lo / la / los / las → se + lo / la / los / las',
      personTitle: l('Человек тоже может быть OD', 'A person can also be the OD'),
      personExample: 'Ana visita a Pedro. → Ana lo visita.',
      personNote: l(
        'Здесь Pedro напрямую получает действие visitar, поэтому это OD — несмотря на личный предлог a.',
        'Here Pedro is directly affected by visitar, so he is the OD — despite the personal a.',
      ),
    },
    {
      id: 'hacer-forms',
      number: '13',
      type: 'hacer-forms',
      shortTitle: 'HACER',
      title: l('Главные формы HACER', 'Essential forms of HACER'),
      subtitle: l('Делать · создавать · погода · время', 'Doing · making · weather · time'),
      memory: l(
        'Запомни пять опор: hago — сейчас, hacía — раньше, hice — законченное действие, haré — будущее, haga — желание или рекомендация.',
        'Remember five anchors: hago — now, hacía — before, hice — completed action, haré — future, haga — a wish or recommendation.',
      ),
      people,
      forms: [
        {
          name: l('Инфинитив', 'Infinitive'),
          cue: l('базовая форма', 'base form'),
          tone: 'blue',
          featured: 'hacer',
          example: ['Necesito hacer una llamada.', l('Мне нужно позвонить.', 'I need to make a call.')],
        },
        {
          name: l('Настоящее', 'Present'),
          cue: l('сейчас / обычно', 'now / usually'),
          tone: 'green',
          forms: ['hago', 'haces', 'hace', 'hacemos', 'hacéis', 'hacen'],
          example: ['Hoy hago ejercicio.', l('Сегодня я занимаюсь спортом.', 'I am exercising today.')],
        },
        {
          name: 'Pretérito imperfecto',
          cue: l('раньше / привычка', 'before / habit'),
          tone: 'purple',
          forms: ['hacía', 'hacías', 'hacía', 'hacíamos', 'hacíais', 'hacían'],
          example: ['Antes hacía ejercicio cada día.', l('Раньше я занимался каждый день.', 'I used to exercise every day.')],
        },
        {
          name: 'Pretérito indefinido',
          cue: l('законченное действие', 'completed action'),
          tone: 'orange',
          forms: ['hice', 'hiciste', 'hizo', 'hicimos', 'hicisteis', 'hicieron'],
          example: ['Ayer hice la tarea.', l('Вчера я сделал задание.', 'I did the homework yesterday.')],
        },
        {
          name: l('Будущее', 'Future'),
          cue: l('потом', 'later'),
          tone: 'blue',
          forms: ['haré', 'harás', 'hará', 'haremos', 'haréis', 'harán'],
          example: ['Mañana haré ejercicio.', l('Завтра я буду заниматься спортом.', 'I will exercise tomorrow.')],
        },
        {
          name: l('Настоящее сослагательного', 'Present subjunctive'),
          cue: l('желание / рекомендация', 'wish / recommendation'),
          tone: 'pink',
          forms: ['haga', 'hagas', 'haga', 'hagamos', 'hagáis', 'hagan'],
          example: ['Quiero que hagas la actividad.', l('Я хочу, чтобы ты выполнил задание.', 'I want you to do the activity.')],
        },
      ],
      progressiveTitle: l('Прогрессивные формы', 'Progressive forms'),
      progressives: [
        {
          form: 'Estoy haciendo',
          tone: 'green',
          cue: l('действие идёт сейчас', 'in progress now'),
          example: 'Ahora estoy haciendo la tarea.',
        },
        {
          form: 'Estaba haciendo',
          tone: 'purple',
          cue: l('действие шло в момент прошлого', 'in progress at a past moment'),
          example: 'Ayer a las ocho estaba haciendo la tarea.',
        },
        {
          form: 'Estuve haciendo',
          tone: 'orange',
          cue: l('действие заняло завершённый период', 'activity over a completed period'),
          example: 'Estuve haciendo la tarea durante dos horas.',
        },
        {
          form: 'Estaré haciendo',
          tone: 'blue',
          cue: l('действие будет идти в момент будущего', 'in progress at a future moment'),
          example: 'Mañana a las ocho estaré haciendo la tarea.',
        },
      ],
    },
  ],
}
