const l = (ru, en) => ({ ru, en })
const w = (ru, en, noteRu, noteEn) => ({ meaning: l(ru, en), note: l(noteRu, noteEn) })
const line = (start, text, ru, en, noteRu, noteEn) => ({ start, text, translation: l(ru, en), explanation: l(noteRu, noteEn) })

const lexicon = {
  yo: w('я', 'I', 'Личное местоимение; обычно его можно опустить, но здесь оно создаёт контраст с tú.', 'Subject pronoun; usually optional, but here it contrasts with tú.'),
  no: w('не / нет', 'not / no', 'Ставится прямо перед глагольной группой: no sé, no nadas.', 'Placed directly before the verb phrase: no sé, no nadas.'),
  sé: w('я знаю / умею', 'I know / know how', 'Неправильная форма saber для yo. Sé + infinitivo = «я умею что-то делать».', 'Irregular yo form of saber. Sé + infinitive means “I know how to do something”.'),
  nadar: w('плавать', 'to swim', 'Инфинитив на -ar; после sé остаётся в начальной форме.', 'An -ar infinitive; it stays infinitive after sé.'),
  y: w('и', 'and', 'Союз, соединяющий слова и части предложения.', 'A conjunction joining words and clauses.'),
  tú: w('ты', 'you', 'Ударение отличает местоимение tú от притяжательного tu — «твой».', 'The accent distinguishes tú “you” from possessive tu “your”.'),
  nadas: w('ты плаваешь', 'you swim', 'Форма nadar для tú: основа nad- + окончание -as.', 'The tú form of nadar: stem nad- + ending -as.'),
  bien: w('хорошо', 'well', 'Наречие, описывающее, как выполняется действие.', 'An adverb describing how an action is done.'),
  en: w('в / на', 'in / on', 'Предлог места: en alta mar, en el mar.', 'A preposition of place: en alta mar, en el mar.'),
  alta: w('высокая; открытая', 'high; open', 'В выражении alta mar означает открытое море, далеко от берега.', 'In alta mar it means the open sea, far from shore.'),
  mar: w('море', 'sea', 'Обычно el mar; устойчивое выражение en alta mar употребляется без артикля.', 'Usually el mar; the fixed phrase en alta mar omits the article.'),
  ninguno: w('ни один / никто из двоих', 'neither / not one', 'Здесь относится к двум людям: ни один из нас не достаёт ногами дна.', 'Here it refers to the two people: neither can touch the bottom.'),
  hace: w('делает', 'does / makes', 'Форма hacer для él/ella/usted; входит в выражение hacer pie.', 'The él/ella/usted form of hacer; used in hacer pie.'),
  pie: w('нога; опора ногами', 'foot; footing', 'Hacer pie = доставать ногами дна, иметь опору в воде.', 'Hacer pie means to touch the bottom and have footing in water.'),
  pero: w('но', 'but', 'Противопоставляет проблему и то, что герои всё-таки умеют.', 'Contrasts the problem with what the speakers can still do.'),
  chapotear: w('плескаться', 'to splash / paddle about', 'Разговорный глагол о движении и игре в воде.', 'An everyday verb for moving and playing in water.'),
  flotar: w('держаться на воде', 'to float', 'Инфинитив на -ar.', 'An -ar infinitive.'),
  sí: w('да', 'yes', 'С ударением: sí = «да». Без ударения si = «если».', 'With an accent, sí means “yes”. Without it, si means “if”.'),
  sabemos: w('мы знаем / умеем', 'we know / know how', 'Форма saber для nosotros.', 'The nosotros form of saber.'),
  así: w('так / таким образом', 'like this / so', 'Así que вместе означает «так что / поэтому».', 'Así que together means “so / therefore”.'),
  que: w('что / который', 'that / which', 'Союз или относительное слово; без ударения, когда не задаёт прямой вопрос.', 'A conjunction or relative word; no accent when it is not a direct question.'),
  voy: w('я иду / собираюсь', 'I go / I am going to', 'Форма ir для yo. Voy a + infinitivo выражает ближайший план.', 'The yo form of ir. Voy a + infinitive expresses a near-future plan.'),
  a: w('к / в / чтобы', 'to / at', 'Предлог направления; также часть конструкции voy a construir.', 'A direction preposition; also part of voy a construir.'),
  construir: w('строить', 'to build', 'Инфинитив на -ir; yo construyo, tú construyes.', 'An -ir infinitive; yo construyo, tú construyes.'),
  un: w('один / неопределённый артикль', 'a / one', 'Мужской артикль перед velero и bajel.', 'Masculine indefinite article before velero and bajel.'),
  velero: w('парусник', 'sailboat', 'Существительное от vela — «парус».', 'A noun related to vela, “sail”.'),
  bajel: w('судно / корабль', 'vessel / ship', 'Книжное, поэтическое слово; в обычной речи чаще barco.', 'A literary, poetic word; barco is more common in everyday speech.'),
  para: w('для / чтобы', 'for / in order to', 'Para + infinitivo показывает цель: «чтобы преследовать».', 'Para + infinitive expresses purpose: “in order to chase”.'),
  perseguir: w('преследовать / гнаться за', 'to chase / pursue', 'Глагол с изменением e→i: persigo, persigues.', 'A stem-changing verb: persigo, persigues.'),
  pájaros: w('птицы', 'birds', 'Множественное число от pájaro; ударение сохраняется.', 'Plural of pájaro; the written accent remains.'),
  de: w('из / от / родительный предлог', 'of / from', 'Связывает слова: pájaros de Portugal, echarte de menos.', 'Links words: pájaros de Portugal, echarte de menos.'),
  portugal: w('Португалия', 'Portugal', 'Название страны пишется с прописной буквы.', 'A country name, written with a capital letter.'),
  tu: w('твой / твоя', 'your', 'Без ударения: притяжательное слово. Tú с ударением = «ты».', 'Without an accent, it is possessive. Tú with an accent means “you”.'),
  estela: w('кильватерный след', 'wake / trail on water', 'След, который лодка оставляет на поверхности воды.', 'The trail a boat leaves on the surface of the water.'),
  el: w('определённый артикль, мужской', 'the, masculine', 'Согласуется с существительным: el mar, el timón.', 'Agrees with its noun: el mar, el timón.'),
  echarte: w('скучать по тебе — в выражении', 'to miss you — in the expression', 'Echar + te: местоимение te прикреплено к инфинитиву. Полное выражение echarte de menos.', 'Echar + te: the object pronoun attaches to the infinitive. The full phrase is echarte de menos.'),
  menos: w('меньше; в выражении «скучать»', 'less; in “to miss”', 'Echar de menos — устойчивое выражение «скучать по кому-то».', 'Echar de menos is the fixed expression “to miss someone”.'),
  mientras: w('пока / в то время как', 'while', 'Вводит одновременное действие.', 'Introduces an action happening at the same time.'),
  navego: w('я плыву / путешествую на судне', 'I sail / navigate', 'Форма navegar для yo.', 'The yo form of navegar.'),
  dirección: w('направление', 'direction', 'Tu dirección = в твоём направлении; ударение на ó.', 'Tu dirección means “your direction”; it takes an accent on ó.'),
  junto: w('рядом / возле', 'next to / beside', 'Junto a = рядом с, возле.', 'Junto a means “next to / beside”.'),
  las: w('определённый артикль, женский множественный', 'the, feminine plural', 'Согласуется с rocas.', 'Agrees with rocas.'),
  rocas: w('скалы / камни', 'rocks', 'Женское множественное число.', 'A feminine plural noun.'),
  me: w('меня / мне / себя', 'me / myself', 'Безударное местоимение перед спрягаемым глаголом: me aferro.', 'An unstressed pronoun before a conjugated verb: me aferro.'),
  aferro: w('я цепляюсь / держусь', 'I cling / hold on', 'Aferrarse a = крепко держаться за что-то; здесь me aferro al timón.', 'Aferrarse a means to hold tightly onto something; here me aferro al timón.'),
  al: w('к / за + мужской артикль', 'to the / onto the', 'Обязательное слияние a + el = al.', 'The required contraction a + el = al.'),
  timón: w('штурвал / руль судна', 'helm / rudder', 'El timón управляет направлением корабля.', 'The timón controls the direction of a boat.'),
  llévame: w('отведи / отвези меня', 'take me', 'Утвердительная команда llevar для tú: lleva + me. Ударение сохраняет произношение.', 'The affirmative tú command of llevar: lleva + me. The accent preserves the stress.'),
  dónde: w('куда / где?', 'where?', 'С ударением в прямом или косвенном вопросе: ¿a dónde?', 'Accented in direct or indirect questions: ¿a dónde?'),
  lo: w('это / его', 'it', 'Безударное местоимение: no lo sé = «я этого не знаю».', 'An unstressed object pronoun: no lo sé means “I do not know it”.'),
  donde: w('где / куда', 'where / wherever', 'Без ударения в относительной конструкции: a donde sea.', 'No accent in a relative construction: a donde sea.'),
  sea: w('было бы / ни было', 'may be / it might be', 'Сослагательная форма ser. A donde sea = «куда угодно».', 'The subjunctive form of ser. A donde sea means “wherever”.'),
  quiera: w('захочет / пожелает', 'may want / chooses', 'Сослагательная форма querer после неопределённого a donde sea que.', 'A subjunctive form of querer after the indefinite a donde sea que.'),
  la: w('определённый артикль, женский', 'the, feminine', 'Согласуется с marea.', 'Agrees with marea.'),
  marea: w('прилив / течение', 'tide', 'Здесь олицетворена: течение само выбирает направление.', 'Personified here: the tide chooses the direction.'),
  quieras: w('ты захочешь / хочешь', 'you may want / you want', 'Сослагательная форма querer для tú после a donde.', 'The tú subjunctive form of querer after a donde.'),
  ve: w('иди', 'go', 'Утвердительная команда ir для tú. В строке: a donde quieras, ve.', 'The affirmative tú command of ir. In the line: a donde quieras, ve.'),
  bailando: w('танцуя', 'dancing', 'Герундий bailar: основа bail- + -ando.', 'The gerund of bailar: stem bail- + -ando.'),
  haciendo: w('делая', 'doing / making', 'Неправильный герундий hacer: haciendo.', 'The irregular gerund of hacer: haciendo.'),
  buenamente: w('как только возможно / по мере сил', 'as best as possible', 'Lo que buenamente pueda = всё, что смогу, насколько хватит сил.', 'Lo que buenamente pueda means whatever I can reasonably manage.'),
  pueda: w('я смогу / могу — сослагательное', 'I may be able to / can', 'Сослагательная форма poder для yo после lo que.', 'The yo present subjunctive of poder after lo que.'),
  te: w('тебя / тебе', 'you / to you', 'Безударное местоимение: te llevaré = «я отвезу тебя».', 'An unstressed object pronoun: te llevaré means “I will take you”.'),
  llevaré: w('я отведу / отвезу', 'I will take', 'Будущее время llevar для yo; ударение на é.', 'The yo future form of llevar; it takes an accent on é.'),
  volar: w('летать', 'to fly', 'Инфинитив на -ar.', 'An -ar infinitive.'),
  vuelas: w('ты летаешь', 'you fly', 'Volar меняет o→ue в ударной форме tú.', 'Volar changes o→ue in the stressed tú form.'),
  por: w('из-за / по / через', 'because of / by / through', 'Por gravedad = из-за действия гравитации.', 'Por gravedad means because of gravity.'),
  gravedad: w('гравитация / сила тяжести', 'gravity', 'Женское существительное: la gravedad.', 'A feminine noun: la gravedad.'),
  nos: w('нас / нам / себя', 'us / ourselves', 'В nos vamos — часть возвратного глагола irse: «мы уходим / движемся».', 'In nos vamos, it belongs to irse: “we leave / we are going”.'),
  vamos: w('мы идём / движемся', 'we go / are going', 'Форма ir для nosotros; vamos a + infinitivo = «мы собираемся».', 'The nosotros form of ir; vamos a + infinitive means “we are going to”.'),
  caer: w('падать', 'to fall', 'Инфинитив; после vamos a остаётся неизменным.', 'An infinitive; it stays unchanged after vamos a.'),
  si: w('если', 'if', 'Без ударения: условный союз. Sí с ударением = «да».', 'Without an accent, it introduces a condition. Sí with an accent means “yes”.'),
  estrellar: w('разбить / врезать', 'to crash / smash', 'Me voy a estrellar = я собираюсь разбиться / врезаться.', 'Me voy a estrellar means I am going to crash.'),
  qué: w('что / какой!', 'what / how!', 'Здесь в восклицании qué gusto — «как приятно».', 'Here in the exclamation qué gusto: “what a pleasure”.'),
  gusto: w('удовольствие / радость', 'pleasure', 'Qué gusto = как приятно / какое удовольствие.', 'Qué gusto means “what a pleasure / how nice”.'),
  hacerlo: w('сделать это', 'to do it', 'Hacer + lo: местоимение прикреплено к инфинитиву.', 'Hacer + lo: the object pronoun attaches to the infinitive.'),
  contigo: w('с тобой', 'with you', 'Особая слитная форма con + ti = contigo.', 'A special fused form: con + ti = contigo.'),
  lomos: w('спина животного', 'an animal’s back', 'A lomos de = верхом на, на спине у.', 'A lomos de means riding on the back of.'),
  dragón: w('дракон', 'dragon', 'Мужское существительное с ударением на ó.', 'A masculine noun with an accent on ó.'),
  acércame: w('подведи / приблизь меня', 'bring me closer', 'Команда acercar для tú + me; ударение сохраняет правильный слог.', 'The tú command of acercar + me; the accent preserves the stress.'),
  sol: w('солнце', 'sun', 'Мужское существительное: el sol.', 'A masculine noun: el sol.'),
  rompamos: w('давай(те) разобьём', 'let us break', 'Сослагательная форма romper для nosotros, используемая как призыв.', 'The nosotros subjunctive of romper, used as a “let’s” command.'),
  neutrón: w('нейтрон', 'neutron', 'Научное существительное; ударение на ó.', 'A scientific noun with an accent on ó.'),
  tras: w('после / за', 'after / behind', 'Tras la explosión = после взрыва.', 'Tras la explosión means after the explosion.'),
  explosión: w('взрыв', 'explosion', 'Женское существительное с ударением на ó.', 'A feminine noun with an accent on ó.'),
  nuestro: w('наш', 'our', 'Мужская форма перед barco.', 'Masculine form before barco.'),
  barco: w('лодка / корабль', 'boat / ship', 'Обычное нейтральное слово, в отличие от поэтического bajel.', 'An everyday neutral word, unlike the poetic bajel.'),
  huimos: w('мы убегаем / спасаемся', 'we flee / escape', 'Форма huir для nosotros; h не произносится.', 'The nosotros form of huir; h is silent.'),
  ahora: w('сейчас / теперь', 'now', 'Наречие времени.', 'An adverb of time.'),
  ya: w('уже / теперь', 'already / now', 'Подчёркивает, что новое состояние уже наступило.', 'Emphasizes that the new state has already begun.'),
  estamos: w('мы находимся / мы есть', 'we are', 'Форма estar для nosotros; здесь временное состояние и совместное положение.', 'The nosotros form of estar; here it marks a current state and being together.'),
  juntos: w('вместе', 'together', 'Множественная мужская/смешанная форма, согласована с los dos.', 'Masculine/mixed plural agreeing with los dos.'),
  los: w('определённый артикль, мужской множественный', 'the, masculine plural', 'Los dos = оба.', 'Los dos means “both”.'),
  dos: w('два / оба', 'two / both', 'Los dos — оба человека.', 'Los dos refers to both people.'),
  miro: w('я смотрю', 'I look', 'Форма mirar для yo. Te miro = я смотрю на тебя.', 'The yo form of mirar. Te miro means I look at you.'),
  sonrío: w('я улыбаюсь', 'I smile', 'Форма sonreír для yo; í сохраняет ударение и раздельное звучание.', 'The yo form of sonreír; í marks the stress and hiatus.'),
  paso: w('я передаю', 'I pass / hand', 'Pasar algo a alguien = передать что-то кому-то.', 'Pasar algo a alguien means to hand something to someone.'),
  'uh-uh-uh': w('вокализация', 'vocalization', 'Не несёт отдельного лексического значения.', 'It carries no separate lexical meaning.'),
  'uh-uh-uh-uh-uh': w('вокализация', 'vocalization', 'Ритмический припев без слов.', 'A rhythmic refrain without words.'),
  eh: w('междометие', 'interjection', 'Ритмический возглас.', 'A rhythmic exclamation.'),
  'ay-ay-ay-ay-ay': w('междометие / вокализация', 'interjection / vocalization', 'Эмоциональный звук без буквального перевода.', 'An emotional sound without a literal translation.'),
}

const lyrics = [
  line(7.84, 'Yo no sé nadar y tú no nadas bien', 'Я не умею плавать, и ты плаваешь не очень хорошо.', 'I cannot swim, and you do not swim very well.', 'No sé + infinitivo выражает отсутствие умения; yo и tú создают параллель.', 'No sé + infinitive expresses lack of ability; yo and tú create a parallel.'),
  line(13.48, 'Y en alta mar ninguno hace pie', 'И в открытом море ни один из нас не достаёт ногами дна.', 'And in the open sea neither of us can touch the bottom.', 'En alta mar и hacer pie — устойчивые выражения.', 'En alta mar and hacer pie are fixed expressions.'),
  line(18.12, 'Pero chapotear', 'Но плескаться…', 'But splashing about…', 'Инфинитив вынесен отдельно ради ритма; мысль продолжается в следующей строке.', 'The infinitive stands alone for rhythm; the sentence continues in the next line.'),
  line(20.3, 'Y flotar sí sabemos', 'И держаться на воде мы всё-таки умеем.', 'And we do know how to float.', 'Sí после инфинитива усиливает противопоставление: это мы как раз умеем.', 'Sí adds emphatic contrast: this is something we do know how to do.'),
  line(23.2, 'Así que', 'Так что…', 'So…', 'Связка вводит результат предыдущей мысли.', 'This connector introduces the result of the previous idea.'),
  line(24.3, 'Voy a construir un velero, un bajel', 'Я построю парусник, корабль.', 'I am going to build a sailboat, a vessel.', 'Voy a + infinitivo — ближайший план; bajel добавляет поэтический оттенок.', 'Voy a + infinitive expresses a plan; bajel adds a poetic tone.'),
  line(30.96, 'Para perseguir pájaros de Portugal', 'Чтобы гнаться за птицами из Португалии.', 'To chase birds from Portugal.', 'Para + infinitivo сообщает цель действия.', 'Para + infinitive gives the purpose of the action.'),
  line(35.6, 'Y tu estela en el mar', 'И за твоим следом на море.', 'And your wake on the sea.', 'Estela — образ следа, оставленного лодкой.', 'Estela is the trail left by a boat.'),
  line(38.5, 'Y así no echarte de menos', 'И так не скучать по тебе.', 'And that way not miss you.', 'Echar de menos — неделимое выражение; te прикреплено к инфинитиву.', 'Echar de menos is a fixed phrase; te attaches to the infinitive.'),
  line(42.56, 'Y mientras navego en tu dirección', 'И пока я плыву в твоём направлении…', 'And while I sail in your direction…', 'Mientras соединяет одновременные действия.', 'Mientras links actions happening at the same time.'),
  line(47.64, 'Junto a las rocas, me aferro al timón', 'Возле скал я крепко держусь за штурвал.', 'Beside the rocks, I cling to the helm.', 'Aferrarse a требует a; a + el превращается в al.', 'Aferrarse a takes a; a + el contracts to al.'),
  line(52.28, 'Llévame, ¿a dónde?, no lo sé', 'Отвези меня — куда? Я не знаю.', 'Take me—where? I do not know.', 'Llévame — команда с прикреплённым me; no lo sé = «я этого не знаю».', 'Llévame is a command with attached me; no lo sé means “I do not know it”.'),
  line(58.0, 'A donde sea que quiera la marea', 'Куда угодно, куда захочет течение.', 'Wherever the tide may choose.', 'Неопределённость вызывает сослагательные sea и quiera.', 'Indefiniteness triggers the subjunctive forms sea and quiera.'),
  line(62.84, 'Y llévame a donde quieras, ve', 'И отвези меня куда захочешь — вперёд.', 'And take me wherever you want—go.', 'Quieras — сослагательное, ve — короткая команда от ir.', 'Quieras is subjunctive; ve is the short tú command of ir.'),
  line(67.48, 'Tú bailando y yo haciendo lo que buenamente pueda', 'Ты танцуешь, а я делаю всё, что в моих силах.', 'You dancing and me doing whatever I reasonably can.', 'Эллиптическая фраза без estamos: герундии рисуют два параллельных действия.', 'An elliptical phrase without estamos: the gerunds paint two parallel actions.'),
  line(72.04, 'Y llévame, a donde no lo sé', 'И отвези меня — куда, я не знаю.', 'And take me—where, I do not know.', 'Повтор припева; dónde подразумевает вопрос, donde — относительную связь.', 'A chorus repetition; dónde implies a question, while donde is relative.'),
  line(77.6, 'A donde sea que quiera la marea', 'Куда угодно, куда захочет течение.', 'Wherever the tide may choose.', 'Sea que quiera создаёт открытое, неопределённое направление.', 'Sea que quiera creates an open, unspecified destination.'),
  line(81.64, 'Y llévame, que yo te llevaré', 'И отвези меня — а я отвезу тебя.', 'And take me, and I will take you.', 'Te llevaré — будущее время и обещание взаимности.', 'Te llevaré is future tense and a promise of reciprocity.'),
  line(90.32, 'Yo no sé volar y tú no vuelas bien', 'Я не умею летать, и ты летаешь не очень хорошо.', 'I cannot fly, and you do not fly very well.', 'Повторяет модель первой строки; volar меняет o→ue в vuelas.', 'It mirrors the first line; volar changes o→ue in vuelas.'),
  line(95.48, 'Y por gravedad nos vamos a caer', 'И из-за гравитации мы упадём.', 'And because of gravity we are going to fall.', 'Nos vamos a caer — разговорная конструкция ближайшего будущего.', 'Nos vamos a caer is a conversational near-future construction.'),
  line(100.68, 'Si me voy a estrellar', 'Если уж я разобьюсь…', 'If I am going to crash…', 'Si без ударения вводит условие.', 'Si without an accent introduces a condition.'),
  line(104.2, 'Qué gusto hacerlo contigo', 'Как приятно сделать это с тобой.', 'What a pleasure to do it with you.', 'Qué gusto — восклицание; hacerlo и contigo — слитные формы с местоимениями.', 'Qué gusto is an exclamation; hacerlo and contigo fuse with pronouns.'),
  line(110.08, 'Llévame a lomos de un dragón', 'Унеси меня верхом на драконе.', 'Take me riding on a dragon’s back.', 'A lomos de — образное выражение «верхом на».', 'A lomos de is the figurative phrase “riding on the back of”.'),
  line(114.4, 'Acércame al sol', 'Приблизь меня к солнцу.', 'Bring me closer to the sun.', 'Команда acerca + me; al = a + el.', 'The command acerca + me; al = a + el.'),
  line(117.4, 'Rompamos el neutrón', 'Давай расщепим нейтрон.', 'Let us break the neutron.', 'Rompamos — призыв от nosotros: «давай(те) сделаем».', 'Rompamos is a nosotros “let’s” command.'),
  line(120.6, 'Y tras la explosión', 'И после взрыва…', 'And after the explosion…', 'Tras — компактный синоним después de.', 'Tras is a compact synonym of después de.'),
  line(123.2, 'En nuestro barco huimos', 'Мы спасаемся на нашей лодке.', 'We escape in our boat.', 'Huimos — форма huir для nosotros.', 'Huimos is the nosotros form of huir.'),
  line(125.88, 'Y ahora que ya estamos juntos los dos', 'И теперь, когда мы уже вдвоём…', 'And now that the two of us are finally together…', 'Ahora que вводит новую ситуацию; los dos = оба.', 'Ahora que introduces a new situation; los dos means both.'),
  line(130.56, 'Te miro, sonrío y te paso el timón', 'Я смотрю на тебя, улыбаюсь и передаю тебе штурвал.', 'I look at you, smile and hand you the helm.', 'Три формы yo соединены союзом y; te выполняет две разные объектные роли.', 'Three yo forms are joined by y; te has two object roles.'),
  line(135.44, 'Llévame, ¿a dónde?, no lo sé', 'Отвези меня — куда? Я не знаю.', 'Take me—where? I do not know.', 'Возвращение припева.', 'The chorus returns.'),
  line(141.08, 'A donde sea que quiera la marea', 'Куда угодно, куда захочет течение.', 'Wherever the tide may choose.', 'Сослагательное сохраняет ощущение неизвестности.', 'The subjunctive keeps the destination open and unknown.'),
  line(146.16, 'Y llévame a donde quieras, ve', 'И отвези меня куда захочешь — вперёд.', 'And take me wherever you want—go.', 'Команда и сослагательное стоят рядом.', 'A command and subjunctive form appear together.'),
  line(150.84, 'Tú bailando y yo haciendo lo que buenamente pueda', 'Ты танцуешь, а я делаю всё, что в моих силах.', 'You dancing and me doing whatever I reasonably can.', 'Buenamente смягчает обещание: сделать столько, сколько реально возможно.', 'Buenamente softens the promise: do as much as is reasonably possible.'),
  line(155.32, 'Y llévame (eh) a donde no lo sé', 'И отвези меня — куда, я не знаю.', 'And take me—where, I do not know.', 'Eh добавляет эмоциональный акцент к ритмическому варианту основной строки.', 'Eh adds emotional emphasis to this rhythmic variation of the main line.'),
  line(160.72, 'A donde sea que quiera la marea', 'Куда угодно, куда захочет течение.', 'Wherever the tide may choose.', 'Повтор закрепляет конструкцию a donde sea que.', 'The repetition reinforces a donde sea que.'),
  line(164.88, 'Y llévame, que yo te llevaré', 'И отвези меня — а я отвезу тебя.', 'And take me, and I will take you.', 'Llevaré — простое будущее.', 'Llevaré is simple future.'),
  line(171.2, 'Uh-uh-uh, uh-uh-uh', 'Вокализация.', 'Vocalization.', 'Ритмический фрагмент без лексического значения.', 'A rhythmic section without lexical meaning.'),
  line(176.0, 'Uh-uh-uh-uh-uh', 'Вокализация.', 'Vocalization.', 'Можно использовать для повторения мелодии перед финальным припевом.', 'Use it to internalize the melody before the final chorus.'),
  line(181.0, 'Uh-uh-uh, uh-uh-uh', 'Вокализация.', 'Vocalization.', 'Лексики нет; только ритм и дыхание.', 'No vocabulary here; only rhythm and breath.'),
  line(186.0, 'Uh-uh-uh-uh-uh (eh)', 'Вокализация и возглас.', 'Vocalization and exclamation.', 'Eh добавляет разговорный эмоциональный акцент.', 'Eh adds an informal emotional accent.'),
  line(192.16, 'Llévame, ¿a dónde?, no lo sé', 'Отвези меня — куда? Я не знаю.', 'Take me—where? I do not know.', 'Финальный припев начинается с главной команды песни.', 'The final chorus begins with the song’s central command.'),
  line(197.6, 'A donde sea que quiera la marea', 'Куда угодно, куда захочет течение.', 'Wherever the tide may choose.', 'Море и течение остаются метафорой неизвестного пути.', 'The sea and tide remain a metaphor for an unknown path.'),
  line(201.48, 'Y llévame y yo te llevaré (eh)', 'И отвези меня, а я отвезу тебя.', 'And take me, and I will take you.', 'Две стороны обещают поддерживать друг друга.', 'Both sides promise to carry and support each other.'),
  line(204.04, 'Tú bailando y yo haciendo lo que buenamente pueda', 'Ты танцуешь, а я делаю всё, что в моих силах.', 'You dancing and me doing whatever I reasonably can.', 'Название песни Haré lo que pueda развивает ту же идею: «сделаю всё, что смогу».', 'The title Haré lo que pueda develops the same idea: “I will do what I can”.'),
  line(210.64, 'Y llévame y yo te llevaré (eh)', 'И отвези меня, а я отвезу тебя.', 'And take me, and I will take you.', 'Повтор обещания взаимности.', 'The mutual promise repeats.'),
  line(214.8, 'Ay-ay-ay-ay-ay', 'Эмоциональная вокализация.', 'Emotional vocalization.', 'Ay передаёт эмоцию, но здесь не требует буквального перевода.', 'Ay conveys emotion but has no literal translation here.'),
  line(217.84, 'Llévame (llévame) y yo te llevaré', 'Отвези меня — отвези — а я отвезу тебя.', 'Take me—take me—and I will take you.', 'Финальная строка соединяет команду и обещание в будущем времени.', 'The final line joins a command with a future promise.'),
]

const cards = [
  ['no sé + infinitivo', 'я не умею / не знаю, как', 'I do not know how to', 'No sé nadar.'],
  ['en alta mar', 'в открытом море', 'on the open sea', 'En alta mar ninguno hace pie.'],
  ['hacer pie', 'доставать ногами дна', 'to touch the bottom', 'Ninguno hace pie.'],
  ['chapotear', 'плескаться', 'to splash about', 'Pero chapotear sí sabemos.'],
  ['flotar', 'держаться на воде', 'to float', 'Sabemos flotar.'],
  ['voy a + infinitivo', 'я собираюсь сделать', 'I am going to do', 'Voy a construir un velero.'],
  ['el velero', 'парусник', 'sailboat', 'Voy a construir un velero.'],
  ['el bajel', 'судно — поэтическое', 'vessel — poetic', 'Un velero, un bajel.'],
  ['perseguir', 'преследовать / гнаться за', 'to chase / pursue', 'Para perseguir pájaros.'],
  ['la estela', 'след судна на воде', 'wake / trail on water', 'Tu estela en el mar.'],
  ['echar de menos', 'скучать по', 'to miss', 'No quiero echarte de menos.'],
  ['navegar', 'плыть на судне', 'to sail', 'Navego en tu dirección.'],
  ['aferrarse a', 'крепко держаться за', 'to cling to', 'Me aferro al timón.'],
  ['el timón', 'штурвал / руль', 'helm / rudder', 'Te paso el timón.'],
  ['llévame', 'отведи / отвези меня', 'take me', 'Llévame a donde quieras.'],
  ['a donde sea', 'куда угодно', 'wherever', 'A donde sea que quiera la marea.'],
  ['la marea', 'прилив / течение', 'tide', 'Que quiera la marea.'],
  ['ve', 'иди', 'go', 'A donde quieras, ve.'],
  ['bailando', 'танцуя', 'dancing', 'Tú bailando.'],
  ['haciendo', 'делая', 'doing / making', 'Yo haciendo lo que pueda.'],
  ['lo que pueda', 'то, что смогу', 'whatever I can', 'Haré lo que pueda.'],
  ['te llevaré', 'я отвезу / поведу тебя', 'I will take you', 'Yo te llevaré.'],
  ['nos vamos a caer', 'мы собираемся упасть', 'we are going to fall', 'Por gravedad nos vamos a caer.'],
  ['estrellarse', 'разбиться / врезаться', 'to crash', 'Me voy a estrellar.'],
  ['qué gusto', 'как приятно', 'what a pleasure', 'Qué gusto hacerlo contigo.'],
  ['contigo', 'с тобой', 'with you', 'Hacerlo contigo.'],
  ['a lomos de', 'верхом на / на спине', 'riding on the back of', 'A lomos de un dragón.'],
  ['acércame', 'приблизь меня', 'bring me closer', 'Acércame al sol.'],
  ['rompamos', 'давай(те) разобьём', 'let us break', 'Rompamos el neutrón.'],
  ['huimos', 'мы спасаемся / убегаем', 'we flee / escape', 'En nuestro barco huimos.'],
  ['los dos', 'оба / мы вдвоём', 'both of us', 'Estamos juntos los dos.'],
  ['sonrío', 'я улыбаюсь', 'I smile', 'Te miro y sonrío.'],
].map(([es, ru, en, example]) => ({ es, en: l(ru, en), example }))

export const hareLoQuePuedaSongLesson = {
  id: 'hare-lo-que-pueda-song', bilingual: true,
  title: 'Haré lo que pueda',
  eyebrow: l('Песня · Puño Dragón · A1', 'Song · Puño Dragón · A1'),
  description: l('Смотри клип с синхронным текстом, разбирай каждое слово и превращай морские метафоры песни в живой испанский.', 'Watch the video with synced lyrics, explore every word and turn the song’s sea metaphors into usable Spanish.'),
  accent: 'blue', minutes: 58, icon: 'Music2',
  guideKicker: l('РАЗБОР ПЕСНИ · СМЫСЛ И ГРАММАТИКА', 'SONG BREAKDOWN · MEANING AND GRAMMAR'),
  modeCopy: {
    song: { label: l('Видео + синхронный текст', 'Video + synced lyrics'), description: l('Следи за строкой в реальном времени, нажимай для перемотки и наводи на каждое слово.', 'Follow each line in real time, click to seek and hover over every word.') },
    guide: { label: l('Смысл и грамматика', 'Meaning and grammar'), description: l('Разбери историю, метафоры, команды, местоимения, будущее и subjuntivo.', 'Understand the story, metaphors, commands, pronouns, future and subjunctive.') },
    cards: { label: l('Главные карточки', 'Essential cards'), description: l('Выучи 32 самые полезные конструкции и образные слова песни.', 'Learn the 32 most useful patterns and vivid words from the song.') },
    match: { label: l('Сопоставление 4×4', '4×4 Match'), description: l('Свяжи выражения песни с точным смыслом.', 'Match the song expressions with their precise meanings.') },
    quiz: { label: l('Проверка понимания', 'Understanding quiz'), description: l('Проверь разницу sí/si, tú/tu, dónde/donde и важные формы.', 'Check sí/si, tú/tu, dónde/donde and the key verb forms.') },
    builder: { label: l('Собери строки', 'Build the lines'), description: l('Восстанови важные конструкции песни из перемешанных слов.', 'Rebuild important song patterns from shuffled words.') },
    compose: { label: l('Напиши по смыслу', 'Write from meaning'), description: l('Воспроизведи фразы без банка слов и пойми их структуру.', 'Recall the phrases without a word bank and understand their structure.') },
    vocab: { label: l('Все слова отдельно', 'Every word separately'), description: l('Пройди весь словарь песни в обе стороны, включая служебные слова и формы.', 'Review the complete song vocabulary in both directions, including function words and forms.') },
  },
  ui: {
    backToPlayground: l('Назад к урокам', 'Back to playground'), mastery: l('освоено', 'mastery'), modes: l('этапов', 'stages'), chooseMode: l('ЭТАПЫ УРОКА', 'LESSON STAGES'), practiceQuestion: l('Сначала проживи песню, затем разбери её', 'Experience the song first, then take it apart'), completed: l('Пройдено', 'Completed'), done: l('Готово', 'Done'), start: l('Начать', 'Start'), minutesShort: l('мин', 'min'), wordsLabel: l('главных карточки', 'essential cards'), phraseOfDay: l('Интерактивная песня', 'Interactive song'),
    back: l('Назад', 'Back'), exit: l('Выйти', 'Exit'), savedPhrases: l('Сохранённые фразы', 'Saved phrases'), cardTitle: l('Слова песни', 'Song Words'), spanish: l('Испанский', 'Spanish'), targetLanguage: l('Русский', 'English'), meaningLabel: l('ЗНАЧЕНИЕ', 'MEANING'), tapToSpanish: l('Нажми, чтобы вернуться к испанскому', 'Tap to return to Spanish'), playPronunciation: l('Прослушать произношение', 'Play Spanish pronunciation'), listenTitle: l('Слушай и связывай с мелодией', 'Listen and connect it to the melody'), listenBody: l('Повтори выражение, затем найди его в песне и пропой вместе с исполнителем.', 'Repeat the expression, then find it in the song and sing it with the artist.'), gotIt: l('Запомнил', 'Got it'), finish: l('Завершить', 'Finish'), previous: l('Назад', 'Previous'), startPractising: l('Перейти к практике', 'Start practising'), understand: l('Понятно', 'I understand'),
    matchKicker: l('СЛОВА ПЕСНИ · СОПОСТАВЛЕНИЕ', 'SONG WORDS · MATCH'), connectPairs: l('Соедини пары', 'Connect the pairs'), round: l('Раунд', 'Round'), of: l('из', 'of'), matched: l('готово', 'matched'), matchCorrect: l('¡Sí! Точный смысл.', '¡Sí! Exact meaning.'), matchWrong: l('Не эта пара — попробуй снова.', 'Not this pair—try again.'), finishMatching: l('Завершить', 'Finish matching'), nextFour: l('Следующие четыре', 'Next four'),
    quizKicker: l('ПЕСНЯ · ФОРМА И СМЫСЛ', 'SONG · FORM AND MEANING'), hardOne: l('Хочешь сохранить?', 'Save this one?'), correctTitle: '¡Muy bien!', wrongTitle: l('Пока не совсем.', 'Not quite yet.'), naturalAnswer: l('Это точный вариант.', 'That is the precise answer.'), answerIs: l('Ответ:', 'The answer is'), sayIt: l('Скажи строку в ритме.', 'Say the line in rhythm.'), next: l('Дальше', 'Next'),
    sentenceKicker: l('ВОССТАНОВИ СТРОКУ', 'REBUILD THE LINE'), buildPlaceholder: l('Собери фразу здесь…', 'Build the phrase here…'), perfect: '¡Perfecto!', wordOrder: l('Проверь порядок, местоимение и ударение.', 'Check the order, pronoun and accent.'), checkSentence: l('Проверить', 'Check phrase'),
    composerKicker: l('ВСПОМНИ ФРАЗУ · БЕЗ БАНКА СЛОВ', 'RECALL THE PHRASE · NO WORD BANK'), yourPhrase: l('Твоя фраза', 'Your phrase'), composePlaceholder: l('Напиши по-испански…', 'Write in Spanish…'), hideHint: l('Скрыть опору', 'Hide hint'), showHint: l('Нужна опора?', 'Need a hint?'), words: l('слов', 'words'), checkPhrase: l('Проверить фразу', 'Check phrase'), finishLesson: l('Завершить этап', 'Finish stage'), nextPhrase: l('Следующая фраза', 'Next phrase'), accentTitle: l('Смысл верный — поправь ударение.', 'Meaning is right—fix the accent.'), writeIt: l('Напиши так:', 'Write it like this:'), verbFormTitle: l('Нужна форма из песни.', 'Use the song form.'), workFormMessage: l('Сравни форму глагола со строкой песни.', 'Compare the verb form with the song line.'), infinitiveTitle: l('Проверь инфинитив.', 'Check the infinitive.'), returnFormMessage: l('После модального глагола нужен инфинитив.', 'An infinitive follows the modal verb.'), noPositionTitle: l('Проверь место no.', 'Check the position of no.'), naturalVariant: l('Естественная версия:', 'A natural version:'), notYetTitle: l('Пока не совпало.', 'Not quite yet.'), compareVariant: l('Сравни со строкой:', 'Compare with the line:'),
  },
  song: {
    videoId: '_SiNwlQ6jgQ', title: 'Puño Dragón — HARÉ LO QUE PUEDA',
    kicker: l('ИНТЕРАКТИВНОЕ АУДИРОВАНИЕ', 'INTERACTIVE LISTENING'),
    instructions: l('Запусти видео. Текущая строка подсвечивается автоматически; нажми любую строку, чтобы перемотать. Наведи на слово или нажми его — ниже появятся перевод и грамматическое объяснение.', 'Play the video. The current line highlights automatically; click any line to seek. Hover over or tap a word to see its translation and grammar below.'),
    nowLabel: l('СЕЙЧАС / ВЫБРАННАЯ СТРОКА', 'NOW / SELECTED LINE'), wordLabel: l('СЛОВО ПОД КУРСОРОМ', 'WORD UNDER THE CURSOR'), transcriptLabel: l('ПОЛНЫЙ ТЕКСТ', 'FULL LYRICS'), linesLabel: l('строк', 'lines'), transcriptHint: l('Нажми строку → перемотка', 'Click a line → seek'),
    studyTitle: l('Как проходить этот режим', 'How to study this mode'), studyNote: l('Первый раз просто смотри и следи за подсветкой. Второй — останавливай после каждой строфы и разбирай слова. Третий — закрой перевод, подпевай и предугадывай следующую строку.', 'First, simply watch and follow the highlight. Second, pause after each verse and inspect the words. Third, hide the translation mentally, sing along and predict the next line.'),
    finishLabel: l('Я разобрал песню', 'I studied the song'),
    fallbackWord: w('слово в контексте строки', 'a word in this line', 'Смотри перевод и объяснение всей строки рядом.', 'Use the line translation and explanation beside it.'),
    lines: lyrics, lexicon,
  },
  guide: [
    { title: l('О чём песня', 'What the song is about'), body: l('Два человека не умеют идеально плавать или летать, но готовы отправиться вместе куда угодно. Море, лодка, дракон и взрыв — игровые образы доверия: «веди меня, а потом я поведу тебя». Название Haré lo que pueda — «Я сделаю всё, что смогу» — не обещает невозможного, а обещает искреннее усилие.', 'Two people cannot swim or fly perfectly, yet they are ready to go anywhere together. The sea, boat, dragon and explosion are playful images of trust: “take me, and then I will take you”. The title Haré lo que pueda—“I will do what I can”—does not promise the impossible; it promises sincere effort.'), rule: 'llévame ↔ yo te llevaré · haré lo que pueda', examples: [['Llévame, que yo te llevaré.', l('Отвези меня, а я отвезу тебя.', 'Take me, and I will take you.')], ['Tú bailando y yo haciendo lo que buenamente pueda.', l('Ты танцуешь, а я делаю всё, что в моих силах.', 'You dancing and me doing whatever I can.')]] },
    { title: l('Уметь: saber + infinitivo', 'Ability: saber + infinitive'), body: l('По-испански практическое умение часто выражается через saber + инфинитив: sé nadar — умею плавать, sabemos flotar — умеем держаться на воде. No ставится перед sé. В песне sí после flotar подчёркивает контраст: плавать хорошо не умеем, но держаться на воде всё-таки умеем.', 'Spanish often expresses a learned ability with saber + infinitive: sé nadar—know how to swim, sabemos flotar—know how to float. No comes before sé. In the song, sí after flotar adds contrast: they cannot swim well, but they do know how to float.'), rule: 'no sé + infinitivo · sí sabemos + infinitivo', examples: [['Yo no sé nadar.', l('Я не умею плавать.', 'I do not know how to swim.')], ['Flotar sí sabemos.', l('А вот держаться на воде мы умеем.', 'We do know how to float.')], ['sí ≠ si', l('sí = да / действительно · si = если', 'sí = yes / indeed · si = if')]] },
    { title: l('Команды и местоимения', 'Commands and attached pronouns'), body: l('В утвердительной команде короткое местоимение прикрепляется к концу: lleva + me → llévame, acerca + me → acércame. Ударение добавляется, чтобы сохранить исходное произношение. То же прикрепление возможно к инфинитиву: echar + te → echarte, hacer + lo → hacerlo.', 'With affirmative commands, the short pronoun attaches to the end: lleva + me → llévame, acerca + me → acércame. The accent preserves the original stress. Pronouns can also attach to infinitives: echar + te → echarte, hacer + lo → hacerlo.'), rule: 'lleva + me = llévame · hacer + lo = hacerlo', examples: [['Llévame.', l('Отведи / отвези меня.', 'Take me.')], ['Acércame al sol.', l('Приблизь меня к солнцу.', 'Bring me closer to the sun.')], ['No quiero echarte de menos.', l('Я не хочу скучать по тебе.', 'I do not want to miss you.')]] },
    { title: l('Неизвестный путь и subjuntivo', 'An unknown path and the subjunctive'), body: l('A donde sea que quiera la marea не сообщает конкретного места. Именно неопределённость вызывает subjuntivo: sea от ser, quiera от querer. В a donde quieras говорящий также оставляет выбор открытым собеседнику. Не нужно пока строить всю систему subjuntivo; запомни эти конструкции целиком.', 'A donde sea que quiera la marea gives no specific destination. This uncertainty triggers the subjunctive: sea from ser and quiera from querer. A donde quieras also leaves the choice open to the other person. You do not need the whole subjunctive system yet; memorize these chunks.'), rule: 'a donde sea · a donde quieras · lo que pueda', examples: [['A donde sea que quiera la marea.', l('Куда угодно, куда захочет течение.', 'Wherever the tide may choose.')], ['A donde quieras.', l('Куда ты захочешь.', 'Wherever you want.')], ['Lo que pueda.', l('То, что смогу.', 'Whatever I can.')]] },
    { title: l('План, процесс и будущее', 'Plan, process and future'), body: l('Voy a construir и nos vamos a caer — ближайший план или ожидаемый результат через ir a + инфинитив. Bailando и haciendo — герундии, которые показывают действие в процессе. Llevaré и название haré — простое будущее: я отвезу, я сделаю.', 'Voy a construir and nos vamos a caer express a plan or expected result with ir a + infinitive. Bailando and haciendo are gerunds showing action in progress. Llevaré and the title haré are simple future: I will take, I will do.'), rule: 'voy a construir · estoy haciendo · te llevaré / haré', examples: [['Voy a construir un velero.', l('Я собираюсь построить парусник.', 'I am going to build a sailboat.')], ['Tú bailando y yo haciendo…', l('Ты танцуешь, а я делаю…', 'You dancing and me doing…')], ['Yo te llevaré.', l('Я отвезу тебя.', 'I will take you.')]] },
    { title: l('Морской словарь и поэтический регистр', 'Sea vocabulary and poetic register'), body: l('Velero — обычный парусник; barco — нейтральная лодка или корабль; bajel — литературное «судно». Estela — след на воде, timón — руль или штурвал, marea — прилив и течение. Эти слова создают центральную метафору: отношения как совместное путешествие без известного маршрута.', 'Velero is a sailboat; barco is a neutral boat or ship; bajel is the literary “vessel”. Estela is a wake, timón a helm or rudder, and marea the tide. Together they build the central metaphor: a relationship as a shared journey without a known route.'), rule: 'velero · bajel · estela · timón · marea', examples: [['Me aferro al timón.', l('Я держусь за штурвал.', 'I cling to the helm.')], ['Te paso el timón.', l('Я передаю тебе штурвал.', 'I hand you the helm.')], ['Que quiera la marea.', l('Как захочет течение.', 'As the tide may choose.')]] },
  ],
  words: cards,
  vocabulary: Object.entries(lexicon).map(([es, entry]) => ({ es, en: entry.meaning, example: entry.note })),
  quiz: [
    { prompt: l('Что означает «no sé nadar»?', 'What does “no sé nadar” mean?'), options: [l('я не умею плавать', 'I cannot swim'), l('я не хочу плавать', 'I do not want to swim'), l('я не плаваю сейчас', 'I am not swimming now')], answer: l('я не умею плавать', 'I cannot swim'), explanation: l('Saber + infinitivo выражает умение.', 'Saber + infinitive expresses an ability.') },
    { prompt: l('Выбери «да / действительно».', 'Choose “yes / indeed”.'), options: ['sí', 'si', 'sé'], answer: 'sí', explanation: l('Sí с ударением = «да»; si без ударения = «если».', 'Sí with an accent means yes; si without an accent means if.') },
    { prompt: l('Выбери «если».', 'Choose “if”.'), options: ['si', 'sí', 'sea'], answer: 'si', explanation: l('У условного союза si нет ударения.', 'The conditional conjunction si has no accent.') },
    { prompt: 'Voy a ___ un velero.', options: ['construir', 'construyo', 'construyendo'], answer: 'construir', explanation: l('После voy a нужен инфинитив.', 'Voy a is followed by an infinitive.') },
    { prompt: l('Что такое bajel?', 'What is a bajel?'), options: [l('поэтическое «судно»', 'a poetic “vessel”'), l('штурвал', 'a helm'), l('прилив', 'a tide')], answer: l('поэтическое «судно»', 'a poetic “vessel”'), explanation: l('В обычной речи чаще barco.', 'Barco is more common in everyday speech.') },
    { prompt: l('Как сказать «скучать по тебе»?', 'How do you say “to miss you”?'), options: ['echarte de menos', 'hacerte menos', 'echar de tu'], answer: 'echarte de menos', explanation: l('Echar de menos — устойчивое выражение; te прикреплено к инфинитиву.', 'Echar de menos is fixed; te attaches to the infinitive.') },
    { prompt: 'a + el timón = ___', options: ['al timón', 'a el timón', 'del timón'], answer: 'al timón', explanation: 'A + el = al.' },
    { prompt: l('Из чего построено llévame?', 'How is llévame formed?'), options: ['lleva + me', 'llevar + mí', 'llega + me'], answer: 'lleva + me', explanation: l('Это команда llevar для tú с прикреплённым me.', 'It is the tú command of llevar with attached me.') },
    { prompt: l('Почему в «a donde sea» используется sea?', 'Why does “a donde sea” use sea?'), options: [l('место неизвестно', 'the place is unspecified'), l('это прошедшее время', 'it is past tense'), l('sea означает море', 'sea means the sea')], answer: l('место неизвестно', 'the place is unspecified'), explanation: l('Неопределённость вызывает subjuntivo.', 'Uncertainty triggers the subjunctive.') },
    { prompt: l('«A donde quieras» означает…', '“A donde quieras” means…'), options: [l('куда ты захочешь', 'wherever you want'), l('где ты был', 'where you were'), l('почему ты уходишь', 'why you leave')], answer: l('куда ты захочешь', 'wherever you want'), explanation: l('Quieras — форма subjuntivo от querer для tú.', 'Quieras is the tú subjunctive of querer.') },
    { prompt: l('Какая команда означает «иди»?', 'Which command means “go”?'), options: ['ve', 'voy', 'vas'], answer: 've', explanation: l('Ve — утвердительная команда ir для tú.', 'Ve is the affirmative tú command of ir.') },
    { prompt: l('Какой герундий у hacer?', 'What is the gerund of hacer?'), options: ['haciendo', 'haciando', 'hago'], answer: 'haciendo', explanation: l('Hacer образует неправильный герундий haciendo.', 'Hacer has the irregular gerund haciendo.') },
    { prompt: l('«Lo que buenamente pueda» означает…', '“Lo que buenamente pueda” means…'), options: [l('всё, что в моих силах', 'whatever I reasonably can'), l('то, что я уже сделал', 'what I already did'), l('то, что ты хочешь', 'what you want')], answer: l('всё, что в моих силах', 'whatever I reasonably can'), explanation: l('Buenamente смягчает обещание, pueda — subjuntivo от poder.', 'Buenamente softens the promise; pueda is the subjunctive of poder.') },
    { prompt: l('Какое время у «te llevaré»?', 'What tense is “te llevaré”?'), options: [l('будущее', 'future'), l('настоящее', 'present'), l('прошедшее', 'past')], answer: l('будущее', 'future'), explanation: l('Окончание -é: «я отвезу тебя».', 'The -é ending means “I will take you”.') },
    { prompt: 'Volar → tú ___', options: ['vuelas', 'volas', 'vueles'], answer: 'vuelas', explanation: l('В настоящем volar меняет o→ue.', 'In the present, volar changes o→ue.') },
    { prompt: l('Что означает «nos vamos a caer»?', 'What does “nos vamos a caer” mean?'), options: [l('мы сейчас упадём', 'we are going to fall'), l('мы хотим летать', 'we want to fly'), l('мы уже упали', 'we already fell')], answer: l('мы сейчас упадём', 'we are going to fall'), explanation: l('Ir a + infinitivo выражает ожидаемое ближайшее событие.', 'Ir a + infinitive expresses an expected near-future event.') },
    { prompt: l('Выбери правильную форму «с тобой».', 'Choose the correct form for “with you”.'), options: ['contigo', 'con tú', 'con ti-go'], answer: 'contigo', explanation: l('Con + ti имеет особую слитную форму contigo.', 'Con + ti has the special fused form contigo.') },
    { prompt: l('Что означает «a lomos de un dragón»?', 'What does “a lomos de un dragón” mean?'), options: [l('верхом на драконе', 'riding on a dragon'), l('перед драконом', 'in front of a dragon'), l('внутри дракона', 'inside a dragon')], answer: l('верхом на драконе', 'riding on a dragon'), explanation: l('A lomos de — на спине животного, верхом на.', 'A lomos de means on an animal’s back, riding.') },
    { prompt: l('«Rompamos» здесь означает…', '“Rompamos” here means…'), options: [l('давай разобьём', 'let us break'), l('мы разбили', 'we broke'), l('ты разбиваешь', 'you break')], answer: l('давай разобьём', 'let us break'), explanation: l('Форма nosotros subjuntivo используется как призыв.', 'The nosotros subjunctive is used as a “let’s” command.') },
    { prompt: l('Что передаёт штурвал в песне?', 'What does handing over the helm suggest in the song?'), options: [l('доверие и смену ведущего', 'trust and taking turns leading'), l('потерю лодки', 'losing the boat'), l('отказ от путешествия', 'giving up the journey')], answer: l('доверие и смену ведущего', 'trust and taking turns leading'), explanation: l('Te paso el timón превращает морской предмет в метафору доверия.', 'Te paso el timón turns the sea object into a metaphor of trust.') },
  ],
  builder: [
    { translation: l('Я не умею плавать.', 'I do not know how to swim.'), answer: ['Yo', 'no', 'sé', 'nadar.'] },
    { translation: l('В открытом море ни один не достаёт дна.', 'In the open sea neither can touch the bottom.'), answer: ['En', 'alta', 'mar', 'ninguno', 'hace', 'pie.'] },
    { translation: l('А держаться на воде мы умеем.', 'We do know how to float.'), answer: ['Flotar', 'sí', 'sabemos.'] },
    { translation: l('Я собираюсь построить парусник.', 'I am going to build a sailboat.'), answer: ['Voy', 'a', 'construir', 'un', 'velero.'] },
    { translation: l('Чтобы гнаться за птицами из Португалии.', 'To chase birds from Portugal.'), answer: ['Para', 'perseguir', 'pájaros', 'de', 'Portugal.'] },
    { translation: l('Чтобы не скучать по тебе.', 'So as not to miss you.'), answer: ['Para', 'no', 'echarte', 'de', 'menos.'] },
    { translation: l('Я держусь за штурвал.', 'I cling to the helm.'), answer: ['Me', 'aferro', 'al', 'timón.'] },
    { translation: l('Отвези меня — куда? Я не знаю.', 'Take me—where? I do not know.'), answer: ['Llévame,', '¿a', 'dónde?,', 'no', 'lo', 'sé.'] },
    { translation: l('Куда угодно, куда захочет течение.', 'Wherever the tide may choose.'), answer: ['A', 'donde', 'sea', 'que', 'quiera', 'la', 'marea.'] },
    { translation: l('Ты танцуешь, а я делаю всё, что смогу.', 'You dancing and me doing whatever I can.'), answer: ['Tú', 'bailando', 'y', 'yo', 'haciendo', 'lo', 'que', 'pueda.'] },
    { translation: l('Я отвезу тебя.', 'I will take you.'), answer: ['Yo', 'te', 'llevaré.'] },
    { translation: l('Из-за гравитации мы упадём.', 'Because of gravity we are going to fall.'), answer: ['Por', 'gravedad', 'nos', 'vamos', 'a', 'caer.'] },
    { translation: l('Как приятно сделать это с тобой.', 'What a pleasure to do it with you.'), answer: ['Qué', 'gusto', 'hacerlo', 'contigo.'] },
    { translation: l('Унеси меня верхом на драконе.', 'Take me riding on a dragon.'), answer: ['Llévame', 'a', 'lomos', 'de', 'un', 'dragón.'] },
    { translation: l('Приблизь меня к солнцу.', 'Bring me closer to the sun.'), answer: ['Acércame', 'al', 'sol.'] },
    { translation: l('Давай разобьём нейтрон.', 'Let us break the neutron.'), answer: ['Rompamos', 'el', 'neutrón.'] },
    { translation: l('Теперь мы уже вдвоём.', 'Now the two of us are together.'), answer: ['Ahora', 'ya', 'estamos', 'juntos', 'los', 'dos.'] },
    { translation: l('Я смотрю на тебя, улыбаюсь и передаю тебе штурвал.', 'I look at you, smile and hand you the helm.'), answer: ['Te', 'miro,', 'sonrío', 'y', 'te', 'paso', 'el', 'timón.'] },
  ],
  compose: [
    { prompt: l('Напиши: «Я не умею плавать».', 'Write: “I do not know how to swim.”'), hint: 'yo · no · saber → sé · nadar', accepted: ['Yo no sé nadar.', 'No sé nadar.'], answer: 'No sé nadar.', explanation: l('No стоит перед sé, а nadar остаётся инфинитивом.', 'No comes before sé, and nadar stays infinitive.') },
    { prompt: l('Напиши: «Я собираюсь построить парусник».', 'Write: “I am going to build a sailboat.”'), hint: 'voy a · construir · un velero', accepted: ['Voy a construir un velero.', 'Yo voy a construir un velero.'], answer: 'Voy a construir un velero.', explanation: l('Voy a + инфинитив выражает план.', 'Voy a + infinitive expresses a plan.') },
    { prompt: l('Напиши: «Я держусь за штурвал».', 'Write: “I cling to the helm.”'), hint: 'me aferro a · a + el · timón', accepted: ['Me aferro al timón.', 'Yo me aferro al timón.'], answer: 'Me aferro al timón.', explanation: l('Aferrarse требует a; a + el = al.', 'Aferrarse takes a; a + el = al.') },
    { prompt: l('Напиши: «Отвези меня».', 'Write: “Take me.”'), hint: 'lleva + me · ударение', accepted: ['Llévame.', '¡Llévame!'], answer: 'Llévame.', explanation: l('Местоимение me прикрепляется к команде, ударение сохраняет произношение.', 'Me attaches to the command, and the accent preserves the stress.') },
    { prompt: l('Напиши: «Куда угодно».', 'Write: “Wherever.”'), hint: 'a donde · ser → sea', accepted: ['A donde sea.', 'Adonde sea.'], answer: 'A donde sea.', explanation: l('Неопределённое место требует sea.', 'An unspecified destination takes sea.') },
    { prompt: l('Напиши: «Я отвезу тебя».', 'Write: “I will take you.”'), hint: 'te · llevar → llevaré', accepted: ['Te llevaré.', 'Yo te llevaré.'], answer: 'Te llevaré.', explanation: l('Te стоит перед личной формой будущего llevaré.', 'Te comes before the conjugated future form llevaré.') },
    { prompt: l('Напиши: «Как приятно сделать это с тобой».', 'Write: “What a pleasure to do it with you.”'), hint: 'qué gusto · hacer + lo · contigo', accepted: ['Qué gusto hacerlo contigo.', '¡Qué gusto hacerlo contigo!'], answer: 'Qué gusto hacerlo contigo.', explanation: l('Qué имеет ударение; lo прикрепляется к hacer; con + ti = contigo.', 'Qué takes an accent; lo attaches to hacer; con + ti = contigo.') },
    { prompt: l('Напиши: «Я смотрю на тебя и улыбаюсь».', 'Write: “I look at you and smile.”'), hint: 'te miro · y · sonrío', accepted: ['Te miro y sonrío.', 'Yo te miro y sonrío.'], answer: 'Te miro y sonrío.', explanation: l('Две формы yo соединены союзом y; sonrío имеет ударение.', 'Two yo forms are linked by y; sonrío takes an accent.') },
  ],
}
