const l = (ru, en) => ({ ru, en })
const w = (ru, en, noteRu, noteEn) => ({ meaning: l(ru, en), note: l(noteRu, noteEn) })
const lx = (es, ru, en, noteRu, noteEn) => [es, w(ru, en, noteRu, noteEn)]
const line = (start, text, ru, en, noteRu, noteEn) => ({ start, text, translation: l(ru, en), explanation: l(noteRu, noteEn) })

const lexicon = Object.fromEntries([
  lx('tonto', 'глупец / глупый', 'fool / foolish', 'Здесь существительное: «глуп тот, кто…».', 'A noun here: “a fool is the one who…”.'),
  lx('el', 'определённый артикль, мужской', 'the, masculine', 'El que = тот, кто. Без ударения; él = он.', 'El que means “the one who”. No accent; él means “he”.'),
  lx('que', 'что / который / кто', 'that / which / who', 'Без ударения связывает части предложения.', 'Without an accent, it links clauses.'),
  lx('no', 'не / нет', 'not / no', 'Ставится перед глагольной группой.', 'Placed before the verb phrase.'),
  lx('entienda', 'понимает — subjuntivo', 'understands — subjunctive', 'Форма entender после обобщающего el que.', 'A form of entender after the generalizing el que.'),
  lx('cuenta', 'рассказывает', 'tells / recounts', 'Форма contar для él/ella; также может означать «счёт».', 'The él/ella form of contar; it can also mean “account”.'),
  lx('una', 'одна / неопределённый артикль', 'a / one, feminine', 'Женская форма перед leyenda и hembra.', 'Feminine form before leyenda and hembra.'),
  lx('leyenda', 'легенда', 'legend', 'Cuenta una leyenda = «легенда рассказывает».', 'Cuenta una leyenda means “a legend tells”.'),
  lx('hembra', 'самка; женщина — поэтически/архаично', 'female; woman — poetic/archaic', 'О человеке сегодня может звучать обезличивающе; здесь старинный балладный регистр.', 'For a person it can sound objectifying today; here it belongs to an old ballad register.'),
  lx('gitana', 'ромская женщина', 'Romani woman', 'Женская форма gitano. Это обозначение идентичности, не характеристика поведения.', 'Feminine of gitano. It names an identity, not a behavioral trait.'),
  lx('conjuró', 'заклинала / призвала', 'conjured / invoked', 'Прошедшее indefinido от conjurar; ударение на ó.', 'Preterite of conjurar; the accent marks the stress.'),
  lx('a', 'к / в / на', 'to / at', 'Предлог направления или адресата действия.', 'A preposition of direction or target.'),
  lx('la', 'определённый артикль, женский', 'the, feminine', 'Согласуется с luna, mujer, estampa.', 'Agrees with luna, mujer and estampa.'),
  lx('luna', 'луна', 'moon', 'Главный персонаж и символ песни.', 'The song’s central character and symbol.'),
  lx('hasta', 'до / вплоть до', 'until / up to', 'Hasta el amanecer = до рассвета.', 'Hasta el amanecer means until dawn.'),
  lx('amanecer', 'рассвет', 'dawn', 'Может быть существительным или инфинитивом «рассветать».', 'It can be a noun or the infinitive “to dawn”.'),
  lx('llorando', 'плача', 'crying', 'Герундий llorar: действие происходит одновременно с pedía.', 'The gerund of llorar: simultaneous with pedía.'),
  lx('pedía', 'просила', 'was asking / begged', 'Imperfecto передаёт продолжающуюся просьбу.', 'The imperfect describes an ongoing plea.'),
  lx('al', 'при / когда; к + артикль', 'upon / when; to the', 'Al + infinitivo = «когда что-то происходит»; также a + el = al.', 'Al + infinitive means “when something happens”; also a + el = al.'),
  lx('llegar', 'прибывать / наступать', 'to arrive / come', 'Al llegar el día = когда наступил день.', 'Al llegar el día means when day came.'),
  lx('día', 'день', 'day', 'Мужское слово несмотря на окончание -a: el día.', 'Masculine despite ending in -a: el día.'),
  lx('desposar', 'вступить в брак / обвенчаться', 'to marry / wed', 'Книжное слово; обычно casarse con.', 'A literary word; casarse con is more common.'),
  lx('un', 'один / неопределённый артикль', 'a / one, masculine', 'Мужская форма перед calé, niño, payo.', 'Masculine form before calé, niño and payo.'),
  lx('calé', 'ромский мужчина; представитель кале', 'Romani man; a Calé person', 'Слово из культурного контекста испанских ромов; здесь «ромский муж».', 'A cultural term connected with Spanish Roma; here, “a Romani husband”.'),
  lx('tendrás', 'у тебя будет', 'you will have', 'Будущее tener для tú.', 'The tú future form of tener.'),
  lx('tu', 'твой / твоя', 'your', 'Без ударения — притяжательное слово.', 'Without an accent, it is possessive.'),
  lx('hombre', 'мужчина / муж', 'man / husband', 'По контексту обещанный партнёр.', 'The promised partner in context.'),
  lx('piel', 'кожа / цвет кожи', 'skin / complexion', 'Piel morena = смуглая кожа.', 'Piel morena means brown/dark complexion.'),
  lx('morena', 'смуглая / тёмная', 'brown-skinned / dark', 'Женская форма, согласована с piel.', 'Feminine form agreeing with piel.'),
  lx('desde', 'из / с', 'from / since', 'Desde el cielo = с неба.', 'Desde el cielo means from the sky.'),
  lx('cielo', 'небо', 'sky / heaven', 'Мужское существительное: el cielo.', 'A masculine noun: el cielo.'),
  lx('habló', 'заговорила / сказала', 'spoke', 'Indefinido от hablar; подлежащее — luna llena.', 'Preterite of hablar; the subject is luna llena.'),
  lx('llena', 'полная', 'full', 'Luna llena = полная луна.', 'Luna llena means full moon.'),
  lx('pero', 'но', 'but', 'Вводит условие после обещания.', 'Introduces a condition after the promise.'),
  lx('cambio', 'обмен / взамен', 'exchange / return', 'A cambio = взамен.', 'A cambio means in return.'),
  lx('quiero', 'я хочу', 'I want', 'Форма querer для yo.', 'The yo form of querer.'),
  lx('hijo', 'сын / ребёнок мужского пола', 'son / male child', 'El hijo primero = первый ребёнок-сын.', 'El hijo primero means the first son/child.'),
  lx('primero', 'первый', 'first', 'Здесь стоит после существительного ради ритма.', 'Placed after the noun here for rhythm.'),
  lx('le', 'ему / ей', 'to him / to her', 'Косвенное местоимение: que le engendres a él.', 'Indirect object pronoun in que le engendres a él.'),
  lx('engendres', 'зачнёшь / родишь — subjuntivo', 'conceive / bear — subjunctive', 'Форма engendrar после требования quiero que.', 'A form of engendrar after the demand quiero que.'),
  lx('él', 'он / ему', 'he / him', 'С ударением — местоимение; el без ударения — артикль.', 'With an accent it is a pronoun; el without one is an article.'),
  lx('quien', 'тот, кто / кто', 'the one who / whoever', 'Без ударения в относительной конструкции.', 'No accent in a relative construction.'),
  lx('su', 'его / её / свой', 'his / her / their', 'Притяжательное слово; точный владелец определяется контекстом.', 'A possessive; context identifies the owner.'),
  lx('inmola', 'приносит в жертву', 'sacrifices / immolates', 'Форма inmolar; книжное и сильное слово.', 'A form of inmolar; a formal and forceful word.'),
  lx('para', 'для / чтобы', 'for / in order to', 'Para no estar sola = чтобы не быть одной.', 'Para no estar sola means in order not to be alone.'),
  lx('estar', 'быть / находиться', 'to be', 'О временном состоянии: estar sola.', 'Used for a state: estar sola.'),
  lx('sola', 'одна', 'alone', 'Женская форма, относится к матери/луне по контексту.', 'Feminine form referring to the mother/moon in context.'),
  lx('poco', 'мало', 'little / not much', 'Poco le iba a querer = он/она мало бы любил(а) его.', 'Poco le iba a querer means they would not love him much.'),
  lx('iba', 'шёл / собирался / стал бы', 'was going to / would', 'Ir a + infinitivo в imperfecto; здесь оценка возможной любви.', 'Ir a + infinitive in the imperfect; here it evaluates possible love.'),
  lx('querer', 'любить / хотеть; любовь', 'to love / want; affection', 'В припеве используется почти как существительное: «любовь/чувство».', 'In the chorus it is used almost as a noun: “love/affection”.'),
  lx('quieres', 'ты хочешь', 'you want', 'Форма querer для tú.', 'The tú form of querer.'),
  lx('ser', 'быть / стать', 'to be / become', 'Ser madre = быть матерью.', 'Ser madre means to be a mother.'),
  lx('madre', 'мать', 'mother', 'Женское существительное.', 'A feminine noun.'),
  lx('y', 'и / а', 'and / while', 'Соединяет слова и части предложения.', 'Joins words and clauses.'),
  lx('encuentras', 'ты находишь', 'you find', 'Форма encontrar для tú; o→ue.', 'The tú form of encontrar; o→ue.'),
  lx('te', 'тебя / тебе / себя', 'you / to you / yourself', 'Безударное местоимение перед глаголом.', 'An unstressed pronoun before a verb.'),
  lx('haga', 'сделает — subjuntivo', 'makes — subjunctive', 'Форма hacer после неопределённого querer que.', 'A form of hacer after the indefinite querer que.'),
  lx('mujer', 'женщина / жена', 'woman / wife', 'Hacer mujer — поэтическое «сделать женщиной/матерью».', 'Hacer mujer is the poetic “make into a woman/mother”.'),
  lx('dime', 'скажи мне', 'tell me', 'Команда decir для tú: di + me.', 'The tú command of decir: di + me.'),
  lx('de', 'из / от / родительный предлог', 'of / from', 'Связывает существительные: luna de plata.', 'Links nouns: luna de plata.'),
  lx('plata', 'серебро', 'silver', 'Luna de plata = серебряная луна.', 'Luna de plata means silver moon.'),
  lx('qué', 'что?', 'what?', 'С ударением в прямом вопросе.', 'Accented in a direct question.'),
  lx('pretendes', 'ты намереваешься', 'you intend', 'Pretender в испанском = намереваться, а не английское pretend.', 'Spanish pretender means intend, not English “pretend”.'),
  lx('hacer', 'делать / сделать', 'to do / make', 'Инфинитив после pretendes.', 'An infinitive after pretendes.'),
  lx('con', 'с', 'with', 'Предлог совместности или инструмента.', 'A preposition of company or instrument.'),
  lx('niño', 'ребёнок / мальчик', 'child / boy', 'Центральный образ песни.', 'The song’s central image.'),
  lx('ah-ah-ah-ah', 'вокализация', 'vocalization', 'Ритмический звук без буквального значения.', 'A rhythmic sound without literal meaning.'),
  lx('padre', 'отец', 'father', 'De padre canela = от смуглого отца.', 'De padre canela means of/from a cinnamon-skinned father.'),
  lx('canela', 'корица; коричневый оттенок', 'cinnamon; cinnamon-colored', 'Поэтическое описание цвета кожи отца.', 'A poetic description of the father’s complexion.'),
  lx('nació', 'родился', 'was born', 'Indefinido от nacer; ударение на ó.', 'Preterite of nacer; accent on ó.'),
  lx('blanco', 'белый', 'white', 'Согласован с niño.', 'Agrees with niño.'),
  lx('como', 'как / словно', 'like / as', 'Сравнение без ударения.', 'A comparison, without an accent.'),
  lx('lomo', 'спина / хребет', 'back / ridge', 'El lomo de un armiño = спина горностая.', 'El lomo de un armiño means an ermine’s back.'),
  lx('armiño', 'горностай', 'ermine', 'Животное с белым зимним мехом.', 'An animal known for white winter fur.'),
  lx('los', 'определённый артикль, мужской множественный', 'the, masculine plural', 'Согласуется с ojos и brazos.', 'Agrees with ojos and brazos.'),
  lx('ojos', 'глаза', 'eyes', 'Множественное число от ojo.', 'Plural of ojo.'),
  lx('grises', 'серые', 'gray', 'Множественное число, согласовано с ojos.', 'Plural agreeing with ojos.'),
  lx('en', 'в / вместо — в выражении', 'in / instead — in phrase', 'En vez de = вместо.', 'En vez de means instead of.'),
  lx('vez', 'раз; в выражении «вместо»', 'time; in “instead of”', 'En vez de — устойчивое выражение.', 'En vez de is a fixed expression.'),
  lx('aceituna', 'оливка', 'olive', 'Здесь метонимия оливкового/тёмного цвета глаз.', 'Here it evokes olive/dark eye color.'),
  lx('albino', 'альбинос / альбиносный', 'albino', 'Описывает необычно светлую внешность ребёнка.', 'Describes the child’s unusually pale appearance.'),
  lx('maldita', 'проклятая', 'damned / cursed', 'Сильное ругательное прилагательное.', 'A strong condemning adjective.'),
  lx('estampa', 'облик / вид', 'appearance / look', 'Maldita su estampa = «будь проклят его вид».', 'Maldita su estampa means “curse his appearance”.'),
  lx('este', 'этот', 'this', 'Указательное слово перед hijo.', 'A demonstrative before hijo.'),
  lx('es', 'есть / является', 'is', 'Форма ser для él/ella.', 'The él/ella form of ser.'),
  lx('payo', 'неромский человек', 'non-Romani person', 'Контекстное слово испанской ромской культуры; не универсальная бытовая метка.', 'A context-specific term in Spanish Romani culture, not a universal everyday label.'),
  lx('yo', 'я', 'I', 'Местоимение подчёркивает говорящего.', 'A pronoun emphasizing the speaker.'),
  lx('me', 'меня / мне / себя', 'me / myself', 'Часть выражения me lo callo.', 'Part of the expression me lo callo.'),
  lx('lo', 'это / его', 'it / him', 'Прямое объектное местоимение.', 'A direct object pronoun.'),
  lx('callo', 'я скрываю / молчу', 'I keep quiet / conceal', 'Callarse algo = промолчать о чём-то; me lo callo.', 'Callarse algo means to keep something quiet; me lo callo.'),
  lx('gitano', 'ромский мужчина', 'Romani man', 'Мужская форма; описывает героя баллады.', 'Masculine form describing the ballad’s character.'),
  lx('creerse', 'считать себя / поверить', 'to believe oneself / believe', 'Al creerse deshonrado = сочтя себя опозоренным.', 'Al creerse deshonrado means believing himself dishonored.'),
  lx('deshonrado', 'опозоренный', 'dishonored', 'Причастие/прилагательное от deshonrar.', 'A participle/adjective from deshonrar.'),
  lx('se', 'себя / возвратная частица', 'self / reflexive marker', 'В se fue и se hizo al monte входит в возвратную конструкцию.', 'Part of reflexive constructions in se fue and se hizo al monte.'),
  lx('fue', 'ушёл / отправился; был', 'went / left; was', 'Здесь от irse: se fue a su mujer.', 'Here it comes from irse: se fue a su mujer.'),
  lx('cuchillo', 'нож', 'knife', 'Cuchillo en mano = с ножом в руке.', 'Cuchillo en mano means knife in hand.'),
  lx('mano', 'рука', 'hand', 'Женское слово несмотря на -o: la mano.', 'Feminine despite ending in -o: la mano.'),
  lx('quién', 'кто?', 'who?', 'С ударением в вопросе: ¿De quién…?', 'Accented in a question: ¿De quién…?'),
  lx('has', 'ты — вспомогательный haber', 'you have — auxiliary', 'Has engañado = ты обманул(а).', 'Has engañado means you have deceived.'),
  lx('engañao', 'обманула — разговорное', 'deceived — colloquial', 'Песенное сокращение engañado с выпадением d; на письме стандартно engañado.', 'A sung colloquial reduction of engañado with dropped d; standard writing is engañado.'),
  lx('fijo', 'точно / наверняка', 'for sure / certainly', 'Разговорное наречное употребление.', 'An informal adverbial use.'),
  lx('muerte', 'смерть', 'death', 'Herir de muerte = смертельно ранить.', 'Herir de muerte means to mortally wound.'),
  lx('hirió', 'ранил', 'wounded', 'Indefinido от herir; e→i.', 'Preterite of herir; e→i.'),
  lx('luego', 'затем / потом', 'then / afterwards', 'Наречие последовательности.', 'An adverb of sequence.'),
  lx('hizo', 'сделал / ушёл — в выражении', 'did / made; went — in phrase', 'Hacerse al monte = скрыться в горах.', 'Hacerse al monte means to flee into the hills.'),
  lx('monte', 'гора / дикая местность', 'hill / wilderness', 'Hacerse al monte — уйти и скрыться вне поселений.', 'Hacerse al monte means to leave and hide in the wild.'),
  lx('brazos', 'руки / объятия', 'arms', 'En brazos = на руках.', 'En brazos means in one’s arms.'),
  lx('allí', 'там', 'there', 'Наречие места с ударением.', 'An adverb of place with an accent.'),
  lx('abandonó', 'оставил / бросил', 'abandoned / left', 'Indefinido от abandonar.', 'Preterite of abandonar.'),
  lx('las', 'определённый артикль, женский множественный', 'the, feminine plural', 'Согласуется с noches.', 'Agrees with noches.'),
  lx('noches', 'ночи', 'nights', 'Множественное число от noche.', 'Plural of noche.'),
  lx('haya', 'будет / имеется — subjuntivo', 'there is / may be — subjunctive', 'После будущего las noches que haya: речь о ещё неизвестных ночах.', 'Used for future unspecified nights in las noches que haya.'),
  lx('será', 'будет', 'will be', 'Будущее ser для él/ella.', 'The él/ella future of ser.'),
  lx('porque', 'потому что', 'because', 'Одно слово без ударения в ответе/объяснении.', 'One unaccented word when giving a reason.'),
  lx('esté', 'находится / будет — subjuntivo', 'is / may be — subjunctive', 'После porque в поэтическом объяснении состояния ребёнка.', 'A subjunctive form describing the child’s state in the poetic explanation.'),
  lx('buenas', 'хорошее настроение — в выражении', 'good mood — in phrase', 'Estar de buenas = быть в хорошем настроении.', 'Estar de buenas means to be in a good mood.'),
  lx('si', 'если', 'if', 'Без ударения вводит условие.', 'Without an accent, it introduces a condition.'),
  lx('llora', 'плачет', 'cries', 'Форма llorar для él/ella.', 'The él/ella form of llorar.'),
  lx('menguará', 'пойдёт на убыль', 'will wane', 'Будущее menguar; о фазе луны.', 'Future of menguar, describing the moon’s phase.'),
  lx('hacerle', 'сделать ему / для него', 'to make for him', 'Hacer + le: местоимение прикреплено к инфинитиву.', 'Hacer + le: the pronoun attaches to the infinitive.'),
  lx('cuna', 'колыбель', 'cradle', 'Луна превращается в колыбель в финальном образе.', 'The moon becomes a cradle in the final image.'),
])

const lyrics = [
  line(8.56, 'Tonto el que no entienda', 'Глуп тот, кто не поймёт.', 'A fool is the one who does not understand.', 'El que обобщает «тот, кто»; entienda стоит в subjuntivo.', 'El que generalizes “the one who”; entienda is subjunctive.'),
  line(12.61, 'Cuenta una leyenda', 'Одна легенда рассказывает…', 'A legend tells…', 'Инверсия делает начало похожим на традиционную балладу.', 'The inversion makes the opening sound like a traditional ballad.'),
  line(16.3, 'Que una hembra gitana', 'Что одна ромская женщина…', 'That a Romani woman…', 'Hembra здесь архаично-поэтическое; в обычной речи лучше mujer.', 'Hembra is archaic/poetic here; mujer is preferable in everyday speech.'),
  line(20.95, 'Conjuró a la luna hasta el amanecer', 'Заклинала луну до самого рассвета.', 'Invoked the moon until dawn.', 'Conjuró — завершённое действие; a отмечает адресата.', 'Conjuró is a completed action; a marks its target.'),
  line(24.65, 'Llorando pedía', 'Плача, она просила…', 'Crying, she begged…', 'Герундий и imperfecto рисуют продолжающуюся сцену.', 'The gerund and imperfect paint an ongoing scene.'),
  line(27.45, 'Al llegar el día', 'Когда наступил день…', 'When day came…', 'Al + infinitivo = «когда / при наступлении».', 'Al + infinitive means “when / upon”.'),
  line(30.0, 'Desposar un calé', 'Выйти замуж за ромского мужчину.', 'To marry a Romani man.', 'Desposar — книжное; calé — культурно специфическое слово.', 'Desposar is literary; calé is culturally specific.'),
  line(39.66, '"Tendrás a tu hombre, piel morena"', '«Ты получишь своего мужчину, смуглокожая».', '“You will have your man, brown-skinned woman.”', 'Прямая речь луны; piel morena используется как обращение.', 'The moon speaks directly; piel morena is used as an address.'),
  line(44.0, 'Desde el cielo habló la luna llena', 'С неба заговорила полная луна.', 'From the sky the full moon spoke.', 'Порядок слов выдвигает место действия вперёд.', 'The word order foregrounds the setting.'),
  line(47.3, '"Pero a cambio quiero', '«Но взамен я хочу…', '“But in return I want…', 'A cambio вводит цену сделки.', 'A cambio introduces the price of the bargain.'),
  line(50.2, 'El hijo primero que le engendres a él', 'Первого сына, которого ты зачнёшь от него.', 'The first son that you bear him.', 'Quiero que вызывает subjuntivo engendres; le и a él дублируют объект для акцента.', 'Quiero que triggers engendres; le and a él double the object for emphasis.'),
  line(55.0, 'Que quien su hijo inmola', 'Ведь тот, кто приносит в жертву своего ребёнка…', 'For whoever sacrifices their child…', 'Inmolar — сильное книжное слово.', 'Inmolar is a strong formal word.'),
  line(59.2, 'Para no estar sola', 'Чтобы не быть одной…', 'So as not to be alone…', 'Para + infinitivo выражает цель.', 'Para + infinitive expresses purpose.'),
  line(63.0, 'Poco le iba a querer"', 'Вряд ли сильно его любил бы».', 'Could hardly have loved him much.”', 'Ir a + infinitivo в imperfecto здесь передаёт оценку: любви было бы мало.', 'Ir a + infinitive in the imperfect gives an evaluation: there would be little love.'),
  line(69.33, 'Luna quieres ser madre', 'Луна, ты хочешь стать матерью.', 'Moon, you want to be a mother.', 'Обращение Luna стоит без отдельной частицы.', 'Luna is a direct address.'),
  line(73.93, 'Y no encuentras querer que te haga mujer', 'Но не находишь любви, которая сделала бы тебя женщиной.', 'And you cannot find a love that would make you a woman.', 'Querer здесь поэтически значит «любовь»; haga — subjuntivo после неопределённого источника любви.', 'Querer poetically means “love”; haga is subjunctive after an unspecified source of love.'),
  line(77.38, 'Dime, luna de plata', 'Скажи мне, серебряная луна.', 'Tell me, silver moon.', 'Dime = di + me, команда decir.', 'Dime is di + me, the command of decir.'),
  line(79.86, '¿Qué pretendes hacer con un niño de piel?', 'Что ты намерена делать с ребёнком из плоти?', 'What do you intend to do with a flesh-and-blood child?', 'Niño de piel — нарочно странный поэтический образ, не обычное современное выражение.', 'Niño de piel is intentionally strange poetic imagery, not a normal modern phrase.'),
  line(84.0, 'Ah-ah-ah-ah, ah-ah-ah-ah', 'Вокализация.', 'Vocalization.', 'Ритмический фрагмент без буквального значения.', 'A rhythmic passage without literal meaning.'),
  line(89.46, 'Hijo de la luna', 'Сын луны.', 'Son of the moon.', 'Название песни и итог рефрена.', 'The title and conclusion of the refrain.'),
  line(99.08, 'De padre canela nació un niño', 'У смуглого отца родился ребёнок.', 'A child was born to a cinnamon-skinned father.', 'Canela метафорически описывает цвет кожи.', 'Canela metaphorically describes complexion.'),
  line(103.1, 'Blanco como el lomo de un armiño', 'Белый, как спина горностая.', 'White as an ermine’s back.', 'Como вводит сравнение.', 'Como introduces a comparison.'),
  line(107.4, 'Con los ojos grises en vez de aceituna', 'С серыми глазами вместо оливковых.', 'With gray eyes instead of olive-colored ones.', 'Aceituna заменяет ожидаемый цвет глаз метонимией.', 'Aceituna stands for the expected eye color by metonymy.'),
  line(111.54, 'Niño albino de luna', 'Лунный ребёнок-альбинос.', 'Albino child of the moon.', 'Краткая именная строка без глагола.', 'A compact verbless nominal line.'),
  line(116.6, '"Maldita su estampa', '«Будь проклят его облик.', '“Curse his appearance.', 'Эмоциональная прямая речь отца.', 'The father’s emotional direct speech.'),
  line(120.0, 'Este hijo es de un payo', 'Этот ребёнок от неромского мужчины.', 'This child belongs to a non-Romani man.', 'Payo — контекстное культурное слово; строка показывает подозрение героя, а не факт.', 'Payo is culturally specific; the line shows the character’s suspicion, not a fact.'),
  line(124.1, 'Y yo no me lo callo"', 'И я об этом молчать не стану».', 'And I will not keep it quiet.”', 'Callarse algo: me + lo + callo.', 'Callarse algo uses me + lo + callo.'),
  line(129.89, 'Luna quieres ser madre', 'Луна, ты хочешь стать матерью.', 'Moon, you want to be a mother.', 'Начало второго припева.', 'The second refrain begins.'),
  line(134.1, 'Y no encuentras querer que te haga mujer', 'Но не находишь любви, которая сделала бы тебя женщиной.', 'And you cannot find a love that would make you a woman.', 'Поэтическое querer используется как имя любви.', 'Poetic querer functions as a name for love.'),
  line(139.0, 'Dime, luna de plata', 'Скажи мне, серебряная луна.', 'Tell me, silver moon.', 'Повтор команды dime.', 'The command dime repeats.'),
  line(143.2, '¿Qué pretendes hacer con un niño de piel?', 'Что ты намерена делать с ребёнком из плоти?', 'What do you intend to do with a flesh-and-blood child?', 'Pretender здесь значит «намереваться».', 'Pretender means “intend” here.'),
  line(148.5, 'Ah-ah-ah-ah, ah-ah-ah-ah', 'Вокализация.', 'Vocalization.', 'Мелодический рефрен.', 'A melodic refrain.'),
  line(154.5, 'Hijo de la luna', 'Сын луны.', 'Son of the moon.', 'Повтор названия.', 'The title repeats.'),
  line(159.64, 'Gitano al creerse deshonrado', 'Ромский мужчина, сочтя себя опозоренным…', 'The Romani man, believing himself dishonored…', 'Al + возвратный инфинитив = «когда/поскольку он счёл себя».', 'Al + reflexive infinitive means “upon/because he believed himself”.'),
  line(163.37, 'Se fue a su mujer, cuchillo en mano', 'Пошёл к своей жене с ножом в руке.', 'Went to his wife, knife in hand.', 'Cuchillo en mano — устойчивая безартиклевая конструкция.', 'Cuchillo en mano is a fixed article-less phrase.'),
  line(169.43, '"¿De quién es el hijo? Me has engañao\' fijo"', '«Чей это ребёнок? Ты точно меня обманула».', '“Whose child is this? You have deceived me for sure.”', 'Engañao\' передаёт разговорное выпадение d; стандартно engañado.', 'Engañao\' represents colloquial loss of d; standard form engañado.'),
  line(173.2, 'Y de muerte la hirió', 'И смертельно ранил её.', 'And mortally wounded her.', 'La — прямой объект; herir de muerte — смертельно ранить.', 'La is the direct object; herir de muerte means mortally wound.'),
  line(177.35, 'Luego se hizo al monte', 'Затем он скрылся в горах.', 'Then he fled into the hills.', 'Hacerse al monte — устойчивое выражение «уйти и скрыться».', 'Hacerse al monte is the fixed expression “flee into the wild”.'),
  line(183.0, 'Con el niño en brazos y allí le abandonó', 'С ребёнком на руках — и там он его оставил.', 'With the child in his arms, and there he abandoned him.', 'En brazos = на руках; le — распространённый испанский leísmo для лица мужского пола.', 'En brazos means in his arms; le is common Spanish leísmo for a male person.'),
  line(191.93, 'Luna quieres ser madre', 'Луна, ты хочешь стать матерью.', 'Moon, you want to be a mother.', 'Третий припев после трагической развязки.', 'The third refrain follows the tragedy.'),
  line(196.0, 'Y no encuentras querer que te haga mujer', 'Но не находишь любви, которая сделала бы тебя женщиной.', 'And you cannot find a love that would make you a woman.', 'Повтор теперь звучит как упрёк.', 'The repetition now sounds accusatory.'),
  line(200.2, 'Dime, luna de plata', 'Скажи мне, серебряная луна.', 'Tell me, silver moon.', 'Обращение к луне.', 'An address to the moon.'),
  line(204.2, '¿Qué pretendes hacer con un niño de piel?', 'Что ты намерена делать с ребёнком из плоти?', 'What do you intend to do with a flesh-and-blood child?', 'Вопрос возвращает внимание к судьбе ребёнка.', 'The question returns attention to the child’s fate.'),
  line(209.2, 'Ah-ah-ah-ah, ah-ah-ah-ah', 'Вокализация.', 'Vocalization.', 'Финальный полный рефрен.', 'The final full refrain.'),
  line(214.5, 'Hijo de la luna', 'Сын луны.', 'Son of the moon.', 'Название становится буквальным внутри легенды.', 'Within the legend, the title becomes literal.'),
  line(219.12, 'Y las noches que haya luna llena', 'И в ночи, когда будет полная луна…', 'And on nights when there is a full moon…', 'Будущие неопределённые ночи требуют haya.', 'Future unspecified nights take haya.'),
  line(223.1, 'Será porque el niño esté de buenas', 'Это будет потому, что ребёнок в хорошем настроении.', 'It will be because the child is in a good mood.', 'Estar de buenas — разговорное «быть в хорошем настроении».', 'Estar de buenas means to be in a good mood.'),
  line(227.5, 'Y si el niño llora', 'А если ребёнок плачет…', 'And if the child cries…', 'Si без ударения вводит условие.', 'Si without an accent introduces a condition.'),
  line(230.2, 'Menguará la luna para hacerle una cuna', 'Луна пойдёт на убыль, чтобы сделать ему колыбель.', 'The moon will wane to make him a cradle.', 'Будущее menguará; hacer + le → hacerle.', 'Future menguará; hacer + le becomes hacerle.'),
  line(234.2, 'Y si el niño llora', 'А если ребёнок плачет…', 'And if the child cries…', 'Строка повторяется для закольцованного финала.', 'The line repeats to create a circular ending.'),
  line(237.2, 'Menguará la luna para hacerle una cuna', 'Луна пойдёт на убыль, чтобы сделать ему колыбель.', 'The moon will wane to make him a cradle.', 'Фаза луны превращается в материнский жест.', 'The moon’s phase becomes a maternal gesture.'),
]

const cards = [
  ['el que', 'тот, кто', 'the one who', 'Tonto el que no entienda.'], ['contar una leyenda', 'рассказывать легенду', 'to tell a legend', 'Cuenta una leyenda.'],
  ['conjurar', 'заклинать / призывать', 'to conjure / invoke', 'Conjuró a la luna.'], ['hasta el amanecer', 'до рассвета', 'until dawn', 'Hasta el amanecer.'],
  ['llorando', 'плача', 'crying', 'Llorando pedía.'], ['al + infinitivo', 'когда / при действии', 'upon / when doing', 'Al llegar el día.'],
  ['desposar', 'вступить в брак', 'to wed', 'Desposar un calé.'], ['calé', 'ромский мужчина', 'Romani man', 'Un calé.'],
  ['a cambio', 'взамен', 'in return', 'Pero a cambio quiero…'], ['engendrar', 'зачать / породить', 'to conceive / beget', 'Que le engendres a él.'],
  ['inmolar', 'принести в жертву', 'to sacrifice', 'Quien su hijo inmola.'], ['estar sola', 'быть одной', 'to be alone', 'Para no estar sola.'],
  ['luna llena', 'полная луна', 'full moon', 'La luna llena.'], ['dime', 'скажи мне', 'tell me', 'Dime, luna de plata.'],
  ['pretender + infinitivo', 'намереваться сделать', 'to intend to do', '¿Qué pretendes hacer?'], ['hijo de la luna', 'сын луны', 'son of the moon', 'Hijo de la luna.'],
  ['en vez de', 'вместо', 'instead of', 'En vez de aceituna.'], ['el armiño', 'горностай', 'ermine', 'El lomo de un armiño.'],
  ['la estampa', 'облик / вид', 'appearance', 'Maldita su estampa.'], ['payo', 'неромский человек', 'non-Romani person', 'Este hijo es de un payo.'],
  ['callarse algo', 'умолчать о чём-то', 'to keep something quiet', 'Yo no me lo callo.'], ['al creerse', 'сочтя себя', 'believing oneself', 'Al creerse deshonrado.'],
  ['cuchillo en mano', 'с ножом в руке', 'knife in hand', 'Cuchillo en mano.'], ['engañao\' → engañado', 'обманул — разговорная форма', 'deceived — colloquial form', 'Me has engañao\' fijo.'],
  ['herir de muerte', 'смертельно ранить', 'to mortally wound', 'De muerte la hirió.'], ['hacerse al monte', 'скрыться в горах', 'to flee into the hills', 'Se hizo al monte.'],
  ['en brazos', 'на руках', 'in one’s arms', 'Con el niño en brazos.'], ['abandonar', 'оставить / бросить', 'to abandon', 'Allí le abandonó.'],
  ['estar de buenas', 'быть в хорошем настроении', 'to be in a good mood', 'El niño esté de buenas.'], ['menguar', 'идти на убыль', 'to wane', 'Menguará la luna.'],
  ['hacerle una cuna', 'сделать ему колыбель', 'to make him a cradle', 'Para hacerle una cuna.'], ['la luna de plata', 'серебряная луна', 'silver moon', 'Dime, luna de plata.'],
].map(([es, ru, en, example]) => ({ es, en: l(ru, en), example }))

export const hijoDeLaLunaSongLesson = {
  id: 'hijo-de-la-luna-song', bilingual: true, featured: true, title: 'Hijo de la luna',
  eyebrow: l('Песня · Mecano · A1–A2', 'Song · Mecano · A1–A2'),
  description: l('Пройди мрачную испанскую балладу строка за строкой: видео, полный перевод, каждое слово, культурный контекст и грамматика.', 'Explore this dark Spanish ballad line by line through video, full translation, every word, cultural context and grammar.'),
  accent: 'blue', minutes: 64, icon: 'Music2',
  guideKicker: l('РАЗБОР ПЕСНИ · ЛЕГЕНДА И ЯЗЫК', 'SONG BREAKDOWN · LEGEND AND LANGUAGE'),
  modeCopy: {
    song: { label: l('Видео + синхронный текст', 'Video + synced lyrics'), description: l('Следи за 51 строкой, нажимай для перемотки и разбирай каждое слово.', 'Follow all 51 lines, click to seek and inspect every word.') },
    guide: { label: l('Сюжет, культура и грамматика', 'Story, culture and grammar'), description: l('Разбери легенду, сложные слова, времена, местоимения и subjuntivo.', 'Understand the legend, sensitive terms, tenses, pronouns and subjunctive.') },
    cards: { label: l('Главные карточки', 'Essential cards'), description: l('Запомни 32 самые полезные конструкции и образные слова.', 'Learn the 32 most useful patterns and vivid words.') },
    match: { label: l('Сопоставление 4×4', '4×4 Match'), description: l('Соедини выражения баллады с точным смыслом.', 'Match the ballad expressions with their precise meanings.') },
    quiz: { label: l('Проверка смысла и форм', 'Meaning and form check'), description: l('Проверь сюжет, лексику, времена и важные различия.', 'Check the story, vocabulary, tenses and important distinctions.') },
    builder: { label: l('Собери строки', 'Build the lines'), description: l('Восстанови ключевые предложения из перемешанных слов.', 'Rebuild key lines from shuffled words.') },
    compose: { label: l('Напиши по смыслу', 'Write from meaning'), description: l('Воспроизведи важные конструкции без банка слов.', 'Recall important patterns without a word bank.') },
    vocab: { label: l('Все слова отдельно', 'Every word separately'), description: l('Пройди весь словарь песни в обе стороны.', 'Review the song’s complete vocabulary in both directions.') },
  },
  ui: {
    backToPlayground:l('Назад к урокам','Back to playground'),mastery:l('освоено','mastery'),modes:l('этапов','stages'),chooseMode:l('ЭТАПЫ УРОКА','LESSON STAGES'),practiceQuestion:l('Сначала история, затем точный язык','Start with the story, then master the language'),completed:l('Пройдено','Completed'),done:l('Готово','Done'),start:l('Начать','Start'),minutesShort:l('мин','min'),wordsLabel:l('главных карточки','essential cards'),phraseOfDay:l('Интерактивная песня','Interactive song'),
    back:l('Назад','Back'),exit:l('Выйти','Exit'),savedPhrases:l('Сохранённые фразы','Saved phrases'),cardTitle:l('Слова песни','Song Words'),spanish:l('Испанский','Spanish'),targetLanguage:l('Русский','English'),meaningLabel:l('ЗНАЧЕНИЕ','MEANING'),tapToSpanish:l('Нажми, чтобы вернуться','Tap to return to Spanish'),playPronunciation:l('Прослушать произношение','Play Spanish pronunciation'),listenTitle:l('Слушай и связывай с сюжетом','Listen and connect it to the story'),listenBody:l('Повтори выражение и найди момент, где оно меняет историю.','Repeat the expression and find where it changes the story.'),gotIt:l('Запомнил','Got it'),finish:l('Завершить','Finish'),previous:l('Назад','Previous'),startPractising:l('Перейти к практике','Start practising'),understand:l('Понятно','I understand'),
    matchKicker:l('СЛОВА ПЕСНИ · СОПОСТАВЛЕНИЕ','SONG WORDS · MATCH'),connectPairs:l('Соедини пары','Connect the pairs'),round:l('Раунд','Round'),of:l('из','of'),matched:l('готово','matched'),matchCorrect:l('¡Sí! Точный смысл.','¡Sí! Exact meaning.'),matchWrong:l('Не эта пара — попробуй снова.','Not this pair—try again.'),finishMatching:l('Завершить','Finish matching'),nextFour:l('Следующие четыре','Next four'),
    quizKicker:l('БАЛЛАДА · ФОРМА И СМЫСЛ','BALLAD · FORM AND MEANING'),hardOne:l('Хочешь сохранить?','Save this one?'),correctTitle:'¡Muy bien!',wrongTitle:l('Пока не совсем.','Not quite yet.'),naturalAnswer:l('Это точный вариант.','That is the precise answer.'),answerIs:l('Ответ:','The answer is'),sayIt:l('Произнеси строку.','Say the line.'),next:l('Дальше','Next'),sentenceKicker:l('ВОССТАНОВИ СТРОКУ','REBUILD THE LINE'),buildPlaceholder:l('Собери фразу здесь…','Build the phrase here…'),perfect:'¡Perfecto!',wordOrder:l('Проверь порядок, форму и местоимение.','Check the order, form and pronoun.'),checkSentence:l('Проверить','Check phrase'),
    composerKicker:l('ВСПОМНИ ФРАЗУ · БЕЗ БАНКА СЛОВ','RECALL THE PHRASE · NO WORD BANK'),yourPhrase:l('Твоя фраза','Your phrase'),composePlaceholder:l('Напиши по-испански…','Write in Spanish…'),hideHint:l('Скрыть опору','Hide hint'),showHint:l('Нужна опора?','Need a hint?'),words:l('слов','words'),checkPhrase:l('Проверить фразу','Check phrase'),finishLesson:l('Завершить этап','Finish stage'),nextPhrase:l('Следующая фраза','Next phrase'),accentTitle:l('Смысл верный — поправь ударение.','Meaning is right—fix the accent.'),writeIt:l('Напиши так:','Write it like this:'),verbFormTitle:l('Нужна форма из песни.','Use the song form.'),workFormMessage:l('Сравни форму глагола со строкой.','Compare the verb form with the line.'),infinitiveTitle:l('Проверь инфинитив.','Check the infinitive.'),returnFormMessage:l('После конструкции нужен инфинитив.','The pattern needs an infinitive.'),noPositionTitle:l('Проверь место no.','Check the position of no.'),naturalVariant:l('Естественная версия:','A natural version:'),notYetTitle:l('Пока не совпало.','Not quite yet.'),compareVariant:l('Сравни со строкой:','Compare with the line:'),
  },
  song: {
    videoId:'0fStdU-CBTI',title:'Mecano — HIJO DE LA LUNA',kicker:l('ИНТЕРАКТИВНОЕ АУДИРОВАНИЕ','INTERACTIVE LISTENING'),
    instructions:l('Запусти видео: строка подсветится по времени. Нажми строку для перемотки; наведи на слово или нажми его, чтобы увидеть перевод, форму и контекст.','Play the video and the current line will highlight. Click a line to seek; hover over or tap a word for its meaning, form and context.'),
    nowLabel:l('СЕЙЧАС / ВЫБРАННАЯ СТРОКА','NOW / SELECTED LINE'),wordLabel:l('СЛОВО ПОД КУРСОРОМ','WORD UNDER THE CURSOR'),transcriptLabel:l('ПОЛНЫЙ ТЕКСТ','FULL LYRICS'),linesLabel:l('строк','lines'),transcriptHint:l('Нажми строку → перемотка','Click a line → seek'),
    studyTitle:l('Как проходить песню','How to study this song'),studyNote:l('Сначала прослушай сюжет целиком. Затем возвращайся к строфам и разбирай слова. В третий проход следи только за испанским и перескажи легенду своими простыми фразами.','First listen to the whole story. Then revisit each verse and inspect the words. On the third pass, follow only the Spanish and retell the legend in simple sentences.'),finishLabel:l('Я разобрал песню','I studied the song'),fallbackWord:w('слово в контексте строки','a word in this line','Смотри объяснение всей строки рядом.','Use the explanation of the full line beside it.'),lines:lyrics,lexicon,
  },
  guide: [
    {title:l('Сюжет: сделка с луной','The story: a bargain with the moon'),body:l('Женщина просит луну помочь ей выйти замуж. Луна требует первого ребёнка. Рождается необычно светлый мальчик; муж обвиняет жену в измене, убивает её и оставляет ребёнка. Луна забирает ребёнка, а её фазы становятся его настроением и колыбелью. Это мрачная фантастическая баллада, а не описание реальных ромских традиций.','A woman asks the moon to help her marry. The moon demands her first child. An unusually pale boy is born; the husband accuses his wife of betrayal, kills her and abandons the child. The moon takes him, and its phases become his moods and cradle. This is a dark fantasy ballad, not a description of real Romani traditions.'),rule:'petición → trato → tragedia → mito',examples:[['Pero a cambio quiero el hijo primero.',l('Но взамен я хочу первого ребёнка.','But in return I want the first child.')],['Menguará la luna para hacerle una cuna.',l('Луна пойдёт на убыль, чтобы сделать ему колыбель.','The moon will wane to make him a cradle.')]]},
    {title:l('Культурные слова без стереотипов','Cultural terms without stereotypes'),body:l('Gitano/gitana обозначают ромскую идентичность в Испании; calé связано с испанской ромской общиной, payo означает неромского человека в этом культурном контексте. Сама песня использует старые драматические тропы ревности и «чести». Их нужно понимать как сюжет персонажей, а не переносить на реальных людей. Hembra о женщине сегодня обычно звучит обезличивающе.','Gitano/gitana name Romani identity in Spain; calé is linked to the Spanish Romani community, and payo means a non-Romani person in this cultural context. The song uses old dramatic tropes of jealousy and “honor”. Treat them as the characters’ story, not as claims about real people. Hembra for a woman usually sounds objectifying today.'),rule:'gitano/a · calé · payo · hembra ≠ mujer',examples:[['Una mujer gitana.',l('Нейтральнее в обычной современной речи.','More neutral in everyday modern speech.')],['Este hijo es de un payo.',l('Подозрение персонажа внутри баллады.','A character’s suspicion inside the ballad.')]]},
    {title:l('Al + infinitivo: когда что-то происходит','Al + infinitive: when something happens'),body:l('Al llegar el día означает «когда наступил день». Al creerse deshonrado — «сочтя себя опозоренным». Это компактный способ связать главное событие с моментом или причиной. Возвратное местоимение остаётся прикреплённым к инфинитиву: creer + se.','Al llegar el día means “when day came”. Al creerse deshonrado means “believing himself dishonored”. It compactly connects the main event with a time or cause. The reflexive pronoun stays attached to the infinitive: creer + se.'),rule:'al + infinitivo · al + infinitivo + se',examples:[['Al llegar el día…',l('Когда наступил день…','When day came…')],['Al creerse deshonrado…',l('Сочтя себя опозоренным…','Believing himself dishonored…')]]},
    {title:l('Местоимения: dime, hacerle, me lo callo','Pronouns: dime, hacerle, me lo callo'),body:l('В утвердительной команде и инфинитиве местоимение прикрепляется: di + me → dime, hacer + le → hacerle. Перед личной формой оно стоит отдельно. В me lo callo порядок фиксирован: сначала косвенное/возвратное me, затем прямое lo, затем глагол. Le abandonó — распространённый в Испании leísmo, когда le заменяет мужское лицо.','With affirmative commands and infinitives, the pronoun attaches: di + me → dime, hacer + le → hacerle. It stands separately before a conjugated form. In me lo callo, the order is fixed: me, then direct object lo, then the verb. Le abandonó is common Spanish leísmo, where le refers to a male person.'),rule:'di + me · hacer + le · me + lo + callo',examples:[['Dime, luna de plata.',l('Скажи мне, серебряная луна.','Tell me, silver moon.')],['Yo no me lo callo.',l('Я об этом не промолчу.','I will not keep it quiet.')],['Para hacerle una cuna.',l('Чтобы сделать ему колыбель.','To make him a cradle.')]]},
    {title:l('Прошедшее и рассказ','Past tenses in the story'),body:l('Indefinido двигает сюжет: conjuró, habló, nació, hirió, abandonó. Imperfecto даёт фон или длительность: pedía, iba a querer. Такое чередование — основа испанского повествования: фон в imperfecto, новое событие в indefinido.','The preterite moves the story forward: conjuró, habló, nació, hirió, abandonó. The imperfect supplies background or duration: pedía, iba a querer. This contrast is central to Spanish storytelling: background in imperfect, new events in preterite.'),rule:'imperfecto = фон · indefinido = событие',examples:[['Llorando pedía…',l('Она продолжала просить.','She kept pleading.')],['Desde el cielo habló la luna.',l('Луна заговорила — новое событие.','The moon spoke—a new event.')],['Y de muerte la hirió.',l('Он смертельно ранил её.','He mortally wounded her.')]]},
    {title:l('Subjuntivo и будущая неизвестность','Subjunctive and future uncertainty'),body:l('Entienda, engendres, haga, haya и esté — формы subjuntivo. Причины разные: обобщение «кто бы ни понял», требование quiero que, неизвестная любовь, будущие неопределённые ночи и воображаемое объяснение состояния ребёнка. Для начала запоминай эти связки целиком.','Entienda, engendres, haga, haya and esté are subjunctive forms. The triggers differ: a general “whoever understands”, a demand with quiero que, an unknown love, future unspecified nights and an imagined explanation of the child’s mood. For now, memorize the full chunks.'),rule:'el que entienda · quiero que engendres · que haya · esté de buenas',examples:[['El que no entienda.',l('Тот, кто не поймёт.','The one who does not understand.')],['El hijo que le engendres.',l('Ребёнок, которого ты зачнёшь.','The child that you bear him.')],['Las noches que haya luna llena.',l('Ночи, когда будет полная луна.','Nights when there is a full moon.')]]},
  ],
  words:cards,
  vocabulary:Object.entries(lexicon).map(([es,entry])=>({es,en:entry.meaning,example:entry.note})),
  quiz: [
    {prompt:l('Что означает «al llegar el día»?','What does “al llegar el día” mean?'),options:[l('когда наступил день','when day came'),l('до наступления дня','before day came'),l('в течение дня','during the day')],answer:l('когда наступил день','when day came'),explanation:l('Al + infinitivo передаёт момент действия.','Al + infinitive expresses when something happens.')},
    {prompt:l('Какое слово в обычной речи нейтральнее вместо hembra о женщине?','Which everyday word is more neutral than hembra for a woman?'),options:['mujer','madre','hembro'],answer:'mujer',explanation:l('Hembra здесь относится к архаическому балладному стилю.','Hembra belongs to the archaic ballad style here.')},
    {prompt:l('Что означает calé в контексте песни?','What does calé mean in the song?'),options:[l('ромский мужчина','Romani man'),l('лунный свет','moonlight'),l('нож','knife')],answer:l('ромский мужчина','Romani man'),explanation:l('Это культурно специфическое слово.','It is a culturally specific term.')},
    {prompt:'a + cambio = ___',options:['a cambio','al cambio','de cambio'],answer:'a cambio',explanation:l('A cambio = взамен.','A cambio means in return.')},
    {prompt:'Quiero que le ___ a él.',options:['engendres','engendras','engendrar'],answer:'engendres',explanation:l('Требование quiero que вызывает subjuntivo.','The demand quiero que triggers the subjunctive.')},
    {prompt:l('Что означает inmolar?','What does inmolar mean?'),options:[l('принести в жертву','to sacrifice'),l('усыновить','to adopt'),l('спрятать','to hide')],answer:l('принести в жертву','to sacrifice'),explanation:l('Это сильное книжное слово.','It is a strong formal word.')},
    {prompt:l('Как построено dime?','How is dime formed?'),options:['di + me','dice + mí','dar + me'],answer:'di + me',explanation:l('Di — команда decir для tú; me прикрепляется.','Di is the tú command of decir; me attaches.')},
    {prompt:l('Pretender в этой строке означает…','Pretender in this line means…'),options:[l('намереваться','to intend'),l('притворяться','to pretend'),l('защищать','to defend')],answer:l('намереваться','to intend'),explanation:l('Это ложный друг английского pretend.','It is a false friend of English “pretend”.')},
    {prompt:'En ___ de aceituna.',options:['vez','ves','ve'],answer:'vez',explanation:l('En vez de = вместо.','En vez de means instead of.')},
    {prompt:l('Что такое armiño?','What is an armiño?'),options:[l('горностай','ermine'),l('дракон','dragon'),l('волк','wolf')],answer:l('горностай','ermine'),explanation:l('Его белый мех создаёт сравнение с ребёнком.','Its white fur creates the comparison with the child.')},
    {prompt:l('Payo в этом культурном контексте — это…','Payo in this cultural context means…'),options:[l('неромский человек','non-Romani person'),l('отец','father'),l('ребёнок','child')],answer:l('неромский человек','non-Romani person'),explanation:l('Термин объясняется только в контексте, без обобщений о людях.','The term is explained contextually, without generalizing about people.')},
    {prompt:'Yo no me lo ___.',options:['callo','callo a','cayo'],answer:'callo',explanation:l('Callarse algo: me + lo + callo.','Callarse algo uses me + lo + callo.')},
    {prompt:l('Стандартное написание engañao\' — это…','The standard spelling behind engañao\' is…'),options:['engañado','engañao','engañando'],answer:'engañado',explanation:l('В песне передано разговорное выпадение d.','The song represents colloquial loss of d.')},
    {prompt:l('Что означает «hacerse al monte»?','What does “hacerse al monte” mean?'),options:[l('скрыться в горах','to flee into the hills'),l('подняться на вершину','to climb to the summit'),l('построить дом','to build a house')],answer:l('скрыться в горах','to flee into the hills'),explanation:l('Это устойчивое выражение.','It is a fixed expression.')},
    {prompt:l('«En brazos» означает…','“En brazos” means…'),options:[l('на руках','in one’s arms'),l('за спиной','behind one’s back'),l('без оружия','unarmed')],answer:l('на руках','in one’s arms'),explanation:l('Con el niño en brazos = с ребёнком на руках.','Con el niño en brazos means with the child in his arms.')},
    {prompt:l('Почему в «las noches que haya» стоит haya?','Why does “las noches que haya” use haya?'),options:[l('ночи ещё не определены и относятся к будущему','the nights are future and unspecified'),l('это приказ','it is a command'),l('это прошлое','it is past')],answer:l('ночи ещё не определены и относятся к будущему','the nights are future and unspecified'),explanation:l('Неопределённое будущее вызывает subjuntivo.','Unspecified future reference triggers the subjunctive.')},
    {prompt:l('Что означает «estar de buenas»?','What does “estar de buenas” mean?'),options:[l('быть в хорошем настроении','to be in a good mood'),l('быть добрым человеком','to be a good person'),l('хорошо выглядеть','to look good')],answer:l('быть в хорошем настроении','to be in a good mood'),explanation:l('Это разговорное устойчивое выражение.','It is an informal fixed expression.')},
    {prompt:l('Какое время у menguará?','What tense is menguará?'),options:[l('будущее','future'),l('прошедшее','past'),l('настоящее','present')],answer:l('будущее','future'),explanation:l('Окончание -á обозначает третье лицо будущего.','The -á ending marks third-person future.')},
    {prompt:l('Какие формы двигают сюжет вперёд?','Which forms move the story forward?'),options:['conjuró · habló · nació · hirió','pedía · iba','haya · esté'],answer:'conjuró · habló · nació · hirió',explanation:l('Это завершённые события в indefinido.','These are completed events in the preterite.')},
    {prompt:l('Что символизирует лунная колыбель в финале?','What does the moon-cradle symbolize at the end?'),options:[l('луна становится матерью ребёнку','the moon becomes the child’s mother'),l('ребёнок возвращается отцу','the child returns to his father'),l('легенда была сном','the legend was a dream')],answer:l('луна становится матерью ребёнку','the moon becomes the child’s mother'),explanation:l('Фазы луны объясняются настроением и заботой о ребёнке.','The moon’s phases are explained through the child’s mood and care.')},
  ],
  builder: [
    {translation:l('Глуп тот, кто не поймёт.','A fool is the one who does not understand.'),answer:['Tonto','el','que','no','entienda.']},
    {translation:l('Одна легенда рассказывает.','A legend tells.'),answer:['Cuenta','una','leyenda.']},
    {translation:l('Она заклинала луну до рассвета.','She invoked the moon until dawn.'),answer:['Conjuró','a','la','luna','hasta','el','amanecer.']},
    {translation:l('Плача, она просила.','Crying, she begged.'),answer:['Llorando','pedía.']},
    {translation:l('Когда наступил день.','When day came.'),answer:['Al','llegar','el','día.']},
    {translation:l('Но взамен я хочу.','But in return I want.'),answer:['Pero','a','cambio','quiero.']},
    {translation:l('Чтобы не быть одной.','So as not to be alone.'),answer:['Para','no','estar','sola.']},
    {translation:l('Луна, ты хочешь быть матерью.','Moon, you want to be a mother.'),answer:['Luna,','quieres','ser','madre.']},
    {translation:l('Скажи мне, серебряная луна.','Tell me, silver moon.'),answer:['Dime,','luna','de','plata.']},
    {translation:l('Что ты намерена сделать?','What do you intend to do?'),answer:['¿Qué','pretendes','hacer?']},
    {translation:l('Белый, как спина горностая.','White as an ermine’s back.'),answer:['Blanco','como','el','lomo','de','un','armiño.']},
    {translation:l('С серыми глазами вместо оливковых.','With gray eyes instead of olive-colored ones.'),answer:['Con','los','ojos','grises','en','vez','de','aceituna.']},
    {translation:l('И я об этом не промолчу.','And I will not keep it quiet.'),answer:['Y','yo','no','me','lo','callo.']},
    {translation:l('С ножом в руке.','Knife in hand.'),answer:['Cuchillo','en','mano.']},
    {translation:l('Он смертельно ранил её.','He mortally wounded her.'),answer:['De','muerte','la','hirió.']},
    {translation:l('Затем он скрылся в горах.','Then he fled into the hills.'),answer:['Luego','se','hizo','al','monte.']},
    {translation:l('Если ребёнок плачет.','If the child cries.'),answer:['Si','el','niño','llora.']},
    {translation:l('Луна пойдёт на убыль, чтобы сделать ему колыбель.','The moon will wane to make him a cradle.'),answer:['Menguará','la','luna','para','hacerle','una','cuna.']},
  ],
  compose: [
    {prompt:l('Напиши: «Когда наступил день».','Write: “When day came.”'),hint:'al + llegar · el día',accepted:['Al llegar el día.'],answer:'Al llegar el día.',explanation:l('Al + infinitivo выражает момент действия.','Al + infinitive expresses when something happens.')},
    {prompt:l('Напиши: «До рассвета».','Write: “Until dawn.”'),hint:'hasta · el amanecer',accepted:['Hasta el amanecer.'],answer:'Hasta el amanecer.',explanation:l('Amanecer здесь существительное.','Amanecer is a noun here.')},
    {prompt:l('Напиши: «Но взамен я хочу».','Write: “But in return I want.”'),hint:'pero · a cambio · quiero',accepted:['Pero a cambio quiero.'],answer:'Pero a cambio quiero.',explanation:l('A cambio — устойчивое «взамен».','A cambio is the fixed phrase “in return”.')},
    {prompt:l('Напиши: «Скажи мне, серебряная луна».','Write: “Tell me, silver moon.”'),hint:'di + me · luna de plata',accepted:['Dime, luna de plata.','Dime luna de plata.'],answer:'Dime, luna de plata.',explanation:l('Dime — команда с прикреплённым me.','Dime is a command with attached me.')},
    {prompt:l('Напиши: «Что ты намерена сделать?»','Write: “What do you intend to do?”'),hint:'¿qué · pretendes · hacer?',accepted:['¿Qué pretendes hacer?','Qué pretendes hacer?'],answer:'¿Qué pretendes hacer?',explanation:l('Qué имеет ударение; после pretendes стоит инфинитив.','Qué takes an accent; pretendes is followed by an infinitive.')},
    {prompt:l('Напиши: «Я об этом не промолчу».','Write: “I will not keep it quiet.”'),hint:'yo · no · me + lo · callo',accepted:['Yo no me lo callo.','No me lo callo.'],answer:'Yo no me lo callo.',explanation:l('Порядок местоимений: me + lo перед callo.','Pronoun order is me + lo before callo.')},
    {prompt:l('Напиши: «Если ребёнок плачет».','Write: “If the child cries.”'),hint:'si · el niño · llora',accepted:['Si el niño llora.'],answer:'Si el niño llora.',explanation:l('У условного si нет ударения.','Conditional si has no accent.')},
    {prompt:l('Напиши: «Луна пойдёт на убыль».','Write: “The moon will wane.”'),hint:'menguar → menguará · la luna',accepted:['Menguará la luna.','La luna menguará.'],answer:'Menguará la luna.',explanation:l('Menguará — третье лицо будущего.','Menguará is third-person future.')},
  ],
}
