const l = (ru, en) => ({ ru, en })

export const joseActionsPositionsLesson = {
  id: 'jose-actions-time-positions',
  bilingual: true,
  title: l('Действия, причины и пространство', 'Actions, reasons and space'),
  eyebrow: l('Третий урок с Хосе · A0–A1', 'Third lesson with José · A0–A1'),
  description: l('Ищи и находи, объясняй причины, говори о времени и точно описывай расположение предметов дома.', 'Search and find, explain reasons, talk about time and describe exactly where objects are at home.'),
  accent: 'coral', minutes: 46, icon: 'MessagesSquare',
  guideKicker: l('УРОК С ХОСЕ · ДЕЙСТВИЯ И ПОЗИЦИИ', 'LESSON WITH JOSÉ · ACTIONS AND POSITIONS'),
  modeCopy: {
    guide: { label: l('Понятная карта урока', 'Clear lesson map'), description: l('Разбери действия, время, porque/por qué и все позиции.', 'Understand actions, time, porque/por qué and every position.') },
    cards: { label: l('Карточки слов и позиций', 'Words and positions deck'), description: l('Запомни значения и примеры в обе стороны.', 'Remember meanings and examples in both directions.') },
    match: { label: l('Сопоставление 4×4', '4×4 Match'), description: l('Соедини двадцать новых единиц с их значениями.', 'Match twenty new items with their meanings.') },
    quiz: { label: l('Проверка различий', 'Difference check'), description: l('Buscar или encontrar, porque или por qué, traes или trae?', 'Buscar or encontrar, porque or por qué, traes or trae?') },
    builder: { label: l('Конструктор предложений', 'Sentence builder'), description: l('Собери ключевые примеры занятия и позиции.', 'Build the key lesson examples and position sentences.') },
    compose: { label: l('Напиши по смыслу', 'Write from meaning'), description: l('Создай предложение без банка слов по заданному смыслу.', 'Create a sentence without a word bank from a target meaning.') },
    create: { label: l('Домашнее задание: 2 фразы', 'Homework: 2 sentences'), description: l('Опиши дом двумя предложениями, используя четыре разные позиции.', 'Describe your home in two sentences using four different positions.') },
  },
  ui: {
    backToPlayground: l('Назад к урокам', 'Back to playground'), mastery: l('освоено', 'mastery'), modes: l('режимов', 'modes'), chooseMode: l('ЭТАПЫ УРОКА', 'LESSON STAGES'), practiceQuestion: l('От новых слов к описанию своего дома', 'From new words to describing your home'), completed: l('Пройдено', 'Completed'), done: l('Готово', 'Done'), start: l('Начать', 'Start'), minutesShort: l('мин', 'min'), wordsLabel: l('слов', 'words'), phraseOfDay: l('Урок дня', 'Lesson of the day'),
    back: l('Назад', 'Back'), exit: l('Выйти', 'Exit'), savedPhrases: l('Сохранённые фразы', 'Saved phrases'), cardTitle: l('Слово и контекст', 'Word & Context'), spanish: l('Испанский', 'Spanish'), targetLanguage: l('Русский', 'English'), meaningLabel: l('ЗНАЧЕНИЕ', 'MEANING'), tapToSpanish: l('Нажми, чтобы увидеть испанский', 'Tap to see Spanish'), playPronunciation: l('Прослушать произношение', 'Play Spanish pronunciation'), listenTitle: l('Слушай и повторяй вслух', 'Listen and repeat aloud'), listenBody: l('Послушай слово и сразу повтори пример целиком.', 'Listen to the word and immediately repeat the full example.'), gotIt: l('Запомнил', 'Got it'), finish: l('Завершить', 'Finish'),
    previous: l('Назад', 'Previous'), startPractising: l('Перейти к практике', 'Start practising'), understand: l('Понятно', 'I understand'),
    matchKicker: l('СОПОСТАВЛЕНИЕ 4 × 4', '4 × 4 MATCH'), connectPairs: l('Соедини пары', 'Connect the pairs'), round: l('Раунд', 'Round'), of: l('из', 'of'), matched: l('готово', 'matched'), matchCorrect: l('¡Sí! Пара совпала.', '¡Sí! That pair matches.'), matchWrong: l('Не эта пара — попробуй ещё.', 'Not this pair — try again.'), finishMatching: l('Завершить сопоставление', 'Finish matching'), nextFour: l('Следующие четыре', 'Next four'),
    quizKicker: l('ТОЧНОЕ ЗНАЧЕНИЕ И ФОРМА', 'PRECISE MEANING AND FORM'), hardOne: l('Сложный момент?', 'Hard one?'), correctTitle: '¡Muy bien!', wrongTitle: l('Нужно ещё немного.', 'Not quite yet.'), naturalAnswer: l('Это естественный вариант.', 'That is the natural option.'), answerIs: l('Ответ:', 'The answer is'), sayIt: l('Скажи вслух.', 'Say it aloud.'), next: l('Дальше', 'Next'),
    sentenceKicker: l('СОБЕРИ ПРЕДЛОЖЕНИЕ', 'BUILD THE SENTENCE'), buildPlaceholder: l('Собери предложение здесь…', 'Build the sentence here…'), perfect: '¡Perfecto!', wordOrder: l('Почти — проверь форму, артикль и порядок.', 'Almost — check the form, article and order.'), checkSentence: l('Проверить предложение', 'Check sentence'),
    composerKicker: l('НАПИШИ ПО СМЫСЛУ · БЕЗ БАНКА СЛОВ', 'WRITE FROM MEANING · NO WORD BANK'), yourPhrase: l('Твоё предложение', 'Your sentence'), composePlaceholder: l('Напиши по-испански…', 'Write in Spanish…'), hideHint: l('Скрыть опору', 'Hide hint'), showHint: l('Нужна опора?', 'Need a hint?'), words: l('слов', 'words'), checkPhrase: l('Проверить предложение', 'Check sentence'), finishLesson: l('Завершить этап', 'Finish stage'), nextPhrase: l('Следующее предложение', 'Next sentence'), accentTitle: l('Смысл верный — поправь ударение.', 'Meaning is right — fix the accent.'), writeIt: l('Напиши так:', 'Write it like this:'), verbFormTitle: l('Нужна личная форма.', 'Use a conjugated form.'), workFormMessage: l('Используй готовую форму глагола.', 'Use a conjugated verb form.'), infinitiveTitle: l('Измени инфинитив.', 'Change the infinitive.'), returnFormMessage: l('Используй личную форму.', 'Use a personal form.'), noPositionTitle: l('No ставится перед глаголом.', 'No goes before the verb.'), naturalVariant: l('Естественный вариант:', 'A natural version:'), notYetTitle: l('Пока не сходится.', 'Not quite yet.'), compareVariant: l('Сравни с вариантом:', 'Compare with this version:'),
    creationKicker: l('ДОМАШНЕЕ ЗАДАНИЕ · МОЙ ДОМ', 'HOMEWORK · MY HOME'), wordBank: l('Позиции перед глазами', 'Positions in front of you'), usefulForms: l('Предметы и блоки:', 'Objects and chunks:'), sentenceNumber: l('Предложение', 'Sentence'), freePlaceholder: l('Например: La mesa está… y…', 'For example: La mesa está… y…'), checkMySentence: l('Проверить описание', 'Check description'), correctDuplicate: l('Правильно, но уже засчитано', 'Correct, but already counted'), correctNotCounted: l('Грамматически правильно, но условие ещё не выполнено', 'Grammatically correct, but the requirement is not met yet'), createdCorrect: l('Правильно — предложение засчитано', 'Correct — sentence counted'), createdWrong: l('Нужно исправить', 'This needs a change'), yourCorrectSentences: l('Твои описания дома', 'Your home descriptions'), removeSentence: l('Удалить предложение', 'Remove sentence'), creationCompleteKicker: l('ТВОИ 2 ПРЕДЛОЖЕНИЯ · 4 ПОЗИЦИИ', 'YOUR 2 SENTENCES · 4 POSITIONS'), creationCompleteTitle: l('Домашнее задание готово.', 'Your homework is ready.'), creationCompleteBody: l('Ниже — два твоих предложения о доме. В них использованы как минимум четыре разные позиционные конструкции — их можно читать Хосе.', 'Below are your two sentences about your home. Together they use at least four different position expressions and are ready to read to José.'), newSet: l('Написать новый вариант', 'Write a new version'), finishAndSave: l('Завершить и сохранить', 'Finish and save'),
  },
  guide: [
    {
      title: 'Buscar ≠ Encontrar',
      body: l('Buscar — пытаться найти: процесс поиска. Encontrar — найти успешно: результат. Поэтому можно buscar долго и всё ещё no encontrar.', 'Buscar means trying to locate something: the search process. Encontrar means locating it successfully: the result. You can buscar for a long time and still no encontrar.'),
      rule: l('buscar = искать · encontrar = найти', 'buscar = search · encontrar = find'),
      examples: [
        ['Busco mi mochila.', l('Я ищу свой рюкзак.', 'I am looking for my backpack.')],
        ['Busco la universidad.', l('Я ищу университет.', 'I am looking for the university.')],
        ['Encuentro la cafetería.', l('Я нахожу кафетерий.', 'I find the café/cafeteria.')],
        ['No encuentro mi teléfono.', l('Я не могу найти свой телефон.', 'I cannot find my phone.')],
      ],
    },
    {
      title: l('Necesitar, entender и «понятный»', 'Necesitar, entender and “understandable”'),
      body: l('Necesito — «мне нужно». После него можно поставить предмет или инфинитив. Entiendo/entiendes — «я понимаю / ты понимаешь». «Понятный» — comprensible или entendible; comprensible нейтрально и широко употребляется.', 'Necesito means “I need”. It can be followed by a thing or an infinitive. Entiendo/entiendes mean “I understand / you understand”. “Understandable” is comprensible or entendible; comprensible is neutral and widespread.'),
      rule: 'necesito + cosa / infinitivo · entiendo ↔ entiendes',
      examples: [
        ['Necesito ayuda. / Necesito tiempo.', l('Мне нужна помощь. / Мне нужно время.', 'I need help. / I need time.')],
        ['Necesito estudiar español.', l('Мне нужно учить испанский.', 'I need to study Spanish.')],
        ['Entiendo. / No entiendo.', l('Я понимаю. / Я не понимаю.', 'I understand. / I do not understand.')],
        ['¿Entiendes?', l('Ты понимаешь?', 'Do you understand?')],
        ['Es comprensible.', l('Это понятно / объяснимо.', 'It is understandable.')],
      ],
    },
    {
      title: l('Traer и nosotros', 'Traer and nosotros'),
      body: l('Traer меняется: yo traigo, tú traes. Trae без s — команда для tú: «принеси». Nosotros означает «мы», но hablamos уже содержит лицо, поэтому nosotros можно опустить.', 'Traer changes: yo traigo, tú traes. Trae without s is the tú command “bring”. Nosotros means “we”, but hablamos already shows the person, so nosotros can be omitted.'),
      rule: 'traigo ↔ traes · ¡trae! · (nosotros) hablamos',
      examples: [
        ['Traigo un libro.', l('Я приношу книгу.', 'I bring a book.')],
        ['Tú traes un ordenador.', l('Ты приносишь компьютер.', 'You bring a computer.')],
        ['Trae tu ordenador.', l('Принеси свой компьютер.', 'Bring your computer.')],
        ['Nosotros hablamos español durante la clase.', l('Мы говорим по-испански во время занятия.', 'We speak Spanish during class.')],
        ['Hablamos español durante la clase.', l('То же значение без nosotros.', 'The same meaning without nosotros.')],
      ],
    },
    {
      title: l('Siempre и durante', 'Siempre and durante'),
      body: l('Siempre описывает частоту и обычно стоит перед глаголом. Durante вводит период и требует существительного: durante la clase, durante el día.', 'Siempre describes frequency and usually goes before the verb. Durante introduces a time period and takes a noun: durante la clase, durante el día.'),
      rule: 'siempre + verbo · durante + periodo',
      examples: [
        ['Siempre estudio por la mañana.', l('Я всегда учусь утром.', 'I always study in the morning.')],
        ['Siempre trabajo aquí.', l('Я всегда работаю здесь.', 'I always work here.')],
        ['Durante la clase.', l('Во время занятия.', 'During class.')],
        ['Durante el día.', l('В течение дня.', 'During the day.')],
      ],
    },
    {
      title: 'Porque ≠ Por qué · Mejor',
      body: l('Porque одним словом отвечает на вопрос и означает «потому что». Por qué — два слова и ударение — задаёт вопрос «почему?». Mejor без артикля обычно «лучше»; «лучший» часто требует el/la mejor.', 'Porque in one word answers a question and means “because”. Por qué is two words with an accent and asks “why?”. Mejor without an article usually means “better”; “the best” often needs el/la mejor.'),
      rule: l('¿Por qué? → Porque… · mejor = лучше', '¿Por qué? → Porque… · mejor = better'),
      examples: [
        ['Estudio español porque vivo en España.', l('Я учу испанский, потому что живу в Испании.', 'I study Spanish because I live in Spain.')],
        ['Trabajo porque necesito dinero.', l('Я работаю, потому что мне нужны деньги.', 'I work because I need money.')],
        ['¿Por qué estudias español?', l('Почему ты учишь испанский?', 'Why do you study Spanish?')],
        ['Este café es mejor.', l('Этот кофе лучше.', 'This coffee is better.')],
        ['Hoy estoy mejor.', l('Сегодня мне лучше.', 'I feel better today.')],
      ],
    },
    {
      title: l('Карта позиций', 'Position map'),
      body: l('Arriba/abajo указывают направление или уровень. Полные отношения между предметами строятся через de: encima de, debajo de, delante de, detrás de, a la izquierda de, a la derecha de. De + el сокращается до del.', 'Arriba/abajo indicate direction or level. Full relations between objects use de: encima de, debajo de, delante de, detrás de, a la izquierda de, a la derecha de. De + el contracts to del.'),
      rule: 'objeto + está + posición + de/del + objeto',
      examples: [
        ['El libro está encima de la mesa.', l('Книга лежит на столе.', 'The book is on top of the table.')],
        ['La gaveta está debajo de la mesa.', l('Ящик находится под столом.', 'The drawer is under the table.')],
        ['El sofá está delante de la ventana.', l('Диван стоит перед окном.', 'The sofa is in front of the window.')],
        ['La cama está detrás de la puerta.', l('Кровать находится за дверью.', 'The bed is behind the door.')],
        ['La mesa está a la izquierda del sofá.', l('Стол слева от дивана.', 'The table is to the left of the sofa.')],
        ['La silla está a la derecha de la cama.', l('Стул справа от кровати.', 'The chair is to the right of the bed.')],
        ['la gaveta / el cajón', l('Gaveta обычно в Латинской Америке; в Испании чаще cajón.', 'Gaveta is common in Latin America; in Spain, cajón is more common.')],
      ],
    },
  ],
  words: [
    { es: 'buscar', en: l('искать', 'to search / look for'), example: 'Busco mi mochila.' },
    { es: 'encontrar', en: l('находить', 'to find'), example: 'No encuentro mi teléfono.' },
    { es: 'necesitar', en: l('нуждаться / нуждаться в', 'to need'), example: 'Necesito ayuda.' },
    { es: 'entender', en: l('понимать', 'to understand'), example: '¿Entiendes?' },
    { es: 'traer', en: l('приносить', 'to bring'), example: 'Traigo un libro. Tú traes un ordenador.' },
    { es: 'siempre', en: l('всегда', 'always'), example: 'Siempre trabajo aquí.' },
    { es: 'durante', en: l('во время / в течение', 'during'), example: 'Durante la clase.' },
    { es: 'nosotros', en: l('мы', 'we'), example: 'Nosotros hablamos español.' },
    { es: 'porque / por qué', en: l('потому что / почему', 'because / why'), example: '¿Por qué? Porque necesito tiempo.' },
    { es: 'mejor', en: l('лучше / лучший', 'better / best'), example: 'Hoy estoy mejor.' },
    { es: 'la casa', en: l('дом', 'house / home'), example: 'Estoy en casa.' },
    { es: 'arriba / abajo', en: l('наверху / внизу', 'up/above / down/below'), example: 'El libro está arriba.' },
    { es: 'encima de', en: l('на, сверху', 'on top of'), example: 'El libro está encima de la mesa.' },
    { es: 'debajo de', en: l('под', 'under / below'), example: 'La gaveta está debajo de la mesa.' },
    { es: 'a la izquierda de', en: l('слева от', 'to the left of'), example: 'La mesa está a la izquierda del sofá.' },
    { es: 'a la derecha de', en: l('справа от', 'to the right of'), example: 'La silla está a la derecha de la cama.' },
    { es: 'delante de', en: l('перед', 'in front of'), example: 'El sofá está delante de la ventana.' },
    { es: 'detrás de', en: l('за, позади', 'behind'), example: 'La cama está detrás de la puerta.' },
    { es: 'la gaveta / el cajón', en: l('выдвижной ящик', 'drawer'), example: 'La gaveta está debajo de la mesa.' },
    { es: 'comprensible / entendible', en: l('понятный', 'understandable'), example: 'La explicación es comprensible.' },
  ],
  quiz: [
    { prompt: l('Ты ещё пытаешься определить местоположение рюкзака. Какой глагол?', 'You are still trying to locate the backpack. Which verb?'), options: ['buscar', 'encontrar', 'traer'], answer: 'buscar', explanation: l('Buscar — процесс поиска.', 'Buscar is the search process.') },
    { prompt: l('Ты успешно нашёл телефон. Какой глагол?', 'You successfully located the phone. Which verb?'), options: ['encontrar', 'buscar', 'necesitar'], answer: 'encontrar', explanation: l('Encontrar — успешный результат.', 'Encontrar is the successful result.') },
    { prompt: 'Yo ___ ayuda.', options: ['necesito', 'necesitas', 'necesitar'], answer: 'necesito', explanation: l('Для yo: necesito.', 'With yo: necesito.') },
    { prompt: '¿Tú ___?', options: ['entiendes', 'entiendo', 'entender'], answer: 'entiendes', explanation: l('Для tú: entiendes.', 'With tú: entiendes.') },
    { prompt: 'Yo ___ un libro.', options: ['traigo', 'traes', 'trae'], answer: 'traigo', explanation: l('Для yo: traigo.', 'With yo: traigo.') },
    { prompt: 'Tú ___ un ordenador.', options: ['traes', 'traigo', 'trae'], answer: 'traes', explanation: l('Обычное утверждение с tú требует traes.', 'A normal tú statement needs traes.') },
    { prompt: l('Выбери команду «Принеси компьютер».', 'Choose the command “Bring the computer.”'), options: ['Trae el ordenador.', 'Traes el ordenador.', 'Traigo el ordenador.'], answer: 'Trae el ordenador.', explanation: l('Trae — повелительная форма tú.', 'Trae is the tú command.') },
    { prompt: '___ estudio por la mañana.', options: ['Siempre', 'Durante', 'Porque'], answer: 'Siempre', explanation: l('Siempre описывает частоту и стоит перед глаголом.', 'Siempre describes frequency and goes before the verb.') },
    { prompt: '___ la clase.', options: ['Durante', 'Siempre', 'Mejor'], answer: 'Durante', explanation: l('Durante вводит период.', 'Durante introduces a period of time.') },
    { prompt: l('Почему?', 'Why?'), options: ['¿Por qué?', '¿Porque?', '¿Por que?'], answer: '¿Por qué?', explanation: l('Вопрос: два слова и ударение в qué.', 'The question uses two words and an accent on qué.') },
    { prompt: l('Потому что мне нужно время.', 'Because I need time.'), options: ['Porque necesito tiempo.', 'Por qué necesito tiempo.', 'Por que necesito tiempo.'], answer: 'Porque necesito tiempo.', explanation: l('Ответ porque пишется одним словом.', 'The answer porque is one word.') },
    { prompt: l('Как естественно сказать «Сегодня мне лучше»?', 'How do you naturally say “I feel better today”?'), options: ['Hoy estoy mejor.', 'Hoy soy mejor.', 'Hoy estoy el mejor.'], answer: 'Hoy estoy mejor.', explanation: l('Состояние требует estar; mejor означает «лучше».', 'A state needs estar; mejor means “better”.') },
    { prompt: 'El libro está ___ la mesa.', options: ['encima de', 'delante', 'izquierda'], answer: 'encima de', explanation: l('Полная конструкция: encima de.', 'The full expression is encima de.') },
    { prompt: 'La gaveta está ___ la mesa.', options: ['debajo de', 'detrás', 'a derecha'], answer: 'debajo de', explanation: l('Полная конструкция: debajo de.', 'The full expression is debajo de.') },
    { prompt: 'La mesa está a la izquierda ___ sofá.', options: ['del', 'de el', 'al'], answer: 'del', explanation: 'De + el = del.' },
    { prompt: l('Какое слово чаще услышишь в Испании для «выдвижного ящика»?', 'Which word is more common in Spain for “drawer”?'), options: ['el cajón', 'la gaveta', 'la cafetería'], answer: 'el cajón', explanation: l('Gaveta нормально в Латинской Америке; в Испании чаще cajón.', 'Gaveta is normal in Latin America; Spain more often uses cajón.') },
    { prompt: l('Как сказать «понятный»?', 'How do you say “understandable”?'), options: ['comprensible', 'entiendo', 'encontrable'], answer: 'comprensible', explanation: l('Comprensible — нейтральный вариант; entendible тоже употребляется.', 'Comprensible is neutral; entendible is also used.') },
    { prompt: l('Нужно ли обязательно говорить nosotros?', 'Must you always say nosotros?'), options: [l('Нет: hablamos уже показывает «мы»', 'No: hablamos already shows “we”'), l('Да, всегда', 'Yes, always'), l('Только после durante', 'Only after durante')], answer: l('Нет: hablamos уже показывает «мы»', 'No: hablamos already shows “we”'), explanation: l('Местоимение можно опустить.', 'The pronoun can be omitted.') },
  ],
  builder: [
    { translation: l('Я ищу свой рюкзак.', 'I am looking for my backpack.'), answer: ['Busco', 'mi', 'mochila.'] },
    { translation: l('Я не нахожу свой телефон.', 'I cannot find my phone.'), answer: ['No', 'encuentro', 'mi', 'teléfono.'] },
    { translation: l('Мне нужно учить испанский.', 'I need to study Spanish.'), answer: ['Necesito', 'estudiar', 'español.'] },
    { translation: l('Ты понимаешь?', 'Do you understand?'), answer: ['¿Entiendes?'] },
    { translation: l('Я приношу книгу.', 'I bring a book.'), answer: ['Traigo', 'un', 'libro.'] },
    { translation: l('Ты приносишь компьютер.', 'You bring a computer.'), answer: ['Tú', 'traes', 'un', 'ordenador.'] },
    { translation: l('Принеси свой компьютер.', 'Bring your computer.'), answer: ['Trae', 'tu', 'ordenador.'] },
    { translation: l('Я всегда учусь утром.', 'I always study in the morning.'), answer: ['Siempre', 'estudio', 'por', 'la', 'mañana.'] },
    { translation: l('Мы говорим по-испански во время занятия.', 'We speak Spanish during class.'), answer: ['Hablamos', 'español', 'durante', 'la', 'clase.'] },
    { translation: l('Я учу испанский, потому что живу в Испании.', 'I study Spanish because I live in Spain.'), answer: ['Estudio', 'español', 'porque', 'vivo', 'en', 'España.'] },
    { translation: l('Почему ты учишь испанский?', 'Why do you study Spanish?'), answer: ['¿Por', 'qué', 'estudias', 'español?'] },
    { translation: l('Сегодня мне лучше.', 'I feel better today.'), answer: ['Hoy', 'estoy', 'mejor.'] },
    { translation: l('Книга лежит на столе.', 'The book is on the table.'), answer: ['El', 'libro', 'está', 'encima', 'de', 'la', 'mesa.'] },
    { translation: l('Ящик находится под столом.', 'The drawer is under the table.'), answer: ['El', 'cajón', 'está', 'debajo', 'de', 'la', 'mesa.'] },
    { translation: l('Стол слева от дивана.', 'The table is to the left of the sofa.'), answer: ['La', 'mesa', 'está', 'a', 'la', 'izquierda', 'del', 'sofá.'] },
    { translation: l('Кровать находится за дверью.', 'The bed is behind the door.'), answer: ['La', 'cama', 'está', 'detrás', 'de', 'la', 'puerta.'] },
  ],
  compose: [
    { prompt: l('Напиши: «Я ищу университет, но не нахожу его».', 'Write: “I am looking for the university, but I cannot find it.”'), hint: 'busco · la universidad · pero · no la encuentro', accepted: ['Busco la universidad, pero no la encuentro.', 'Yo busco la universidad, pero no la encuentro.'], answer: 'Busco la universidad, pero no la encuentro.', explanation: l('Buscar — процесс, encontrar — результат; la заменяет universidad.', 'Buscar is the process, encontrar the result; la replaces universidad.') },
    { prompt: l('Напиши: «Мне нужна помощь, потому что я не понимаю».', 'Write: “I need help because I do not understand.”'), hint: 'necesito ayuda · porque · no entiendo', accepted: ['Necesito ayuda porque no entiendo.', 'Yo necesito ayuda porque no entiendo.'], answer: 'Necesito ayuda porque no entiendo.', explanation: l('Porque объясняет причину и пишется одним словом.', 'Porque gives the reason and is written as one word.') },
    { prompt: l('Напиши: «Мы всегда говорим по-испански во время занятия».', 'Write: “We always speak Spanish during class.”'), hint: 'siempre · hablamos español · durante la clase', accepted: ['Siempre hablamos español durante la clase.', 'Nosotros siempre hablamos español durante la clase.'], answer: 'Siempre hablamos español durante la clase.', explanation: l('Siempre стоит перед hablamos; nosotros можно опустить.', 'Siempre goes before hablamos; nosotros can be omitted.') },
    { prompt: l('Напиши: «Книга лежит на столе».', 'Write: “The book is on the table.”'), hint: 'el libro · está · encima de · la mesa', accepted: ['El libro está encima de la mesa.'], answer: 'El libro está encima de la mesa.', explanation: l('Позиция строится через encima de.', 'The position uses encima de.') },
    { prompt: l('Напиши: «Стол справа от дивана».', 'Write: “The table is to the right of the sofa.”'), hint: 'la mesa · está · a la derecha · de + el sofá', accepted: ['La mesa está a la derecha del sofá.'], answer: 'La mesa está a la derecha del sofá.', explanation: l('Полная конструкция a la derecha de; de + el = del.', 'Use the full expression a la derecha de; de + el = del.') },
    { prompt: l('Напиши: «Сегодня этот кофе лучше».', 'Write: “This coffee is better today.”'), hint: 'hoy · este café · es mejor', accepted: ['Hoy este café es mejor.', 'Este café es mejor hoy.'], answer: 'Hoy este café es mejor.', explanation: l('Mejor без артикля означает «лучше».', 'Mejor without an article means “better”.') },
  ],
  creation: {
    checker: 'house-positions', total: 2,
    title: l('Напиши 2 предложения о своём доме', 'Write 2 sentences about your home'),
    instruction: l('В каждом предложении используй минимум две полные позиции, соединённые через y. В двух засчитанных предложениях должно быть не меньше четырёх разных конструкций. Checker проверяет está/están, de/del, артикли, ударения и не засчитывает повтор позиций как новый.', 'Use at least two complete position expressions in each sentence, joined with y. Across the two counted sentences, use at least four different expressions. The checker verifies está/están, de/del, articles and accents, and repeated positions do not count as new ones.'),
    bank: [
      { word: 'encima de', meaning: l('на / сверху', 'on top of') }, { word: 'debajo de', meaning: l('под', 'under') },
      { word: 'delante de', meaning: l('перед', 'in front of') }, { word: 'detrás de', meaning: l('за / позади', 'behind') },
      { word: 'a la izquierda de', meaning: l('слева от', 'to the left of') }, { word: 'a la derecha de', meaning: l('справа от', 'to the right of') },
      { word: 'arriba / abajo', meaning: l('наверху / внизу', 'up / down') },
    ],
    forms: ['la mesa', 'la silla', 'la cama', 'el sofá', 'la ventana', 'la puerta', 'el libro', 'la mochila', 'el ordenador', 'la gaveta / el cajón', 'está / están', 'de + el = del', 'y'],
  },
}
