const l = (ru, en) => ({ ru, en })

export const joseCoreVerbsLesson = {
  id: 'jose-core-verbs-yo-tu',
  bilingual: true,
  title: l('Yo, tú и шесть главных глаголов', 'Yo, tú and six essential verbs'),
  eyebrow: l('Второй урок с Хосе · A0', 'Second lesson with José · A0'),
  description: l('Научись менять tener, querer, poder, hacer, ir и venir для «я» и «ты» — и сразу используй их в своих фразах.', 'Change tener, querer, poder, hacer, ir and venir for “I” and “you”, then use them in sentences of your own.'),
  accent: 'coral',
  minutes: 42,
  icon: 'Brain',
  guideKicker: l('УРОК С ХОСЕ · YO, TÚ И ОСНОВНЫЕ ГЛАГОЛЫ', 'LESSON WITH JOSÉ · YO, TÚ AND CORE VERBS'),
  modeCopy: {
    guide: { label: l('Карта форм', 'Form map'), description: l('Пойми логику yo/tú, неправильные формы и направление через a/al.', 'Understand yo/tú, irregular forms and direction with a/al.') },
    cards: { label: l('Карточки форм', 'Form cards'), description: l('Вспомни значение инфинитива и обе нужные формы.', 'Recall each infinitive and the two forms you need.') },
    match: { label: l('Сопоставление 4×4', '4×4 Match'), description: l('Соедини глаголы и служебные слова с их значениями.', 'Match verbs and function words with their meanings.') },
    quiz: { label: l('Выбери форму', 'Choose the form'), description: l('Различай tengo/tienes, puedo/puedes, voy/vas и другие пары.', 'Distinguish tengo/tienes, puedo/puedes, voy/vas and the other pairs.') },
    builder: { label: l('Конструктор предложений', 'Sentence builder'), description: l('Собери ключевые предложения занятия из перемешанных слов.', 'Build the key lesson sentences from shuffled words.') },
    compose: { label: l('Напиши по смыслу', 'Write from meaning'), description: l('Напиши предложение без банка слов, но с заданным смыслом.', 'Write a sentence without a word bank but with a target meaning.') },
    create: { label: l('5 своих предложений', '5 sentences of your own'), description: l('Финальное задание Хосе: пять разных фраз из слов двух уроков.', 'José’s final task: five different sentences using words from both lessons.') },
  },
  ui: {
    backToPlayground: l('Назад к урокам', 'Back to playground'), mastery: l('освоено', 'mastery'), modes: l('режимов', 'modes'),
    chooseMode: l('ЭТАПЫ УРОКА', 'LESSON STAGES'), practiceQuestion: l('Пройди от формы к собственной речи', 'Move from forms to your own speech'),
    completed: l('Пройдено', 'Completed'), done: l('Готово', 'Done'), start: l('Начать', 'Start'), minutesShort: l('мин', 'min'), wordsLabel: l('слов', 'words'), phraseOfDay: l('Урок дня', 'Lesson of the day'),
    back: l('Назад', 'Back'), exit: l('Выйти', 'Exit'), savedPhrases: l('Сохранённые фразы', 'Saved phrases'), cardTitle: l('Формы и смысл', 'Forms & Meaning'),
    spanish: l('Испанский', 'Spanish'), targetLanguage: l('Русский', 'English'), meaningLabel: l('ЗНАЧЕНИЕ И ФОРМЫ', 'MEANING AND FORMS'), tapToSpanish: l('Нажми, чтобы увидеть испанский', 'Tap to see Spanish'), playPronunciation: l('Прослушать произношение', 'Play Spanish pronunciation'),
    listenTitle: l('Слушай и повторяй форму', 'Listen and repeat the form'), listenBody: l('Послушай пример и повтори вслух. Обращай внимание на форму yo или tú.', 'Listen to the example and repeat it aloud. Notice whether it uses yo or tú.'), gotIt: l('Запомнил', 'Got it'), finish: l('Завершить', 'Finish'),
    previous: l('Назад', 'Previous'), startPractising: l('Перейти к практике', 'Start practising'), understand: l('Понятно', 'I understand'),
    matchKicker: l('СОПОСТАВЛЕНИЕ 4 × 4', '4 × 4 MATCH'), connectPairs: l('Соедини пары', 'Connect the pairs'), round: l('Раунд', 'Round'), of: l('из', 'of'), matched: l('готово', 'matched'), matchCorrect: l('¡Sí! Пара совпала.', '¡Sí! That pair matches.'), matchWrong: l('Не эта пара — попробуй другое значение.', 'Not this pair — try another meaning.'), finishMatching: l('Завершить сопоставление', 'Finish matching'), nextFour: l('Следующие четыре', 'Next four'),
    quizKicker: l('YO ИЛИ TÚ?', 'YO OR TÚ?'), hardOne: l('Сложный момент?', 'Hard one?'), correctTitle: '¡Muy bien!', wrongTitle: l('Пока не совсем.', 'Not quite yet.'), naturalAnswer: l('Это естественный ответ.', 'That is the natural answer.'), answerIs: l('Ответ:', 'The answer is'), sayIt: l('Скажи его вслух.', 'Say it aloud.'), next: l('Дальше', 'Next'),
    sentenceKicker: l('СОБЕРИ ПРЕДЛОЖЕНИЕ', 'BUILD THE SENTENCE'), buildPlaceholder: l('Собери предложение здесь…', 'Build the sentence here…'), perfect: '¡Perfecto!', wordOrder: l('Почти — проверь форму и порядок слов.', 'Almost — check the form and word order.'), checkSentence: l('Проверить предложение', 'Check sentence'),
    composerKicker: l('НАПИШИ ПО СМЫСЛУ · БЕЗ БАНКА СЛОВ', 'WRITE FROM MEANING · NO WORD BANK'), yourPhrase: l('Твоё предложение', 'Your sentence'), composePlaceholder: l('Напиши по-испански…', 'Write in Spanish…'), hideHint: l('Скрыть опору', 'Hide hint'), showHint: l('Нужна опора?', 'Need a hint?'), words: l('слов', 'words'), checkPhrase: l('Проверить предложение', 'Check sentence'), finishLesson: l('Завершить этап', 'Finish stage'), nextPhrase: l('Следующее предложение', 'Next sentence'),
    accentTitle: l('Смысл верный — поправь ударение.', 'Meaning is right — fix the accent.'), writeIt: l('Напиши так:', 'Write it like this:'), verbFormTitle: l('Нужна личная форма глагола.', 'Use a conjugated verb.'), workFormMessage: l('Для «я работаю» используй trabajo, а trabajar — инфинитив.', 'For “I work”, use trabajo; trabajar is the infinitive.'), infinitiveTitle: l('Инфинитив нужно изменить.', 'Change the infinitive.'), returnFormMessage: l('Для «я возвращаюсь» используй vuelvo, а не volver.', 'For “I return”, use vuelvo, not volver.'), noPositionTitle: l('Поставь no перед глаголом.', 'Put no before the verb.'), naturalVariant: l('Естественный вариант:', 'A natural version:'), notYetTitle: l('Пока не сходится.', 'Not quite yet.'), compareVariant: l('Сравни с вариантом:', 'Compare with this version:'),
    creationKicker: l('ДОМАШНЕЕ ЗАДАНИЕ ХОСЕ · СВОИ ФРАЗЫ', 'JOSÉ’S HOMEWORK · YOUR OWN SENTENCES'), wordBank: l('Слова двух уроков', 'Words from both lessons'), usefulForms: l('Личные формы и блоки:', 'Personal forms and chunks:'), sentenceNumber: l('Предложение', 'Sentence'), freePlaceholder: l('Придумай своё предложение…', 'Create your own sentence…'), checkMySentence: l('Проверить моё предложение', 'Check my sentence'), correctDuplicate: l('Правильно, но уже засчитано', 'Correct, but already counted'), createdCorrect: l('Правильно — добавлено в список', 'Correct — added to your list'), createdWrong: l('Нужно исправить', 'This needs a change'), yourCorrectSentences: l('Твои правильные предложения', 'Your correct sentences'), removeSentence: l('Удалить предложение', 'Remove sentence'),
    creationCompleteKicker: l('ТВОИ 5 ПРАВИЛЬНЫХ ПРЕДЛОЖЕНИЙ', 'YOUR 5 CORRECT SENTENCES'), creationCompleteTitle: l('Задание Хосе выполнено.', 'José’s task is complete.'), creationCompleteBody: l('Ниже — пять предложений, которые ты придумал и написал сам, используя материал двух занятий.', 'Below are five sentences you created and wrote yourself using material from both lessons.'), newSet: l('Написать новый набор', 'Write a new set'), finishAndSave: l('Завершить и сохранить', 'Finish and save'),
  },
  guide: [
    {
      title: l('Yo и tú меняют форму глагола', 'Yo and tú change the verb form'),
      body: l('Инфинитив называет действие вообще: tener — «иметь». В предложении форма показывает, кто действует. Yo и tú часто можно не произносить, но окончания и неправильные формы всё равно должны совпадать.', 'An infinitive names an action in general: tener means “to have”. In a sentence, the form shows who acts. Yo and tú are often omitted, but the verb form must still agree.'),
      rule: l('yo → форма «я» · tú → форма «ты»', 'yo → I-form · tú → you-form'),
      examples: [
        ['Yo estudio. / Tú estudias.', l('Я учусь. / Ты учишься.', 'I study. / You study.')],
        ['Yo trabajo. / Tú trabajas.', l('Я работаю. / Ты работаешь.', 'I work. / You work.')],
        ['Yo vivo aquí.', l('Я живу здесь.', 'I live here.')],
        ['Tú estás aquí.', l('Ты здесь.', 'You are here.')],
        ['tú ≠ tu', l('Tú = ты; tu без ударения = твой/твоя.', 'Tú = you; tu without an accent = your.')],
      ],
    },
    {
      title: 'Tener + Querer',
      body: l('Tener и querer меняют корень. Для yo: tengo, quiero. Для tú: tienes, quieres. Querer означает «хотеть», а с человеком также может означать «любить/дорожить». Amar — более прямое «любить».', 'Tener and querer change their stem. With yo: tengo, quiero. With tú: tienes, quieres. Querer means “to want” and can also mean “to love/care for” with a person. Amar is the more direct verb “to love”.'),
      rule: 'tengo ↔ tienes · quiero ↔ quieres',
      examples: [
        ['Tengo tiempo. / ¿Tienes tiempo?', l('У меня есть время. / У тебя есть время?', 'I have time. / Do you have time?')],
        ['No tengo tiempo.', l('У меня нет времени.', 'I do not have time.')],
        ['Quiero café. / ¿Quieres café?', l('Я хочу кофе. / Ты хочешь кофе?', 'I want coffee. / Do you want coffee?')],
        ['Quiero aprender español.', l('Я хочу учить испанский.', 'I want to learn Spanish.')],
        ['Quiero trabajar en España.', l('Я хочу работать в Испании.', 'I want to work in Spain.')],
      ],
    },
    {
      title: 'Poder + Hacer',
      body: l('Важная поправка: puedo — «я могу», а puedes — «ты можешь». После poder следующее действие остаётся инфинитивом. Hacer меняется на hago/haces. Буква h не читается: hago звучит примерно «а-го».', 'Important correction: puedo means “I can”, while puedes means “you can”. After poder, the next action stays in the infinitive. Hacer changes to hago/haces. The h is silent, so hago sounds roughly like “AH-go”.'),
      rule: 'puedo + infinitivo · puedes + infinitivo · hago ↔ haces',
      examples: [
        ['Puedo estudiar.', l('Я могу учиться.', 'I can study.')],
        ['No puedo ahora.', l('Я сейчас не могу.', 'I cannot now.')],
        ['¿Puedes venir?', l('Ты можешь прийти?', 'Can you come?')],
        ['Hago ejercicio. / Hago la tarea.', l('Я делаю упражнения. / Я делаю домашнее задание.', 'I exercise. / I do the homework.')],
        ['¿Qué haces ahora?', l('Что ты сейчас делаешь?', 'What are you doing now?')],
        ['el poder', l('Как существительное poder может означать «сила/власть».', 'As a noun, poder can mean “power”.')],
      ],
    },
    {
      title: 'Ir + Venir',
      body: l('Ir — движение от говорящего: voy/vas. Venir — движение к говорящему: vengo/vienes. Направление вводится через a. Перед el два слова сливаются: a + el = al. Форма iré означает «я пойду» в будущем; сейчас основная форма — voy.', 'Ir is movement away from the speaker: voy/vas. Venir is movement toward the speaker: vengo/vienes. Use a for a destination. Before el, the two words contract: a + el = al. Iré means “I will go” in the future; the main present form here is voy.'),
      rule: 'voy ↔ vas · vengo ↔ vienes · a + el = al',
      examples: [
        ['Voy a la playa.', l('Я иду на пляж: playa женского рода, поэтому a la.', 'I am going to the beach: playa is feminine, so use a la.')],
        ['Voy al trabajo.', l('Я иду на работу: a + el trabajo = al trabajo.', 'I am going to work: a + el trabajo = al trabajo.')],
        ['Voy a casa. / Voy ahora.', l('Я иду домой. / Я иду сейчас.', 'I am going home. / I am going now.')],
        ['Vengo mañana. / ¿Vienes?', l('Я приду завтра. / Ты придёшь?', 'I am coming tomorrow. / Are you coming?')],
        ['Ven aquí.', l('Иди/приходи сюда — команда для tú.', 'Come here — the command for tú.')],
        ['Iré a la playa mañana.', l('Я пойду на пляж завтра — небольшое знакомство с будущим.', 'I will go to the beach tomorrow — a small preview of the future.')],
      ],
    },
    {
      title: 'Estar + Ser',
      body: l('Для yo: estoy и soy. Для tú: estás и eres. Estar отвечает за место и состояние; ser — за роль, идентичность и происхождение.', 'With yo: estoy and soy. With tú: estás and eres. Estar handles location and state; ser handles role, identity and origin.'),
      rule: 'estoy ↔ estás · soy ↔ eres',
      examples: [
        ['Estoy aquí. / Tú estás aquí.', l('Я здесь. / Ты здесь.', 'I am here. / You are here.')],
        ['Estoy bien. / Estoy en casa.', l('Я в порядке. / Я дома.', 'I am well. / I am at home.')],
        ['Soy estudiante.', l('Я студент.', 'I am a student.')],
        ['Soy arquitecto.', l('Я архитектор.', 'I am an architect.')],
        ['Soy de Ucrania.', l('Я из Украины.', 'I am from Ukraine.')],
      ],
    },
    {
      title: l('Артикли и фраза-бонус', 'Articles and a bonus phrase'),
      body: l('El/la — единственное число, los/las — множественное. Род слова определяет артикль: el trabajo, la playa, la tarea. Фраза Хосе «No veo ningún avión» означает «Я не вижу ни одного самолёта».', 'El/la are singular; los/las are plural. The noun’s gender chooses the article: el trabajo, la playa, la tarea. José’s phrase “No veo ningún avión” means “I do not see any airplane”.'),
      rule: 'el · la · los · las · ningún + masculino singular',
      examples: [
        ['el trabajo / la playa', l('работа / пляж', 'work / the beach')],
        ['los trabajos / las playas', l('работы / пляжи', 'jobs / beaches')],
        ['No veo ningún avión.', l('Я не вижу ни одного самолёта.', 'I do not see any airplane.')],
        ['Yo hago café.', l('Я готовлю кофе. Не забудь ударение: café.', 'I make coffee. Remember the accent in café.')],
      ],
    },
  ],
  words: [
    { es: 'yo / tú', en: l('я / ты', 'I / you'), example: 'Yo estudio. Tú estudias.' },
    { es: 'tener → tengo / tienes', en: l('иметь → у меня есть / у тебя есть', 'to have → I have / you have'), example: 'Tengo tiempo. ¿Tienes tiempo?' },
    { es: 'querer → quiero / quieres', en: l('хотеть → я хочу / ты хочешь', 'to want → I want / you want'), example: 'Quiero café. ¿Quieres café?' },
    { es: 'poder → puedo / puedes', en: l('мочь → я могу / ты можешь', 'can → I can / you can'), example: 'Puedo estudiar. ¿Puedes venir?' },
    { es: 'hacer → hago / haces', en: l('делать → я делаю / ты делаешь', 'to do/make → I do / you do'), example: 'Hago ejercicio. ¿Qué haces?' },
    { es: 'ir → voy / vas', en: l('идти → я иду / ты идёшь', 'to go → I go / you go'), example: 'Voy a la playa. ¿Vas a casa?' },
    { es: 'venir → vengo / vienes', en: l('приходить → я прихожу / ты приходишь', 'to come → I come / you come'), example: 'Vengo mañana. ¿Vienes?' },
    { es: 'estar → estoy / estás', en: l('быть, находиться → я / ты', 'to be → I am / you are'), example: 'Estoy bien. Tú estás aquí.' },
    { es: 'ser → soy / eres', en: l('быть → я являюсь / ты являешься', 'to be → I am / you are'), example: 'Soy arquitecto. ¿Eres estudiante?' },
    { es: 'amar', en: l('любить', 'to love'), example: 'Amar es un verbo.' },
    { es: 'a / al', en: l('к, в / a + el', 'to / a + el'), example: 'Voy a casa. Voy al trabajo.' },
    { es: 'el / la / los / las', en: l('определённые артикли', 'the: definite articles'), example: 'El trabajo. La playa. Los trabajos. Las playas.' },
  ],
  quiz: [
    { prompt: l('Puedo означает…', 'Puedo means…'), options: [l('я могу', 'I can'), l('ты можешь', 'you can'), l('я хочу', 'I want')], answer: l('я могу', 'I can'), explanation: l('Puedo — форма yo. Для tú нужна puedes.', 'Puedo is the yo form. With tú, use puedes.') },
    { prompt: 'Tú ___ venir.', options: ['puedo', 'puedes', 'poder'], answer: 'puedes', explanation: l('С tú: puedes + инфинитив venir.', 'With tú: puedes + the infinitive venir.') },
    { prompt: 'Yo ___ tiempo.', options: ['tengo', 'tienes', 'tener'], answer: 'tengo', explanation: l('С yo глагол tener меняется на tengo.', 'With yo, tener changes to tengo.') },
    { prompt: '¿___ café?', options: ['Quieres', 'Quiero', 'Querer'], answer: 'Quieres', explanation: l('Вопрос к tú требует формы quieres.', 'A question to tú needs quieres.') },
    { prompt: 'Yo ___ ejercicio.', options: ['hago', 'haces', 'hacer'], answer: 'hago', explanation: l('Для yo: hago. Буква h не читается.', 'With yo: hago. The h is silent.') },
    { prompt: '¿Qué ___ ahora?', options: ['hago', 'haces', 'hacer'], answer: 'haces', explanation: l('Вопрос адресован tú, поэтому haces.', 'The question addresses tú, so use haces.') },
    { prompt: 'Yo ___ a la playa.', options: ['voy', 'vas', 'ir'], answer: 'voy', explanation: l('Для yo глагол ir меняется на voy.', 'With yo, ir changes to voy.') },
    { prompt: l('Выбери правильное сокращение.', 'Choose the correct contraction.'), options: ['a el trabajo', 'al trabajo', 'a la trabajo'], answer: 'al trabajo', explanation: 'a + el = al.' },
    { prompt: 'Yo ___ mañana.', options: ['vengo', 'vienes', 'venir'], answer: 'vengo', explanation: l('Для yo: vengo.', 'With yo: vengo.') },
    { prompt: '¿___ mañana?', options: ['Vienes', 'Vengo', 'Venir'], answer: 'Vienes', explanation: l('Для tú: vienes.', 'With tú: vienes.') },
    { prompt: 'Yo ___ en casa.', options: ['estoy', 'soy', 'estás'], answer: 'estoy', explanation: l('Место требует estar; для yo — estoy.', 'Location needs estar; with yo, use estoy.') },
    { prompt: 'Yo ___ arquitecto.', options: ['soy', 'estoy', 'eres'], answer: 'soy', explanation: l('Роль требует ser; для yo — soy.', 'A role needs ser; with yo, use soy.') },
    { prompt: l('Что означает iré?', 'What does iré mean?'), options: [l('я пойду', 'I will go'), l('я иду', 'I go'), l('ты идёшь', 'you go')], answer: l('я пойду', 'I will go'), explanation: l('Iré — будущее. Voy — настоящее.', 'Iré is future; voy is present.') },
    { prompt: l('Как правильно написать?', 'Which spelling is correct?'), options: ['Yo hago cafe.', 'Yo hago café.', 'Yo ago café.'], answer: 'Yo hago café.', explanation: l('H в hago не читается, но пишется; café имеет ударение.', 'The h in hago is silent but written; café has an accent.') },
    { prompt: l('Выбери полную отрицательную фразу.', 'Choose the complete negative sentence.'), options: ['No veo ningún avión.', 'Veo no avión.', 'No ningún avión.'], answer: 'No veo ningún avión.', explanation: l('No стоит перед veo, а ningún — перед существительным мужского рода.', 'No comes before veo, and ningún comes before a masculine singular noun.') },
  ],
  builder: [
    { translation: l('Я учусь.', 'I study.'), answer: ['Yo', 'estudio.'] },
    { translation: l('Ты работаешь.', 'You work.'), answer: ['Tú', 'trabajas.'] },
    { translation: l('У меня есть время.', 'I have time.'), answer: ['Tengo', 'tiempo.'] },
    { translation: l('У тебя есть время?', 'Do you have time?'), answer: ['¿Tienes', 'tiempo?'] },
    { translation: l('Я хочу учить испанский.', 'I want to learn Spanish.'), answer: ['Quiero', 'aprender', 'español.'] },
    { translation: l('Ты хочешь кофе?', 'Do you want coffee?'), answer: ['¿Quieres', 'café?'] },
    { translation: l('Я могу учиться.', 'I can study.'), answer: ['Puedo', 'estudiar.'] },
    { translation: l('Ты можешь прийти?', 'Can you come?'), answer: ['¿Puedes', 'venir?'] },
    { translation: l('Я делаю упражнения.', 'I exercise.'), answer: ['Hago', 'ejercicio.'] },
    { translation: l('Что ты сейчас делаешь?', 'What are you doing now?'), answer: ['¿Qué', 'haces', 'ahora?'] },
    { translation: l('Я иду на пляж.', 'I am going to the beach.'), answer: ['Voy', 'a', 'la', 'playa.'] },
    { translation: l('Я иду на работу.', 'I am going to work.'), answer: ['Voy', 'al', 'trabajo.'] },
    { translation: l('Я приду завтра.', 'I am coming tomorrow.'), answer: ['Vengo', 'mañana.'] },
    { translation: l('Ты придёшь?', 'Are you coming?'), answer: ['¿Vienes?'] },
    { translation: l('Я дома.', 'I am at home.'), answer: ['Estoy', 'en', 'casa.'] },
    { translation: l('Я архитектор.', 'I am an architect.'), answer: ['Soy', 'arquitecto.'] },
  ],
  compose: [
    { prompt: l('Напиши: «Я хочу работать здесь».', 'Write: “I want to work here.”'), hint: 'yo → quiero · trabajar · aquí', accepted: ['Quiero trabajar aquí.', 'Yo quiero trabajar aquí.'], answer: 'Quiero trabajar aquí.', explanation: l('Quiero — форма yo, а после неё trabajar остаётся инфинитивом.', 'Quiero is the yo form, and trabajar stays in the infinitive after it.') },
    { prompt: l('Напиши: «У меня много времени».', 'Write: “I have a lot of time.”'), hint: 'tener → tengo · mucho tiempo', accepted: ['Tengo mucho tiempo.', 'Yo tengo mucho tiempo.'], answer: 'Tengo mucho tiempo.', explanation: l('Tengo — форма yo; с tiempo используется mucho.', 'Tengo is the yo form; tiempo takes mucho.') },
    { prompt: l('Напиши: «Ты можешь прийти завтра?»', 'Write: “Can you come tomorrow?”'), hint: 'tú → puedes · venir · mañana', accepted: ['¿Puedes venir mañana?', '¿Tú puedes venir mañana?', 'Tú puedes venir mañana.'], answer: '¿Puedes venir mañana?', explanation: l('Puedes согласовано с tú, а venir после poder остаётся инфинитивом.', 'Puedes agrees with tú, and venir stays in the infinitive after poder.') },
    { prompt: l('Напиши: «Я сейчас делаю домашнее задание».', 'Write: “I am doing the homework now.”'), hint: 'ahora · hacer → hago · la tarea', accepted: ['Ahora hago la tarea.', 'Hago la tarea ahora.', 'Yo hago la tarea ahora.'], answer: 'Ahora hago la tarea.', explanation: l('Hago — форма yo; la согласуется с tarea.', 'Hago is the yo form; la agrees with tarea.') },
    { prompt: l('Напиши: «Я иду на пляж».', 'Write: “I am going to the beach.”'), hint: 'ir → voy · a la playa', accepted: ['Voy a la playa.', 'Yo voy a la playa.'], answer: 'Voy a la playa.', explanation: l('Voy — форма yo; перед playa используется a la.', 'Voy is the yo form; a la is used before playa.') },
    { prompt: l('Напиши: «Я иду на работу».', 'Write: “I am going to work.”'), hint: 'voy · a + el trabajo', accepted: ['Voy al trabajo.', 'Yo voy al trabajo.'], answer: 'Voy al trabajo.', explanation: 'A + el = al.' },
    { prompt: l('Напиши: «Ты здесь».', 'Write: “You are here.”'), hint: 'tú · estar → estás · aquí', accepted: ['Tú estás aquí.', 'Estás aquí.'], answer: 'Tú estás aquí.', explanation: l('Для tú форма estar — estás; здесь нужно письменное ударение.', 'The tú form of estar is estás, with a written accent.') },
    { prompt: l('Напиши: «Я студент и я из Украины».', 'Write: “I am a student and I am from Ukraine.”'), hint: 'soy estudiante · y · soy de Ucrania', accepted: ['Soy estudiante y soy de Ucrania.', 'Yo soy estudiante y soy de Ucrania.'], answer: 'Soy estudiante y soy de Ucrania.', explanation: l('Обе части описывают идентичность и происхождение, поэтому используется soy.', 'Both clauses describe identity and origin, so they use soy.') },
  ],
  creation: {
    checker: 'core-verbs',
    total: 5,
    title: l('Напиши 5 предложений из слов двух уроков', 'Write 5 sentences using words from both lessons'),
    instruction: l('Это задание Хосе без заданного перевода. Слова и нужные формы перед глазами, но смысл выбираешь ты. Checker принимает разные естественные конструкции, объясняет каждый ответ и не завершит этап, пока не будет пяти разных правильных предложений.', 'This is José’s task with no target translation. The words and useful forms stay visible, but you choose the meaning. The checker accepts different natural constructions, explains every answer and keeps the stage open until you have five different correct sentences.'),
    bank: [
      { word: 'Yo / Tú', meaning: l('я / ты', 'I / you') }, { word: 'Sí / No', meaning: l('да / нет, не', 'yes / no, not') },
      { word: 'Aquí / Allí', meaning: l('здесь / там', 'here / there') }, { word: 'Ahora', meaning: l('сейчас', 'now') },
      { word: 'Tiempo', meaning: l('время', 'time') }, { word: 'Mucho', meaning: l('много', 'a lot') },
      { word: 'Tener', meaning: l('иметь', 'to have') }, { word: 'Querer', meaning: l('хотеть', 'to want') },
      { word: 'Poder', meaning: l('мочь', 'can') }, { word: 'Hacer', meaning: l('делать', 'to do/make') },
      { word: 'Ir', meaning: l('идти', 'to go') }, { word: 'Venir', meaning: l('приходить', 'to come') },
      { word: 'Estar / Ser', meaning: l('быть', 'to be') }, { word: 'Trabajar', meaning: l('работать', 'to work') },
      { word: 'Estudiar', meaning: l('учиться', 'to study') }, { word: 'Volver', meaning: l('возвращаться', 'to return') },
      { word: 'Y', meaning: l('и', 'and') },
    ],
    forms: ['tengo / tienes', 'quiero / quieres', 'puedo / puedes', 'hago / haces', 'voy / vas', 'vengo / vienes', 'estoy / estás', 'soy / eres', 'trabajo / trabajas', 'estudio / estudias', 'a casa', 'a la playa', 'al trabajo', 'en España', 'mañana'],
  },
}
