const l = (ru, en) => ({ ru, en })

export const joseSentenceLesson = {
  id: 'jose-sentence-foundations',
  bilingual: true,
  featured: true,
  title: l('Строй свои первые фразы', 'Build your first Spanish sentences'),
  eyebrow: l('Урок с Хосе · A0', 'Lesson with José · A0'),
  description: l('Преврати sí, no, aquí, ahora и повседневные глаголы во фразы, которые ты создаёшь сам.', 'Turn sí, no, aquí, ahora and everyday verbs into sentences you can create yourself.'),
  accent: 'coral',
  minutes: 32,
  icon: 'MessagesSquare',
  guideKicker: l('ПОВТОРЕНИЕ С ХОСЕ · ОТ СЛОВ К ФРАЗАМ', 'JOSÉ RECAP · FROM WORDS TO SENTENCES'),
  modeCopy: {
    guide: { label: l('Понятное объяснение', 'Clear guide'), description: l('Восстанови правила и примеры из урока без грамматического тумана.', 'Rebuild the rules and examples from the lesson without grammar fog.') },
    cards: { label: l('Карточки в обе стороны', 'Two-way deck'), description: l('Вспомни каждое слово по-испански и его значение.', 'Recall every Spanish word and its meaning.') },
    match: { label: l('Сопоставление 4×4', '4×4 Match'), description: l('Соедини испанские слова с их значениями.', 'Connect the Spanish words with their meanings.') },
    quiz: { label: l('Проверка понимания', 'Understanding quiz'), description: l('Проверь значение, формы глаголов, порядок слов и произношение.', 'Check meaning, verb forms, word order and pronunciation.') },
    builder: { label: l('Конструктор фраз', 'Sentence lab'), description: l('Собери десять фраз из перемешанных слов.', 'Build ten sentences from shuffled words.') },
    compose: { label: l('Напиши сам', 'Write it yourself'), description: l('Создай всю фразу с нуля и получи полезную проверку.', 'Create the whole sentence from scratch and get a useful check.') },
  },
  ui: {
    backToPlayground: l('Назад к урокам', 'Back to playground'),
    mastery: l('освоено', 'mastery'),
    modes: l('режимов', 'modes'),
    chooseMode: l('ВЫБЕРИ ЭТАП', 'CHOOSE A MODE'),
    practiceQuestion: l('Как будем закреплять?', 'How do you want to practise?'),
    completed: l('Пройдено', 'Completed'),
    done: l('Готово', 'Done'),
    start: l('Начать', 'Start'),
    minutesShort: l('мин', 'min'),
    wordsLabel: l('слов', 'words'),
    phraseOfDay: l('Фраза дня', 'Phrase of the day'),
    back: l('Назад', 'Back'),
    exit: l('Выйти', 'Exit'),
    savedPhrases: l('Сохранённые фразы', 'Saved phrases'),
    cardTitle: l('Спроси и вспомни', 'Ask & Find'),
    spanish: l('Испанский', 'Spanish'),
    targetLanguage: l('Русский', 'English'),
    meaningLabel: l('ЗНАЧЕНИЕ ПО-РУССКИ', 'ENGLISH MEANING'),
    tapToSpanish: l('Нажми, чтобы увидеть испанский', 'Tap to see Spanish'),
    playPronunciation: l('Прослушать произношение', 'Play Spanish pronunciation'),
    listenTitle: l('Слушай и запоминай слово', 'Listen and remember the word'),
    listenBody: l('Нажми на динамик, послушай произношение и повтори вслух.', 'Tap the speaker, listen to the pronunciation and repeat it out loud.'),
    gotIt: l('Запомнил', 'Got it'),
    finish: l('Завершить', 'Finish'),
    previous: l('Назад', 'Previous'),
    startPractising: l('Перейти к практике', 'Start practising'),
    understand: l('Понятно', 'I understand'),
    matchKicker: l('СОПОСТАВЛЕНИЕ 4 × 4', '4 × 4 MATCH'),
    connectPairs: l('Соедини пары', 'Connect the pairs'),
    round: l('Раунд', 'Round'),
    of: l('из', 'of'),
    matched: l('готово', 'matched'),
    matchCorrect: l('¡Sí! Эта пара совпала.', '¡Sí! That pair belongs together.'),
    matchWrong: l('Не эта пара — попробуй другое значение.', 'Not this pair — try the other meaning.'),
    finishMatching: l('Завершить сопоставление', 'Finish matching'),
    nextFour: l('Следующие четыре', 'Next four'),
    quizKicker: l('ПРОВЕРКА ПОНИМАНИЯ', 'UNDERSTANDING QUIZ'),
    hardOne: l('Сложный момент?', 'Hard one?'),
    correctTitle: '¡Muy bien!',
    wrongTitle: l('Пока не совсем.', 'Not quite yet.'),
    naturalAnswer: l('Это естественный ответ.', 'That is the natural answer.'),
    answerIs: l('Ответ:', 'The answer is'),
    sayIt: l('Произнеси его один раз вслух.', 'Say it once out loud.'),
    next: l('Дальше', 'Next'),
    sentenceKicker: l('КОНСТРУКТОР ФРАЗ', 'SENTENCE LAB'),
    buildPlaceholder: l('Собери фразу здесь…', 'Build the sentence here…'),
    perfect: '¡Perfecto!',
    wordOrder: l('Почти — проверь порядок слов.', 'Almost — check the word order.'),
    checkSentence: l('Проверить фразу', 'Check sentence'),
    composerKicker: l('СОЗДАЙ ФРАЗУ · БЕЗ БАНКА СЛОВ', 'CREATE A SENTENCE · NO WORD BANK'),
    yourPhrase: l('Твоя фраза', 'Your sentence'),
    composePlaceholder: l('Напиши по-испански…', 'Write in Spanish…'),
    hideHint: l('Скрыть опору', 'Hide hint'),
    showHint: l('Нужна опора?', 'Need a hint?'),
    words: l('слов', 'words'),
    checkPhrase: l('Проверить фразу', 'Check sentence'),
    finishLesson: l('Завершить урок', 'Finish lesson'),
    nextPhrase: l('Следующая фраза', 'Next sentence'),
    accentTitle: l('Смысл верный — поправь ударение.', 'Meaning is right — fix the accent.'),
    writeIt: l('Напиши так:', 'Write it like this:'),
    verbFormTitle: l('Нужна форма глагола.', 'Use a conjugated verb.'),
    workFormMessage: l('Для «я работаю» используй trabajo, а trabajar означает «работать».', 'For “I work”, use trabajo; trabajar means “to work”.'),
    infinitiveTitle: l('Инфинитив нужно изменить.', 'Change the infinitive.'),
    returnFormMessage: l('Для «я возвращаюсь» используй vuelvo, а не volver.', 'For “I return”, use vuelvo, not volver.'),
    noPositionTitle: l('Поставь no перед глаголом.', 'Put no before the verb.'),
    naturalVariant: l('Один естественный вариант:', 'One natural version:'),
    notYetTitle: l('Пока не сходится.', 'Not quite yet.'),
    compareVariant: l('Сравни с рабочим вариантом:', 'Compare it with this version:'),
  },
  guide: [
    {
      title: l('Сначала — короткие ответы', 'Start with short answers'),
      body: l('Sí и no уже могут быть полным ответом. Перед глаголом no делает всё предложение отрицательным. У sí есть ударение: без него si означает «если».', 'Sí and no can already be complete answers. Before a verb, no makes the whole sentence negative. Sí has a written accent; without it, si means “if”.'),
      rule: l('Sí = да · No + verbo = не делаю', 'Sí = yes · No + verb = do not'),
      examples: [
        ['Sí, entiendo.', l('Да, я понимаю.', 'Yes, I understand.')],
        ['Sí, quiero.', l('Да, я хочу.', 'Yes, I want to.')],
        ['Sí, tengo tiempo.', l('Да, у меня есть время.', 'Yes, I have time.')],
        ['No entiendo.', l('Я не понимаю.', 'I do not understand.')],
        ['No tengo tiempo.', l('У меня нет времени.', 'I do not have time.')],
        ['No puedo.', l('Я не могу.', 'I cannot.')],
      ],
    },
    {
      title: l('Добавь место и время', 'Add place and time'),
      body: l('Aquí — «здесь», allí — «там», ahora — «сейчас». Эти слова можно ставить в начало или ближе к концу. Для начала используй устойчивую схему: время + действие + место.', 'Aquí means “here”, allí means “there”, and ahora means “now”. These words can go at the beginning or near the end. Start with a reliable pattern: time + action + place.'),
      rule: 'Ahora + verbo + aquí / allí',
      examples: [
        ['Aquí.', l('Здесь. Этого достаточно как короткого ответа.', 'Here. This is enough as a short answer.')],
        ['Aquí está mi casa.', l('Вот здесь мой дом.', 'Here is my home.')],
        ['Estoy aquí.', l('Я здесь.', 'I am here.')],
        ['Allí.', l('Там. Короткий ответ.', 'There. A short answer.')],
        ['La universidad está allí.', l('Университет там.', 'The university is there.')],
        ['Está allí.', l('Это / он / она находится там.', 'It / he / she is there.')],
      ],
    },
    {
      title: 'Yo + verbo + información',
      body: l('В испанском форма глагола уже показывает, кто действует, поэтому yo обычно можно опустить. Главное: в готовой фразе нужен не инфинитив trabajar, а форма trabajo; не volver, а vuelvo.', 'In Spanish, the verb form already shows who acts, so yo is usually optional. A complete sentence needs trabajo rather than the infinitive trabajar, and vuelvo rather than volver.'),
      rule: '(Yo) + trabajo / vuelvo / tengo + información',
      examples: [
        ['Ahora trabajo.', l('Сейчас я работаю.', 'Now I work.')],
        ['Ahora estudio.', l('Сейчас я учусь.', 'Now I study.')],
        ['Ahora no.', l('Сейчас нет.', 'Not now.')],
        ['(Yo) trabajo mucho.', l('Я много работаю. Yo можно не говорить.', 'I work a lot. You can omit yo.')],
        ['Trabajo en Barcelona.', l('Я работаю в Барселоне.', 'I work in Barcelona.')],
        ['(Yo) vuelvo ahora.', l('Я возвращаюсь сейчас.', 'I am coming back now.')],
        ['(Yo) vuelvo a casa.', l('Я возвращаюсь домой.', 'I return home.')],
        ['(Yo) tengo tiempo.', l('У меня есть время.', 'I have time.')],
        ['Mucho tiempo.', l('Много времени: tiempo — мужского рода.', 'A lot of time: tiempo is masculine.')],
        ['Muchas gracias.', l('Большое спасибо: gracias — множественное число женского рода.', 'Thank you very much: gracias is feminine plural.')],
      ],
    },
    {
      title: l('Соединяй мысли через y', 'Connect ideas with y'),
      body: l('Y — это союз, то есть слово, которое соединяет равные части. В испанском y произносится как русское «и». Поэтому Хосе сказал, что y и буква i звучат одинаково.', 'Y is a conjunction: a word that connects equal parts. As a conjunction, Spanish y is pronounced like the Spanish vowel i. That is why José said y and i sound the same.'),
      rule: 'idea 1 + y + idea 2',
      examples: [
        ['Trabajo y estudio.', l('Я работаю и учусь.', 'I work and study.')],
        ['Barcelona y Madrid.', l('Барселона и Мадрид.', 'Barcelona and Madrid.')],
        ['Español e inglés.', l('Перед звуком i союз y обычно меняется на e.', 'Before an i sound, the conjunction y usually changes to e.')],
        ['«Y» es una conjunción.', l('Y — это союз.', 'Y is a conjunction.')],
      ],
    },
    {
      title: l('Два важных звука из урока', 'Two important sounds from the lesson'),
      body: l('В современном испанском b и v произносятся одинаково: не пытайся делать английский звук v. В начале фразы звук плотнее, между гласными — мягче. А y как союз звучит просто как [i].', 'In modern Spanish, b and v are pronounced alike: do not force an English v sound. The sound is firmer at the start of a phrase and softer between vowels. As a conjunction, y is simply pronounced [i].'),
      rule: 'b ≈ v · y = [i]',
      examples: [
        ['Barcelona.', l('Начальный b произносится плотнее.', 'The initial b is pronounced more firmly.')],
        ['Volver.', l('V здесь не английское «в» — это тот же испанский звук, что b.', 'This v is not an English v; it represents the same Spanish sound as b.')],
        ['Vuelvo ahora.', l('Повтори целиком, не отделяя vuelvo от ahora.', 'Repeat the whole phrase without separating vuelvo from ahora.')],
        ['Trabajo y estudio.', l('Y произнеси коротко: [i].', 'Pronounce y briefly: [i].')],
      ],
    },
  ],
  words: [
    { es: 'sí', en: l('да', 'yes'), example: 'Sí, entiendo.' },
    { es: 'no', en: l('нет / не', 'no / not'), example: 'No tengo tiempo.' },
    { es: 'aquí', en: l('здесь', 'here'), example: 'Estoy aquí.' },
    { es: 'allí', en: l('там', 'there'), example: 'La universidad está allí.' },
    { es: 'ahora', en: l('сейчас', 'now'), example: 'Ahora trabajo.' },
    { es: 'el tiempo', en: l('время', 'time'), example: 'Ahora tengo tiempo.' },
    { es: 'trabajar', en: l('работать', 'to work'), example: 'Trabajo en Barcelona.' },
    { es: 'mucho', en: l('много', 'a lot / much'), example: 'Trabajo mucho.' },
    { es: 'y', en: l('и', 'and'), example: 'Trabajo y estudio.' },
    { es: 'volver', en: l('возвращаться', 'to return / come back'), example: 'Vuelvo a casa.' },
    { es: 'la conjunción', en: l('союз', 'conjunction'), example: '«Y» es una conjunción.' },
  ],
  quiz: [
    { prompt: l('Выбери естественный вариант: «Да, я понимаю».', 'Choose the natural Spanish for “Yes, I understand.”'), options: ['Si, entiendo.', 'Sí, entiendo.', 'Sí, entender.'], answer: 'Sí, entiendo.', explanation: l('Sí = «да» всегда пишется с ударением. Entiendo — готовая форма глагола.', 'Sí meaning “yes” always has a written accent. Entiendo is the conjugated verb form.') },
    { prompt: l('Сделай фразу отрицательной: «Tengo tiempo».', 'Make the sentence negative: “Tengo tiempo.”'), options: ['Tengo no tiempo.', 'No tengo tiempo.', 'No tiempo tengo.'], answer: 'No tengo tiempo.', explanation: l('No ставится прямо перед спрягаемым глаголом: no + tengo.', 'No goes directly before the conjugated verb: no + tengo.') },
    { prompt: l('Что означает «Estoy aquí»?', 'What does “Estoy aquí” mean?'), options: [l('Я здесь.', 'I am here.'), l('Я работаю здесь.', 'I work here.'), l('Я там.', 'I am there.')], answer: l('Я здесь.', 'I am here.'), explanation: l('Aquí = здесь; allí = там.', 'Aquí = here; allí = there.') },
    { prompt: l('Закончи фразу: «La universidad está ___».', 'Complete: “La universidad está ___.”'), options: ['allí', 'mucho', 'y'], answer: 'allí', explanation: l('Allí указывает на место, которое не рядом с говорящим.', 'Allí points to a place away from the speaker.') },
    { prompt: l('Какая фраза означает «Сейчас я работаю»?', 'Which sentence means “Now I work”?'), options: ['Ahora trabajo.', 'Ahora trabajar.', 'Trabajo allí ahora no.'], answer: 'Ahora trabajo.', explanation: l('После ahora нужна готовая форма trabajo, не инфинитив trabajar.', 'After ahora, use the conjugated form trabajo, not the infinitive trabajar.') },
    { prompt: l('Выбери форму: «Yo ___ mucho».', 'Choose the correct form: “Yo ___ mucho.”'), options: ['trabajar', 'trabajo', 'trabajas'], answer: 'trabajo', explanation: l('Для yo: trabajo. Само yo можно опустить.', 'With yo, use trabajo. You can omit yo itself.') },
    { prompt: l('Выбери форму: «Ahora ___ a casa».', 'Choose the correct form: “Ahora ___ a casa.”'), options: ['volver', 'vuelvo', 'vuelve'], answer: 'vuelvo', explanation: l('Для yo глагол volver меняется: vuelvo.', 'With yo, volver changes to vuelvo.') },
    { prompt: l('Чем является y во фразе «Trabajo y estudio»?', 'What is y in “Trabajo y estudio”?'), options: [l('Глаголом', 'A verb'), l('Союзом', 'A conjunction'), l('Словом места', 'A place word')], answer: l('Союзом', 'A conjunction'), explanation: l('Y соединяет две части и означает «и».', 'Y connects two parts and means “and”.') },
    { prompt: l('Как произносится союз y?', 'How is the conjunction y pronounced?'), options: [l('Как испанская i', 'Like Spanish i'), l('Как английское why', 'Like English why'), l('Как испанская u', 'Like Spanish u')], answer: l('Как испанская i', 'Like Spanish i'), explanation: l('Как союз y произносится [i].', 'As a conjunction, y is pronounced [i].') },
    { prompt: l('Какое утверждение о современном испанском верно?', 'Which pronunciation idea is correct in modern Spanish?'), options: [l('b и v произносятся одинаково', 'b and v are pronounced alike'), l('v обязательно звучит как английская v', 'v must sound like English v'), l('b всегда немая', 'b is always silent')], answer: l('b и v произносятся одинаково', 'b and v are pronounced alike'), explanation: l('B и v обозначают один и тот же набор испанских звуков.', 'B and v represent the same set of Spanish sounds.') },
    { prompt: l('Выбери естественную фразу.', 'Choose the natural sentence.'), options: ['Yo trabajar aquí.', 'Trabajo aquí.', 'Yo aquí trabajar.'], answer: 'Trabajo aquí.', explanation: l('Форма trabajo уже содержит смысл «я работаю».', 'The form trabajo already carries the meaning “I work”.') },
    { prompt: l('Закончи фразу: «Trabajo ___».', 'Complete: “Trabajo ___.”'), options: ['mucho', 'mucha', 'muchos'], answer: 'mucho', explanation: l('Здесь mucho — наречие «много»: trabajo mucho.', 'Here mucho is the adverb “a lot”: trabajo mucho.') },
  ],
  builder: [
    { translation: l('Да, я понимаю.', 'Yes, I understand.'), answer: ['Sí,', 'entiendo.'] },
    { translation: l('Нет, я не понимаю.', 'No, I do not understand.'), answer: ['No,', 'no', 'entiendo.'] },
    { translation: l('Я здесь.', 'I am here.'), answer: ['Estoy', 'aquí.'] },
    { translation: l('Университет там.', 'The university is there.'), answer: ['La', 'universidad', 'está', 'allí.'] },
    { translation: l('Сейчас я работаю.', 'Now I work.'), answer: ['Ahora', 'trabajo.'] },
    { translation: l('Я много работаю.', 'I work a lot.'), answer: ['Trabajo', 'mucho.'] },
    { translation: l('Я работаю здесь.', 'I work here.'), answer: ['Trabajo', 'aquí.'] },
    { translation: l('Я работаю и учусь.', 'I work and study.'), answer: ['Trabajo', 'y', 'estudio.'] },
    { translation: l('Я возвращаюсь завтра.', 'I return tomorrow.'), answer: ['Vuelvo', 'mañana.'] },
    { translation: l('Сейчас я возвращаюсь домой.', 'Now I return home.'), answer: ['Ahora', 'vuelvo', 'a', 'casa.'] },
  ],
  compose: [
    { prompt: l('Напиши по-испански: «Да, я понимаю».', 'Write in Spanish: “Yes, I understand.”'), hint: 'sí · entender → entiendo', accepted: ['Sí, entiendo.'], answer: 'Sí, entiendo.', explanation: l('Sí пишется с ударением; форма entiendo уже передаёт «я понимаю».', 'Sí takes a written accent; entiendo already expresses “I understand”.') },
    { prompt: l('Напиши: «Сейчас у меня нет времени».', 'Write: “I do not have time now.”'), hint: 'ahora · no + tengo · tiempo', accepted: ['Ahora no tengo tiempo.', 'No tengo tiempo ahora.'], answer: 'Ahora no tengo tiempo.', explanation: l('No стоит перед глаголом tengo. Ahora может быть в начале или в конце.', 'No goes before tengo. Ahora can go at the beginning or the end.') },
    { prompt: l('Напиши: «Я работаю здесь».', 'Write: “I work here.”'), hint: 'trabajar → trabajo · aquí', accepted: ['Trabajo aquí.', 'Yo trabajo aquí.'], answer: 'Trabajo aquí.', explanation: l('Нужна форма trabajo. Местоимение yo можно не писать.', 'Use trabajo. The pronoun yo is optional.') },
    { prompt: l('Напиши: «Сейчас я много работаю».', 'Write: “I work a lot now.”'), hint: 'ahora · trabajo · mucho', accepted: ['Ahora trabajo mucho.', 'Trabajo mucho ahora.', 'Ahora yo trabajo mucho.', 'Yo trabajo mucho ahora.'], answer: 'Ahora trabajo mucho.', explanation: l('Mucho после trabajo означает «много». Ahora можно переставить в конец.', 'Mucho after trabajo means “a lot”. Ahora can move to the end.') },
    { prompt: l('Соедини две мысли: «Я работаю и учусь».', 'Connect two ideas: “I work and study.”'), hint: 'trabajo · y · estudio', accepted: ['Trabajo y estudio.', 'Yo trabajo y estudio.'], answer: 'Trabajo y estudio.', explanation: l('Y соединяет два глагола с одним действующим лицом.', 'Y connects two verbs with the same subject.') },
    { prompt: l('Напиши: «Университет там».', 'Write: “The university is there.”'), hint: 'la universidad · está · allí', accepted: ['La universidad está allí.', 'Allí está la universidad.'], answer: 'La universidad está allí.', explanation: l('Для местоположения используй está; allí означает «там».', 'Use está for location; allí means “there”.') },
    { prompt: l('Напиши: «Я возвращаюсь сейчас».', 'Write: “I am coming back now.”'), hint: 'volver → vuelvo · ahora', accepted: ['Vuelvo ahora.', 'Ahora vuelvo.', 'Yo vuelvo ahora.', 'Ahora yo vuelvo.'], answer: 'Vuelvo ahora.', explanation: l('Для yo: vuelvo, не volver. Ahora свободно перемещается.', 'With yo, use vuelvo, not volver. Ahora can move freely.') },
    { prompt: l('Напиши: «Я возвращаюсь домой».', 'Write: “I return home.”'), hint: 'vuelvo · a casa', accepted: ['Vuelvo a casa.', 'Yo vuelvo a casa.'], answer: 'Vuelvo a casa.', explanation: l('Направление выражается через a: vuelvo a casa.', 'Use a for direction: vuelvo a casa.') },
    { prompt: l('Напиши: «Да, сейчас у меня есть время».', 'Write: “Yes, I have time now.”'), hint: 'sí · ahora · tengo tiempo', accepted: ['Sí, ahora tengo tiempo.', 'Ahora sí tengo tiempo.', 'Sí, tengo tiempo ahora.'], answer: 'Sí, ahora tengo tiempo.', explanation: l('Все три порядка естественны. Не забудь ударение в sí.', 'All three word orders are natural. Remember the accent in sí.') },
    { prompt: l('Финал: «Нет, сейчас я много работаю и у меня нет времени».', 'Final: “No, I work a lot now and I do not have time.”'), hint: 'no · ahora · trabajo mucho · y · no tengo tiempo', accepted: ['No, ahora trabajo mucho y no tengo tiempo.', 'Ahora trabajo mucho y no tengo tiempo.', 'No, trabajo mucho ahora y no tengo tiempo.'], answer: 'No, ahora trabajo mucho y no tengo tiempo.', explanation: l('Ты собрал две полноценные мысли через y. Во второй части no снова ставится перед tengo.', 'You connected two complete ideas with y. In the second part, no goes before tengo again.') },
  ],
}
