export const joseSentenceLesson = {
  id: 'jose-sentence-foundations',
  featured: true,
  title: 'Build your first Spanish sentences',
  eyebrow: 'Lesson with José · A0',
  description: 'Turn Sí, no, aquí, ahora and everyday verbs into sentences you can actually create yourself.',
  accent: 'coral',
  minutes: 32,
  icon: 'MessagesSquare',
  guideKicker: 'JOSÉ RECAP · FROM WORDS TO SENTENCES',
  guide: [
    {
      title: 'Сначала — короткие ответы',
      body: 'Sí и no уже могут быть полным ответом. Перед глаголом no делает всё предложение отрицательным. У sí есть ударение: без него si означает «если».',
      rule: 'Sí = да · No + verbo = не делаю',
      examples: [
        ['Sí, entiendo.', 'Да, я понимаю.'],
        ['Sí, quiero.', 'Да, я хочу.'],
        ['Sí, tengo tiempo.', 'Да, у меня есть время.'],
        ['No entiendo.', 'Я не понимаю.'],
        ['No tengo tiempo.', 'У меня нет времени.'],
        ['No puedo.', 'Я не могу.'],
      ],
    },
    {
      title: 'Добавь место и время',
      body: 'Aquí — «здесь», allí — «там», ahora — «сейчас». Эти слова можно ставить в начало или ближе к концу. Для начала используй устойчивую схему: время + действие + место.',
      rule: 'Ahora + verbo + aquí / allí',
      examples: [
        ['Aquí.', 'Здесь. Этого достаточно как короткого ответа.'],
        ['Aquí está mi casa.', 'Вот здесь мой дом.'],
        ['Estoy aquí.', 'Я здесь.'],
        ['Allí.', 'Там. Короткий ответ.'],
        ['La universidad está allí.', 'Университет там.'],
        ['Está allí.', 'Это / он / она находится там.'],
      ],
    },
    {
      title: 'Yo + verbo + información',
      body: 'В испанском форма глагола уже показывает, кто действует, поэтому yo обычно можно опустить. Главное: в готовой фразе нужен не инфинитив trabajar, а форма trabajo; не volver, а vuelvo.',
      rule: '(Yo) + trabajo / vuelvo / tengo + información',
      examples: [
        ['Ahora trabajo.', 'Сейчас я работаю.'],
        ['Ahora estudio.', 'Сейчас я учусь.'],
        ['Ahora no.', 'Сейчас нет.'],
        ['(Yo) trabajo mucho.', 'Я много работаю. Yo можно не говорить.'],
        ['Trabajo en Barcelona.', 'Я работаю в Барселоне.'],
        ['(Yo) vuelvo ahora.', 'Я возвращаюсь сейчас.'],
        ['(Yo) vuelvo a casa.', 'Я возвращаюсь домой.'],
        ['(Yo) tengo tiempo.', 'У меня есть время.'],
        ['Mucho tiempo.', 'Много времени: tiempo — мужского рода.'],
        ['Muchas gracias.', 'Большое спасибо: gracias — множественное число женского рода.'],
      ],
    },
    {
      title: 'Соединяй мысли через y',
      body: 'Y — это союз, то есть слово, которое соединяет равные части. В испанском y произносится как русское «и». Поэтому José сказал, что y и буква i звучат одинаково.',
      rule: 'idea 1 + y + idea 2',
      examples: [
        ['Trabajo y estudio.', 'Я работаю и учусь.'],
        ['Barcelona y Madrid.', 'Барселона и Мадрид.'],
        ['Español e inglés.', 'Перед звуком i союз y обычно меняется на e.'],
        ['«Y» es una conjunción.', 'Y — это союз.'],
      ],
    },
    {
      title: 'Два важных звука из урока',
      body: 'В современном испанском b и v произносятся одинаково: не пытайся делать английский звук v. В начале фразы звук плотнее, между гласными — мягче. А y как союз звучит просто как [i].',
      rule: 'b ≈ v · y = [i]',
      examples: [
        ['Barcelona.', 'Начальный b произносится плотнее.'],
        ['Volver.', 'V здесь не английское «в» — это тот же испанский звук, что b.'],
        ['Vuelvo ahora.', 'Повтори целиком, не отделяя vuelvo от ahora.'],
        ['Trabajo y estudio.', 'Y произнеси коротко: [i].'],
      ],
    },
  ],
  words: [
    { es: 'sí', en: 'yes', example: 'Sí, entiendo.' },
    { es: 'no', en: 'no / not', example: 'No tengo tiempo.' },
    { es: 'aquí', en: 'here', example: 'Estoy aquí.' },
    { es: 'allí', en: 'there', example: 'La universidad está allí.' },
    { es: 'ahora', en: 'now', example: 'Ahora trabajo.' },
    { es: 'el tiempo', en: 'time', example: 'Ahora tengo tiempo.' },
    { es: 'trabajar', en: 'to work', example: 'Trabajo en Barcelona.' },
    { es: 'mucho', en: 'a lot / much', example: 'Trabajo mucho.' },
    { es: 'y', en: 'and', example: 'Trabajo y estudio.' },
    { es: 'volver', en: 'to return / come back', example: 'Vuelvo a casa.' },
    { es: 'la conjunción', en: 'conjunction', example: '«Y» es una conjunción.' },
  ],
  quiz: [
    { prompt: 'Choose the natural Spanish for “Yes, I understand.”', options: ['Si, entiendo.', 'Sí, entiendo.', 'Sí, entender.'], answer: 'Sí, entiendo.', explanation: 'Sí = «да» всегда пишется с ударением. Entiendo — готовая форма глагола.' },
    { prompt: 'Make the sentence negative: “Tengo tiempo.”', options: ['Tengo no tiempo.', 'No tengo tiempo.', 'No tiempo tengo.'], answer: 'No tengo tiempo.', explanation: 'No ставится прямо перед спрягаемым глаголом: no + tengo.' },
    { prompt: 'What does “Estoy aquí” mean?', options: ['I am here.', 'I work here.', 'I am there.'], answer: 'I am here.', explanation: 'Aquí = здесь; allí = там.' },
    { prompt: 'Complete: “La universidad está ___.”', options: ['allí', 'mucho', 'y'], answer: 'allí', explanation: 'Allí указывает на место, которое не рядом с говорящим.' },
    { prompt: 'Which sentence means “Now I work”?', options: ['Ahora trabajo.', 'Ahora trabajar.', 'Trabajo allí ahora no.'], answer: 'Ahora trabajo.', explanation: 'После ahora нужна готовая форма trabajo, не инфинитив trabajar.' },
    { prompt: 'Choose the correct form: “Yo ___ mucho.”', options: ['trabajar', 'trabajo', 'trabajas'], answer: 'trabajo', explanation: 'Для yo: trabajo. Само yo можно опустить.' },
    { prompt: 'Choose the correct form: “Ahora ___ a casa.”', options: ['volver', 'vuelvo', 'vuelve'], answer: 'vuelvo', explanation: 'Для yo глагол volver меняется: vuelvo.' },
    { prompt: 'What is y in “Trabajo y estudio”?', options: ['A verb', 'A conjunction', 'A place word'], answer: 'A conjunction', explanation: 'Y соединяет две части и означает «и».' },
    { prompt: 'How is the conjunction y pronounced?', options: ['Like Spanish i', 'Like English why', 'Like Spanish u'], answer: 'Like Spanish i', explanation: 'Как союз y произносится [i].' },
    { prompt: 'Which pronunciation idea is correct in modern Spanish?', options: ['b and v are pronounced alike', 'v must sound like English v', 'b is always silent'], answer: 'b and v are pronounced alike', explanation: 'B и v обозначают один и тот же набор испанских звуков.' },
    { prompt: 'Choose the natural sentence.', options: ['Yo trabajar aquí.', 'Trabajo aquí.', 'Yo aquí trabajar.'], answer: 'Trabajo aquí.', explanation: 'Форма trabajo уже содержит смысл «я работаю».' },
    { prompt: 'Complete: “Trabajo ___.”', options: ['mucho', 'mucha', 'muchos'], answer: 'mucho', explanation: 'Здесь mucho — наречие «много»: trabajo mucho.' },
  ],
  builder: [
    { translation: 'Yes, I understand.', answer: ['Sí,', 'entiendo.'] },
    { translation: 'No, I don’t understand.', answer: ['No,', 'no', 'entiendo.'] },
    { translation: 'I am here.', answer: ['Estoy', 'aquí.'] },
    { translation: 'The university is there.', answer: ['La', 'universidad', 'está', 'allí.'] },
    { translation: 'Now I work.', answer: ['Ahora', 'trabajo.'] },
    { translation: 'I work a lot.', answer: ['Trabajo', 'mucho.'] },
    { translation: 'I work here.', answer: ['Trabajo', 'aquí.'] },
    { translation: 'I work and study.', answer: ['Trabajo', 'y', 'estudio.'] },
    { translation: 'I return tomorrow.', answer: ['Vuelvo', 'mañana.'] },
    { translation: 'Now I return home.', answer: ['Ahora', 'vuelvo', 'a', 'casa.'] },
  ],
  compose: [
    {
      prompt: 'Напиши по-испански: «Да, я понимаю».',
      hint: 'sí · entender → entiendo',
      accepted: ['Sí, entiendo.'],
      answer: 'Sí, entiendo.',
      explanation: 'Sí пишется с ударением; форма entiendo уже передаёт «я понимаю».',
    },
    {
      prompt: 'Напиши: «Сейчас у меня нет времени».',
      hint: 'ahora · no + tengo · tiempo',
      accepted: ['Ahora no tengo tiempo.', 'No tengo tiempo ahora.'],
      answer: 'Ahora no tengo tiempo.',
      explanation: 'No стоит перед глаголом tengo. Ahora может быть в начале или в конце.',
    },
    {
      prompt: 'Напиши: «Я работаю здесь».',
      hint: 'trabajar → trabajo · aquí',
      accepted: ['Trabajo aquí.', 'Yo trabajo aquí.'],
      answer: 'Trabajo aquí.',
      explanation: 'Нужна форма trabajo. Местоимение yo можно не писать.',
    },
    {
      prompt: 'Напиши: «Сейчас я много работаю».',
      hint: 'ahora · trabajo · mucho',
      accepted: ['Ahora trabajo mucho.', 'Trabajo mucho ahora.', 'Ahora yo trabajo mucho.', 'Yo trabajo mucho ahora.'],
      answer: 'Ahora trabajo mucho.',
      explanation: 'Mucho после trabajo означает «много». Ahora можно переставить в конец.',
    },
    {
      prompt: 'Соедини две мысли: «Я работаю и учусь».',
      hint: 'trabajo · y · estudio',
      accepted: ['Trabajo y estudio.', 'Yo trabajo y estudio.'],
      answer: 'Trabajo y estudio.',
      explanation: 'Y соединяет два глагола с одним действующим лицом.',
    },
    {
      prompt: 'Напиши: «Университет там».',
      hint: 'la universidad · está · allí',
      accepted: ['La universidad está allí.', 'Allí está la universidad.'],
      answer: 'La universidad está allí.',
      explanation: 'Для местоположения используй está; allí означает «там».',
    },
    {
      prompt: 'Напиши: «Я возвращаюсь сейчас».',
      hint: 'volver → vuelvo · ahora',
      accepted: ['Vuelvo ahora.', 'Ahora vuelvo.', 'Yo vuelvo ahora.', 'Ahora yo vuelvo.'],
      answer: 'Vuelvo ahora.',
      explanation: 'Для yo: vuelvo, не volver. Ahora свободно перемещается.',
    },
    {
      prompt: 'Напиши: «Я возвращаюсь домой».',
      hint: 'vuelvo · a casa',
      accepted: ['Vuelvo a casa.', 'Yo vuelvo a casa.'],
      answer: 'Vuelvo a casa.',
      explanation: 'Направление выражается через a: vuelvo a casa.',
    },
    {
      prompt: 'Напиши: «Да, сейчас у меня есть время».',
      hint: 'sí · ahora · tengo tiempo',
      accepted: ['Sí, ahora tengo tiempo.', 'Ahora sí tengo tiempo.', 'Sí, tengo tiempo ahora.'],
      answer: 'Sí, ahora tengo tiempo.',
      explanation: 'Все три порядка естественны. Не забудь ударение в sí.',
    },
    {
      prompt: 'Финал: «Нет, сейчас я много работаю и у меня нет времени».',
      hint: 'no · ahora · trabajo mucho · y · no tengo tiempo',
      accepted: ['No, ahora trabajo mucho y no tengo tiempo.', 'Ahora trabajo mucho y no tengo tiempo.', 'No, trabajo mucho ahora y no tengo tiempo.'],
      answer: 'No, ahora trabajo mucho y no tengo tiempo.',
      explanation: 'Ты собрал две полноценные мысли через y. Во второй части no снова ставится перед tengo.',
    },
  ],
}
