const l = (ru, en) => ({ ru, en })

const people = ['yo', 'tú', 'él / ella', 'nosotros', 'vosotros', 'ellos / ellas']

export const joseLearningChangesLesson = {
  id: 'jose-learning-changes-communication',
  bilingual: true,
  featured: true,
  title: l('Учиться, меняться и говорить', 'Learn, change and communicate'),
  eyebrow: l('Четвёртый урок с Хосе · A0–A1', 'Fourth lesson with José · A0–A1'),
  description: l('Освой настоящее время, говори об учёбе, переменах, людях и ежедневных действиях — затем напиши пять собственных фраз.', 'Master the present tense, talk about learning, change, people and daily actions, then write five sentences of your own.'),
  accent: 'coral', minutes: 48, icon: 'Brain',
  guideKicker: l('УРОК С ХОСЕ · ГЛАГОЛЫ И ИЗМЕНЕНИЯ', 'LESSON WITH JOSÉ · VERBS AND CHANGE'),
  modeCopy: {
    guide: { label: l('Спряжение без тумана', 'Conjugation without fog'), description: l('Разбери окончания -ar, -er, -ir, исключения и все примеры занятия.', 'Understand -ar, -er and -ir endings, exceptions and every lesson example.') },
    cards: { label: l('Карточки слов и форм', 'Words and forms deck'), description: l('Запомни значение, форму yo и живой пример для каждого глагола.', 'Remember the meaning, yo form and a useful example for each verb.') },
    match: { label: l('Сопоставление 4×4', '4×4 Match'), description: l('Соедини глаголы, формы и выражения с точными значениями.', 'Match verbs, forms and expressions with their precise meanings.') },
    quiz: { label: l('Проверка форм и смысла', 'Form and meaning check'), description: l('Выбери нужное окончание, предлог, ударение и естественную конструкцию.', 'Choose the right ending, preposition, accent and natural construction.') },
    builder: { label: l('Конструктор предложений', 'Sentence builder'), description: l('Собери ключевые фразы урока и исправленные варианты своих примеров.', 'Build the key lesson sentences and corrected versions of your examples.') },
    compose: { label: l('Напиши по смыслу', 'Write from meaning'), description: l('Восстанови фразу с нуля, без готового порядка слов.', 'Produce the sentence from scratch without a ready-made word order.') },
    create: { label: l('Домашнее задание: 5 фраз', 'Homework: 5 sentences'), description: l('Напиши пять собственных правильных фраз с пятью разными глаголами урока.', 'Write five correct sentences of your own with five different lesson verbs.') },
  },
  ui: {
    backToPlayground: l('Назад к урокам', 'Back to playground'), mastery: l('освоено', 'mastery'), modes: l('этапов', 'stages'), chooseMode: l('ЭТАПЫ УРОКА', 'LESSON STAGES'), practiceQuestion: l('От спряжения к своим пяти фразам', 'From conjugation to five sentences of your own'), completed: l('Пройдено', 'Completed'), done: l('Готово', 'Done'), start: l('Начать', 'Start'), minutesShort: l('мин', 'min'), wordsLabel: l('слов и форм', 'words and forms'), phraseOfDay: l('Новый урок Хосе', 'New lesson with José'),
    back: l('Назад', 'Back'), exit: l('Выйти', 'Exit'), savedPhrases: l('Сохранённые фразы', 'Saved phrases'), cardTitle: l('Слово и контекст', 'Word & Context'), spanish: l('Испанский', 'Spanish'), targetLanguage: l('Русский', 'English'), meaningLabel: l('ЗНАЧЕНИЕ', 'MEANING'), tapToSpanish: l('Нажми, чтобы увидеть испанский', 'Tap to see Spanish'), playPronunciation: l('Прослушать произношение', 'Play Spanish pronunciation'), listenTitle: l('Слушай форму и повторяй пример', 'Listen to the form and repeat the example'), listenBody: l('Сначала произнеси форму отдельно, затем всю фразу без паузы.', 'Say the form first, then repeat the whole sentence without a pause.'), gotIt: l('Запомнил', 'Got it'), finish: l('Завершить', 'Finish'),
    previous: l('Назад', 'Previous'), startPractising: l('Перейти к практике', 'Start practising'), understand: l('Понятно', 'I understand'),
    matchKicker: l('СОПОСТАВЛЕНИЕ 4 × 4', '4 × 4 MATCH'), connectPairs: l('Соедини пары', 'Connect the pairs'), round: l('Раунд', 'Round'), of: l('из', 'of'), matched: l('готово', 'matched'), matchCorrect: l('¡Sí! Пара совпала.', '¡Sí! That pair matches.'), matchWrong: l('Не эта пара — попробуй ещё.', 'Not this pair — try again.'), finishMatching: l('Завершить сопоставление', 'Finish matching'), nextFour: l('Следующие четыре', 'Next four'),
    quizKicker: l('ФОРМА, ПРЕДЛОГ И СМЫСЛ', 'FORM, PREPOSITION AND MEANING'), hardOne: l('Сложный момент?', 'Hard one?'), correctTitle: '¡Muy bien!', wrongTitle: l('Нужно ещё немного.', 'Not quite yet.'), naturalAnswer: l('Это правильный и естественный вариант.', 'That is the correct natural option.'), answerIs: l('Ответ:', 'The answer is'), sayIt: l('Произнеси фразу вслух.', 'Say the sentence aloud.'), next: l('Дальше', 'Next'),
    sentenceKicker: l('СОБЕРИ ПРЕДЛОЖЕНИЕ', 'BUILD THE SENTENCE'), buildPlaceholder: l('Собери предложение здесь…', 'Build the sentence here…'), perfect: '¡Perfecto!', wordOrder: l('Почти — проверь форму, предлог, ударение и порядок.', 'Almost — check the form, preposition, accent and order.'), checkSentence: l('Проверить предложение', 'Check sentence'),
    composerKicker: l('НАПИШИ ПО СМЫСЛУ · БЕЗ БАНКА СЛОВ', 'WRITE FROM MEANING · NO WORD BANK'), yourPhrase: l('Твоя фраза', 'Your sentence'), composePlaceholder: l('Напиши по-испански…', 'Write in Spanish…'), hideHint: l('Скрыть опору', 'Hide hint'), showHint: l('Нужна опора?', 'Need a hint?'), words: l('слов', 'words'), checkPhrase: l('Проверить предложение', 'Check sentence'), finishLesson: l('Завершить этап', 'Finish stage'), nextPhrase: l('Следующее предложение', 'Next sentence'), accentTitle: l('Смысл верный — поправь ударение.', 'Meaning is right — fix the accent.'), writeIt: l('Напиши так:', 'Write it like this:'), verbFormTitle: l('Нужна личная форма.', 'Use a personal verb form.'), workFormMessage: l('Выбери форму, которая согласуется с тем, кто действует.', 'Choose the form that agrees with the person acting.'), infinitiveTitle: l('Измени инфинитив.', 'Change the infinitive.'), returnFormMessage: l('В самостоятельной фразе нужен спрягаемый глагол.', 'A standalone sentence needs a conjugated verb.'), noPositionTitle: l('Проверь место отрицания.', 'Check the position of the negative.'), naturalVariant: l('Естественный вариант:', 'A natural version:'), notYetTitle: l('Пока не сходится.', 'Not quite yet.'), compareVariant: l('Сравни с вариантом:', 'Compare with this version:'),
    creationKicker: l('ДОМАШНЕЕ ЗАДАНИЕ · 5 РАЗНЫХ ГЛАГОЛОВ', 'HOMEWORK · 5 DIFFERENT VERBS'), wordBank: l('Глаголы перед глазами', 'Verbs in front of you'), usefulForms: l('Полезные формы и блоки:', 'Useful forms and chunks:'), sentenceNumber: l('Предложение', 'Sentence'), freePlaceholder: l('Например: Quiero aprender más.', 'For example: Quiero aprender más.'), checkMySentence: l('Проверить моё предложение', 'Check my sentence'), correctDuplicate: l('Правильно, но уже засчитано', 'Correct, but already counted'), correctNotCounted: l('Правильно, но нужен новый глагол', 'Correct, but use a new verb'), createdCorrect: l('Правильно — предложение засчитано', 'Correct — sentence counted'), createdWrong: l('Нужно исправить', 'This needs a change'), yourCorrectSentences: l('Твои правильные предложения', 'Your correct sentences'), removeSentence: l('Удалить предложение', 'Remove sentence'), creationCompleteKicker: l('ТВОИ 5 ФРАЗ · 5 РАЗНЫХ ГЛАГОЛОВ', 'YOUR 5 SENTENCES · 5 DIFFERENT VERBS'), creationCompleteTitle: l('Домашнее задание готово.', 'Your homework is ready.'), creationCompleteBody: l('Ниже — пять твоих собственных правильных предложений. В каждом засчитан новый глагол из урока: их можно перечитать и отправить Хосе.', 'Below are five correct sentences of your own. Each counted sentence introduces a new lesson verb, ready to review or send to José.'), newSet: l('Написать новый набор', 'Write a new set'), finishAndSave: l('Завершить и сохранить', 'Finish and save'),
  },
  guide: [
    {
      title: l('Настоящее время: -ar, -er, -ir', 'Present tense: -ar, -er, -ir'),
      body: l('У правильных глаголов убери -ar, -er или -ir и добавь окончание нужного лица. В таблице Хосе не было vosotros; здесь оно добавлено, потому что в Испании эту форму используют постоянно. Это основа, но empezar, conocer, decir и hacer имеют изменения, которые разберём дальше.', 'With regular verbs, remove -ar, -er or -ir and add the ending for the person. José’s chart omitted vosotros; it is included here because it is used constantly in Spain. This is the base pattern, but empezar, conocer, decir and hacer have changes covered below.'),
      rule: l('основа + окончание лица', 'stem + person ending'),
      examples: [
        ['Trabajo · aprendes · abrimos', l('Окончание сразу показывает лицо.', 'The ending already shows the person.')],
        ['Yo trabajo. / Trabajo.', l('Оба варианта правильны; yo обычно можно опустить.', 'Both are correct; yo is usually optional.')],
      ],
      conjugation: {
        title: l('Окончания правильных глаголов', 'Regular verb endings'),
        endings: [
          { group: '-AR', rule: 'trabajar', tone: 'blue', forms: people.map((person, index) => [person, ['-o', '-as', '-a', '-amos', '-áis', '-an'][index]]) },
          { group: '-ER', rule: 'aprender', tone: 'green', forms: people.map((person, index) => [person, ['-o', '-es', '-e', '-emos', '-éis', '-en'][index]]) },
          { group: '-IR', rule: 'abrir', tone: 'purple', forms: people.map((person, index) => [person, ['-o', '-es', '-e', '-imos', '-ís', '-en'][index]]) },
        ],
        examplesTitle: l('Три полных примера', 'Three complete examples'),
        examples: [
          { verb: 'TRABAJAR', group: '-AR', tone: 'blue', forms: people.map((person, index) => [person, ['trabajo', 'trabajas', 'trabaja', 'trabajamos', 'trabajáis', 'trabajan'][index]]) },
          { verb: 'APRENDER', group: '-ER', tone: 'green', forms: people.map((person, index) => [person, ['aprendo', 'aprendes', 'aprende', 'aprendemos', 'aprendéis', 'aprenden'][index]]) },
          { verb: 'ABRIR', group: '-IR', tone: 'purple', forms: people.map((person, index) => [person, ['abro', 'abres', 'abre', 'abrimos', 'abrís', 'abren'][index]]) },
        ],
        reminder: l('У правильного глагола основа почти всегда сохраняется; меняется окончание. Неправильные и глаголы с чередованием нужно запоминать отдельно.', 'A regular verb normally keeps its stem and changes the ending. Irregular and stem-changing verbs must be learned separately.'),
      },
    },
    {
      title: l('Aprender, empezar и cambiar', 'Aprender, empezar and cambiar'),
      body: l('Aprender — правильный -er глагол. Empezar меняет e→ie в ударных формах: empiezo, empiezas, empieza, empiezan, но empezamos и empezáis. Герундий empezando тоже сохраняет e. Cambiar спрягается регулярно; для переодевания естественны me cambio de ropa или me cambio el sombrero.', 'Aprender is a regular -er verb. Empezar changes e→ie in stressed forms: empiezo, empiezas, empieza, empiezan, but empezamos and empezáis. The gerund empezando also keeps e. Cambiar is regular; for changing clothes, me cambio de ropa or me cambio el sombrero is natural.'),
      rule: 'aprendo · empiezo / empezamos · cambio / me cambio',
      examples: [
        ['Aprendo español. / Quiero aprender más.', l('Я учу испанский. / Я хочу узнать больше.', 'I learn Spanish. / I want to learn more.')],
        ['Empiezo la clase ahora.', l('Я начинаю занятие сейчас.', 'I am starting class now.')],
        ['Empiezo el máster en Barcelona.', l('Я начинаю магистратуру в Барселоне.', 'I am starting my master’s degree in Barcelona.')],
        ['Estoy empezando el máster en Barcelona.', l('Я начинаю / сейчас в процессе начала магистратуры в Барселоне.', 'I am starting my master’s degree in Barcelona.')],
        ['Quiero cambiar de ciudad. / Cambio mi horario.', l('Я хочу сменить город. / Я меняю своё расписание.', 'I want to change cities. / I change my schedule.')],
      ],
    },
    {
      title: l('Decir и creer: передавай мысль', 'Decir and creer: express an idea'),
      body: l('У decir форма yo — digo, а для tú — dices. Конструкция ¿Cómo se dice…? означает «Как это говорится…?». Creer даёт creo/crees; после него que вводит целую мысль. «Любить» в романтическом смысле — amar, а creer означает «верить / считать».', 'The yo form of decir is digo and the tú form is dices. ¿Cómo se dice…? means “How do you say…?”. Creer gives creo/crees; que introduces a full idea after it. Romantic “to love” is amar, while creer means “to believe / think”.'),
      rule: 'digo / dices · se dice · creo que…',
      examples: [
        ['Quiero decir algo.', l('Я хочу кое-что сказать.', 'I want to say something.')],
        ['¿Cómo se dice en español?', l('Как это сказать по-испански?', 'How do you say it in Spanish?')],
        ['Creo que es importante.', l('Я считаю, что это важно.', 'I believe it is important.')],
        ['Creo que aprender español es necesario.', l('Я считаю, что учить испанский необходимо.', 'I believe learning Spanish is necessary.')],
      ],
    },
    {
      title: l('Conocer и llegar: люди, места и прибытие', 'Conocer and llegar: people, places and arrival'),
      body: l('Conocer используют со знакомыми людьми и местами; форма yo — conozco. Перед человеком ставится личное a: conozco a una persona. Llegar — прибывать; место назначения вводится через a. Llegaré — «я прибуду» в будущем. Llévame означает «отвези/отведи меня» и происходит от другого глагола — llevar.', 'Conocer is used for people and places you know or meet; its yo form is conozco. A person takes personal a: conozco a una persona. Llegar means to arrive and a introduces the destination. Llegaré means “I will arrive”. Llévame means “take me” and comes from a different verb, llevar.'),
      rule: 'conozco + lugar · conozco a + persona · llego a + lugar',
      examples: [
        ['Quiero conocer Barcelona.', l('Я хочу познакомиться с Барселоной / узнать город.', 'I want to get to know Barcelona.')],
        ['Conozco a una persona nueva.', l('Я знакомлюсь / знаком с новым человеком.', 'I meet / know a new person.')],
        ['Llego a casa. / Llego a Barcelona mañana.', l('Я прихожу домой. / Я прибываю в Барселону завтра.', 'I arrive home. / I arrive in Barcelona tomorrow.')],
        ['Llegaré mañana.', l('Я прибуду завтра — форма будущего времени.', 'I will arrive tomorrow — future tense.')],
        ['Llévame a casa.', l('Отвези / отведи меня домой — от llevar.', 'Take me home — from llevar.')],
      ],
    },
    {
      title: l('Abrir, hacer и trabajar', 'Abrir, hacer and trabajar'),
      body: l('Abrir и trabajar следуют обычным моделям -ir и -ar. Hacer — неправильный только в некоторых формах: yo hago, но tú haces. Артикль должен совпадать с существительным: la puerta, el ordenador, la tarea.', 'Abrir and trabajar follow the regular -ir and -ar patterns. Hacer is irregular in some forms: yo hago, but tú haces. The article must match the noun: la puerta, el ordenador, la tarea.'),
      rule: 'abro · hago / haces · trabajo',
      examples: [
        ['Abro la puerta. / Abro el ordenador.', l('Я открываю дверь. / Я открываю компьютер.', 'I open the door. / I open the computer.')],
        ['Hago la tarea. / Hago ejercicio.', l('Я делаю домашнее задание. / Я занимаюсь спортом.', 'I do the homework. / I exercise.')],
        ['¿Qué haces ahora?', l('Что ты сейчас делаешь?', 'What are you doing now?')],
        ['Trabajo mucho. / Quiero trabajar en España.', l('Я много работаю. / Я хочу работать в Испании.', 'I work a lot. / I want to work in Spain.')],
      ],
    },
    {
      title: l('Две дополнительные модели: dormir и construir', 'Two extra patterns: dormir and construir'),
      body: l('Dormir меняет o→ue во всех ударных формах, но не у nosotros/vosotros. Construir добавляет y в формах, где окончание начинается не с i. Эти формы не входят в список десяти глаголов домашнего задания, но полностью сохраняют материал урока.', 'Dormir changes o→ue in stressed forms, but not with nosotros/vosotros. Construir adds y where the ending does not begin with i. These are not among the ten homework verbs, but they preserve the complete lesson material.'),
      rule: 'duermo / dormimos · construyo / construimos',
      examples: [
        ['duermo · duermes · duerme · dormimos · dormís · duermen', l('Полная модель dormir в настоящем.', 'The complete present-tense pattern of dormir.')],
        ['construyo · construyes · construye · construimos · construís · construyen', l('Полная модель construir в настоящем.', 'The complete present-tense pattern of construir.')],
      ],
    },
    {
      title: l('Твои примеры: точная естественная версия', 'Your examples: precise natural versions'),
      body: l('Формы из занятия были понятны; здесь исправлены орфография, вопросительные слова и более естественный выбор конструкции. Español — со строчной буквы, lección — с ударением. Местоимение yo можно оставить для контраста, но обычно оно не нужно.', 'Your lesson forms were clear; this page fixes spelling, question words and a few more natural constructions. Español is lower-case and lección has an accent. Yo can stay for contrast, but it is normally unnecessary.'),
      rule: l('ударение + предлог + естественный глагол', 'accent + preposition + natural verb choice'),
      examples: [
        ['Quiero aprender español.', l('Не Español: названия языков пишутся со строчной буквы.', 'Not Español: language names are lower-case.')],
        ['Ahora empiezo la clase.', l('Yo можно опустить; ahora естественно задаёт время.', 'Yo can be omitted; ahora naturally sets the time.')],
        ['Cuando llego a casa, me cambio de ropa.', l('Когда я прихожу домой, я переодеваюсь. В утверждении cuando без ударения.', 'When I arrive home, I change clothes. In a statement, cuando has no accent.')],
        ['Creo que esa idea es interesante.', l('Полная мысль после creo que.', 'A complete idea follows creo que.')],
        ['Quiero decir: «Gracias por esta lección».', l('Lección пишется с ó; двоеточие вводит точные слова.', 'Lección takes ó; the colon introduces the exact words.')],
        ['¿Qué aprendes? · ¿A quién quieres conocer? · ¿Cuándo llegas?', l('Вопросительные слова несут письменное ударение; перед человеком стоит a.', 'Question words take written accents; a comes before a person.')],
        ['¿Cuándo te cambias de ropa?', l('Естественный вопрос о том, когда человек переодевается.', 'A natural question asking when someone changes clothes.')],
      ],
    },
  ],
  words: [
    { es: 'aprender → aprendo', en: l('учиться / узнавать → я учусь', 'to learn → I learn'), example: 'Aprendo español.' },
    { es: 'empezar → empiezo', en: l('начинать → я начинаю', 'to start → I start'), example: 'Empiezo la clase ahora.' },
    { es: 'empezando', en: l('начиная / в процессе начала', 'starting'), example: 'Estoy empezando el máster.' },
    { es: 'cambiar → cambio', en: l('менять → я меняю', 'to change → I change'), example: 'Cambio mi horario.' },
    { es: 'el horario', en: l('расписание', 'schedule'), example: 'Quiero cambiar mi horario.' },
    { es: 'decir → digo', en: l('говорить / сказать → я говорю', 'to say/tell → I say'), example: 'Quiero decir algo.' },
    { es: 'creer → creo', en: l('верить / считать → я считаю', 'to believe/think → I believe'), example: 'Creo que es importante.' },
    { es: 'conocer → conozco', en: l('знать / знакомиться с человеком или местом', 'to know/meet a person or place'), example: 'Conozco a una persona nueva.' },
    { es: 'llegar → llego', en: l('прибывать → я прибываю', 'to arrive → I arrive'), example: 'Llego a casa.' },
    { es: 'llegaré', en: l('я прибуду — будущее', 'I will arrive — future'), example: 'Llegaré mañana.' },
    { es: 'llevar → llévame', en: l('отвести / отвезти → отведи меня', 'to take → take me'), example: 'Llévame a casa.' },
    { es: 'abrir → abro', en: l('открывать → я открываю', 'to open → I open'), example: 'Abro la puerta.' },
    { es: 'hacer → hago', en: l('делать → я делаю', 'to do/make → I do'), example: 'Hago ejercicio.' },
    { es: 'trabajar → trabajo', en: l('работать → я работаю', 'to work → I work'), example: 'Trabajo mucho.' },
    { es: 'dormir → duermo', en: l('спать → я сплю', 'to sleep → I sleep'), example: 'Duermo bien.' },
    { es: 'construir → construyo', en: l('строить → я строю', 'to build → I build'), example: 'Construyo una casa.' },
  ],
  quiz: [
    { prompt: 'Yo ___ español.', options: ['aprendo', 'aprendes', 'aprender'], answer: 'aprendo', explanation: l('Для yo у правильного -er глагола окончание -o.', 'A regular -er verb takes -o with yo.') },
    { prompt: 'Nosotros ___ español.', options: ['aprendemos', 'aprendimos', 'aprendéis'], answer: 'aprendemos', explanation: l('Настоящее nosotros для -er: -emos.', 'The present nosotros ending for -er is -emos.') },
    { prompt: 'Vosotros ___ la puerta.', options: ['abrís', 'abres', 'abren'], answer: 'abrís', explanation: l('Настоящее vosotros для -ir: -ís.', 'The present vosotros ending for -ir is -ís.') },
    { prompt: 'Yo ___ la clase ahora.', options: ['empiezo', 'empezo', 'empiezas'], answer: 'empiezo', explanation: l('В ударной форме empezar меняет e→ie.', 'In the stressed form, empezar changes e→ie.') },
    { prompt: 'Nosotros ___ la clase.', options: ['empezamos', 'empiezamos', 'empiezan'], answer: 'empezamos', explanation: l('У nosotros чередования e→ie нет.', 'There is no e→ie change with nosotros.') },
    { prompt: l('Как сказать «Я сейчас начинаю магистратуру»?', 'How do you say “I am starting my master’s degree”?'), options: ['Estoy empezando el máster.', 'Estoy empiezo el máster.', 'Soy empezando el máster.'], answer: 'Estoy empezando el máster.', explanation: l('Процесс: estar + герундий empezando.', 'An action in progress uses estar + the gerund empezando.') },
    { prompt: 'Yo ___ algo.', options: ['digo', 'dice', 'decir'], answer: 'digo', explanation: l('Форма yo глагола decir — digo.', 'The yo form of decir is digo.') },
    { prompt: '¿Cómo se ___ en español?', options: ['dice', 'digo', 'decir'], answer: 'dice', explanation: l('Устойчивая безличная конструкция: se dice.', 'The fixed impersonal pattern is se dice.') },
    { prompt: 'Yo ___ que es importante.', options: ['creo', 'cree', 'creer'], answer: 'creo', explanation: l('Для yo: creo; затем que + мысль.', 'With yo: creo, followed by que + an idea.') },
    { prompt: '___ a una persona nueva.', options: ['Conozco', 'Conoco', 'Conocer'], answer: 'Conozco', explanation: l('Форма yo — conozco; перед человеком нужно a.', 'The yo form is conozco, and a is needed before a person.') },
    { prompt: 'Quiero ___ Barcelona.', options: ['conocer', 'conozco a', 'conocer a'], answer: 'conocer', explanation: l('После quiero — инфинитив; перед местом личное a не ставится.', 'Quiero takes an infinitive, and a place does not take personal a.') },
    { prompt: 'Llego ___ casa.', options: ['a', 'en', 'de'], answer: 'a', explanation: l('Направление с llegar вводится через a.', 'A destination with llegar is introduced by a.') },
    { prompt: l('Что означает llegaré?', 'What does llegaré mean?'), options: [l('я прибуду', 'I will arrive'), l('я прибываю', 'I arrive'), l('отведи меня', 'take me')], answer: l('я прибуду', 'I will arrive'), explanation: l('Окончание -é здесь даёт будущее первого лица.', 'The -é ending marks first-person future here.') },
    { prompt: l('От какого глагола форма llévame?', 'Which verb does llévame come from?'), options: ['llevar', 'llegar', 'venir'], answer: 'llevar', explanation: l('Llévame — «отведи/отвези меня», от llevar.', 'Llévame means “take me” and comes from llevar.') },
    { prompt: 'Yo ___ la puerta.', options: ['abro', 'abre', 'abrir'], answer: 'abro', explanation: l('Abrir — правильный -ir глагол; для yo — abro.', 'Abrir is a regular -ir verb; its yo form is abro.') },
    { prompt: '¿Qué ___ ahora?', options: ['haces', 'hago', 'hacer'], answer: 'haces', explanation: l('Вопрос к tú требует haces.', 'A question to tú needs haces.') },
    { prompt: l('Выбери правильное написание.', 'Choose the correct spelling.'), options: ['Gracias por esta lección.', 'Gracias por esta leccíon.', 'Gracias por esta leccion.'], answer: 'Gracias por esta lección.', explanation: l('Ударение в lección падает на ó.', 'The written accent in lección belongs on ó.') },
    { prompt: l('Как естественно сказать «я переодеваюсь»?', 'What is a natural way to say “I change clothes”?'), options: ['Me cambio de ropa.', 'Cambio de mi ropa.', 'Me cambiar ropa.'], answer: 'Me cambio de ropa.', explanation: l('Возвратное me показывает, что человек переодевает себя.', 'Reflexive me shows that the person is changing their own clothes.') },
  ],
  builder: [
    { translation: l('Я учу испанский.', 'I learn Spanish.'), answer: ['Aprendo', 'español.'] },
    { translation: l('Я хочу узнать больше.', 'I want to learn more.'), answer: ['Quiero', 'aprender', 'más.'] },
    { translation: l('Я начинаю занятие сейчас.', 'I am starting class now.'), answer: ['Empiezo', 'la', 'clase', 'ahora.'] },
    { translation: l('Я начинаю магистратуру в Барселоне.', 'I am starting my master’s degree in Barcelona.'), answer: ['Empiezo', 'el', 'máster', 'en', 'Barcelona.'] },
    { translation: l('Я сейчас начинаю магистратуру.', 'I am starting my master’s degree.'), answer: ['Estoy', 'empezando', 'el', 'máster.'] },
    { translation: l('Я хочу сменить город.', 'I want to change cities.'), answer: ['Quiero', 'cambiar', 'de', 'ciudad.'] },
    { translation: l('Я меняю своё расписание.', 'I change my schedule.'), answer: ['Cambio', 'mi', 'horario.'] },
    { translation: l('Я хочу кое-что сказать.', 'I want to say something.'), answer: ['Quiero', 'decir', 'algo.'] },
    { translation: l('Как это сказать по-испански?', 'How do you say it in Spanish?'), answer: ['¿Cómo', 'se', 'dice', 'en', 'español?'] },
    { translation: l('Я считаю, что это важно.', 'I believe it is important.'), answer: ['Creo', 'que', 'es', 'importante.'] },
    { translation: l('Я хочу узнать Барселону.', 'I want to get to know Barcelona.'), answer: ['Quiero', 'conocer', 'Barcelona.'] },
    { translation: l('Я знакомлюсь с новым человеком.', 'I meet a new person.'), answer: ['Conozco', 'a', 'una', 'persona', 'nueva.'] },
    { translation: l('Я прихожу домой.', 'I arrive home.'), answer: ['Llego', 'a', 'casa.'] },
    { translation: l('Я прибуду завтра.', 'I will arrive tomorrow.'), answer: ['Llegaré', 'mañana.'] },
    { translation: l('Я открываю дверь.', 'I open the door.'), answer: ['Abro', 'la', 'puerta.'] },
    { translation: l('Я занимаюсь спортом.', 'I exercise.'), answer: ['Hago', 'ejercicio.'] },
    { translation: l('Я много работаю.', 'I work a lot.'), answer: ['Trabajo', 'mucho.'] },
    { translation: l('Когда ты приезжаешь?', 'When do you arrive?'), answer: ['¿Cuándo', 'llegas?'] },
  ],
  compose: [
    { prompt: l('Напиши: «Я хочу учить испанский».', 'Write: “I want to learn Spanish.”'), hint: 'quiero + aprender · español', accepted: ['Quiero aprender español.', 'Yo quiero aprender español.'], answer: 'Quiero aprender español.', explanation: l('После quiero используется инфинитив aprender; español пишется со строчной буквы.', 'Quiero is followed by the infinitive aprender; español is lower-case.') },
    { prompt: l('Напиши: «Сейчас я начинаю занятие».', 'Write: “I am starting class now.”'), hint: 'ahora · empezar → empiezo · la clase', accepted: ['Ahora empiezo la clase.', 'Empiezo la clase ahora.', 'Ahora yo empiezo la clase.'], answer: 'Ahora empiezo la clase.', explanation: l('В форме yo: empiezo. Местоимение yo необязательно.', 'The yo form is empiezo. The pronoun yo is optional.') },
    { prompt: l('Напиши: «Когда я прихожу домой, я переодеваюсь».', 'Write: “When I arrive home, I change clothes.”'), hint: 'cuando llego a casa · me cambio de ropa', accepted: ['Cuando llego a casa, me cambio de ropa.', 'Cuando llego a casa me cambio de ropa.'], answer: 'Cuando llego a casa, me cambio de ropa.', explanation: l('В утверждении cuando без ударения; llegar требует a casa; переодеваться — me cambio de ropa.', 'In a statement cuando has no accent; llegar takes a casa; changing clothes is me cambio de ropa.') },
    { prompt: l('Напиши: «Я считаю, что эта идея интересная».', 'Write: “I think this idea is interesting.”'), hint: 'creo que · esa idea · es interesante', accepted: ['Creo que esa idea es interesante.', 'Yo creo que esa idea es interesante.'], answer: 'Creo que esa idea es interesante.', explanation: l('Creo que вводит полную мысль.', 'Creo que introduces a complete idea.') },
    { prompt: l('Напиши: «Я хочу сказать: спасибо за этот урок».', 'Write: “I want to say: thank you for this lesson.”'), hint: 'quiero decir · gracias por esta lección', accepted: ['Quiero decir: gracias por esta lección.', 'Quiero decir gracias por esta lección.'], answer: 'Quiero decir: gracias por esta lección.', explanation: l('После quiero — инфинитив decir; lección имеет ударение на ó.', 'Quiero takes the infinitive decir; lección has an accent on ó.') },
    { prompt: l('Спроси: «С кем ты хочешь познакомиться?»', 'Ask: “Who do you want to meet?”'), hint: '¿a quién · quieres conocer?', accepted: ['¿A quién quieres conocer?', 'A quién quieres conocer?'], answer: '¿A quién quieres conocer?', explanation: l('Перед человеком нужно a, а quién в вопросе имеет ударение.', 'A person needs a, and quién takes an accent in a question.') },
    { prompt: l('Напиши: «Я открываю компьютер и делаю домашнее задание».', 'Write: “I open the computer and do the homework.”'), hint: 'abro el ordenador · y · hago la tarea', accepted: ['Abro el ordenador y hago la tarea.', 'Yo abro el ordenador y hago la tarea.'], answer: 'Abro el ordenador y hago la tarea.', explanation: l('Abro и hago — две формы yo; y соединяет действия.', 'Abro and hago are both yo forms; y connects the actions.') },
    { prompt: l('Напиши: «Я хочу работать в Испании».', 'Write: “I want to work in Spain.”'), hint: 'quiero + trabajar · en España', accepted: ['Quiero trabajar en España.', 'Yo quiero trabajar en España.'], answer: 'Quiero trabajar en España.', explanation: l('После quiero инфинитив trabajar; название страны España с прописной буквы.', 'Quiero takes the infinitive trabajar; the country name España is capitalized.') },
  ],
  creation: {
    checker: 'learning-changes', total: 5,
    title: l('Напиши 5 предложений с пятью разными глаголами', 'Write 5 sentences with five different verbs'),
    instruction: l('Используй глаголы этого урока и сам выбери смысл. Каждое предложение проверяется отдельно с объяснением. Оно засчитывается, только если грамматически верно и добавляет новый глагол; этап не завершится, пока не будет пяти правильных фраз.', 'Use the verbs from this lesson and choose the meaning yourself. Each sentence is checked separately with an explanation. It counts only when it is grammatical and introduces a new verb; the stage stays open until you have five correct sentences.'),
    bank: [
      { word: 'Abrir', meaning: l('открывать', 'to open') }, { word: 'Aprender', meaning: l('учиться', 'to learn') },
      { word: 'Cambiar', meaning: l('менять', 'to change') }, { word: 'Conocer', meaning: l('знать / знакомиться', 'to know / meet') },
      { word: 'Creer', meaning: l('верить / считать', 'to believe / think') }, { word: 'Decir', meaning: l('сказать / говорить', 'to say / tell') },
      { word: 'Empezar', meaning: l('начинать', 'to start') }, { word: 'Hacer', meaning: l('делать', 'to do / make') },
      { word: 'Llegar', meaning: l('прибывать', 'to arrive') }, { word: 'Trabajar', meaning: l('работать', 'to work') },
    ],
    forms: ['abro / abres', 'aprendo / aprendes', 'cambio / me cambio', 'conozco / conoces', 'creo que…', 'digo / dices', 'empiezo / empezamos', 'hago / haces', 'llego a… / llegaré', 'trabajo / trabajas', 'quiero + infinitivo', 'a una persona', 'a casa', 'en España'],
  },
}
