export const serEstarPack = {
  id: 'ser-vs-estar',
  title: 'Ser vs Estar — finally clear',
  eyebrow: 'Grammar without pain · A1',
  description: 'Understand the real difference, learn the forms and choose naturally in everyday situations.',
  accent: 'blue',
  minutes: 35,
  icon: 'Brain',
  guide: [
    {
      title: 'Не «постоянное vs временное»',
      body: 'Рабочая идея проще: SER говорит, кто или что это. ESTAR говорит, где это или в каком оно состоянии.',
      rule: 'SER = identity · ESTAR = state & location',
      examples: [
        ['Soy estudiante.', 'Я студент: это моя роль.'],
        ['Estoy cansado.', 'Я устал: это моё состояние.'],
        ['Barcelona está en España.', 'Место всегда требует estar, даже если оно не изменится.'],
        ['Hoy es martes.', 'Время и дата требуют ser, хотя вторник временный.'],
      ],
    },
    {
      title: 'Когда нужен SER',
      body: 'Используй SER для личности, происхождения, профессии, характеристики, времени, материала и отношений.',
      rule: 'soy · eres · es · somos · sois · son',
      examples: [
        ['Soy de Ucrania.', 'Происхождение.'],
        ['José es profesor.', 'Профессия или роль.'],
        ['La mesa es de madera.', 'Материал.'],
        ['Son las ocho.', 'Время.'],
        ['Marta es mi amiga.', 'Отношения.'],
      ],
    },
    {
      title: 'Когда нужен ESTAR',
      body: 'Используй ESTAR для местоположения, чувств и состояний, результата изменения и действия прямо сейчас.',
      rule: 'estoy · estás · está · estamos · estáis · están',
      examples: [
        ['Estoy en Barcelona.', 'Местоположение.'],
        ['Estamos contentos.', 'Чувство или состояние.'],
        ['La puerta está abierta.', 'Результат: дверь открыли.'],
        ['Estoy aprendiendo español.', 'Действие происходит сейчас.'],
      ],
    },
    {
      title: 'Одно прилагательное — другой смысл',
      body: 'Некоторые прилагательные меняют смысл. SER описывает характерную черту, ESTAR — состояние или результат.',
      rule: 'what it is ↔ how it is',
      examples: [
        ['Es aburrido. ↔ Está aburrido.', 'Он скучный. ↔ Ему скучно.'],
        ['Es listo. ↔ Está listo.', 'Он умный. ↔ Он готов.'],
        ['Es rico. ↔ Está rico.', 'Он богатый. ↔ Это вкусно.'],
        ['Es seguro. ↔ Está seguro.', 'Это безопасно. ↔ Он уверен.'],
      ],
    },
    {
      title: 'Алгоритм на пять секунд',
      body: 'Задай вопрос по порядку. Где находится? → ESTAR. Как себя чувствует или в каком состоянии? → ESTAR. Кто это, откуда, что это за вещь, который час? → SER.',
      rule: 'where/how → estar · who/what → ser',
      examples: [
        ['¿Dónde está el baño?', 'Где? → estar.'],
        ['¿Cómo estás?', 'Как себя чувствуешь? → estar.'],
        ['¿De dónde eres?', 'Откуда ты? → ser.'],
        ['¿Qué es esto?', 'Что это? → ser.'],
      ],
    },
  ],
  words: [
    { es: 'Soy de Ucrania.', en: 'I am from Ukraine.', example: 'SER: происхождение — часть ответа на вопрос «кто ты?»' },
    { es: 'Estoy en Barcelona.', en: 'I am in Barcelona.', example: 'ESTAR: местоположение.' },
    { es: 'Soy estudiante.', en: 'I am a student.', example: 'SER: роль или профессия.' },
    { es: 'Estoy cansado.', en: 'I am tired.', example: 'ESTAR: состояние.' },
    { es: 'Marta es mi amiga.', en: 'Marta is my friend.', example: 'SER: отношения.' },
    { es: 'Marta está en casa.', en: 'Marta is at home.', example: 'ESTAR: где находится Marta.' },
    { es: 'Barcelona está en España.', en: 'Barcelona is in Spain.', example: 'Место требует ESTAR, даже когда оно постоянное.' },
    { es: 'Hoy es martes.', en: 'Today is Tuesday.', example: 'SER: дата и время.' },
    { es: 'La mesa es de madera.', en: 'The table is made of wood.', example: 'SER: материал.' },
    { es: 'La puerta está abierta.', en: 'The door is open.', example: 'ESTAR: результат изменения.' },
    { es: 'La película es aburrida.', en: 'The film is boring.', example: 'SER: фильм обладает такой характеристикой.' },
    { es: 'Estoy aburrido.', en: 'I am bored.', example: 'ESTAR: мне сейчас скучно.' },
    { es: 'Él es listo.', en: 'He is clever.', example: 'SER + listo = умный.' },
    { es: 'Él está listo.', en: 'He is ready.', example: 'ESTAR + listo = готов.' },
    { es: 'Ella es rica.', en: 'She is rich.', example: 'SER + rico = богатый.' },
    { es: 'La sopa está rica.', en: 'The soup tastes good.', example: 'ESTAR + rico = вкусный.' },
  ],
  quiz: [
    { prompt: 'Yo ___ de Ucrania.', options: ['soy', 'estoy', 'es', 'está'], answer: 'soy', explanation: 'Происхождение отвечает на вопрос «кто ты?» → SER.' },
    { prompt: 'Ahora ___ en Barcelona.', options: ['soy', 'estoy', 'eres', 'es'], answer: 'estoy', explanation: 'Местоположение → ESTAR.' },
    { prompt: 'Barcelona ___ en España.', options: ['es', 'está', 'son', 'están'], answer: 'está', explanation: 'Города и страны не «временные», но местоположение всё равно требует ESTAR.' },
    { prompt: 'Hoy ___ martes.', options: ['es', 'está', 'soy', 'estoy'], answer: 'es', explanation: 'День, дата и время → SER.' },
    { prompt: 'José ___ profesor.', options: ['es', 'está', 'eres', 'estás'], answer: 'es', explanation: 'Профессия или роль → SER.' },
    { prompt: 'José ___ cansado.', options: ['es', 'está', 'son', 'están'], answer: 'está', explanation: 'Усталость — состояние → ESTAR.' },
    { prompt: 'La clase ___ interesante.', options: ['es', 'está', 'soy', 'estoy'], answer: 'es', explanation: 'Мы характеризуем саму лекцию → SER.' },
    { prompt: 'La clase ___ en el aula 4.', options: ['es', 'está', 'son', 'están'], answer: 'está', explanation: 'Здесь речь о месте проведения → ESTAR.' },
    { prompt: 'Nosotros ___ listos para salir.', options: ['somos', 'estamos', 'sois', 'estáis'], answer: 'estamos', explanation: 'Estar listo = быть готовым.' },
    { prompt: 'Mi hermano ___ muy listo.', options: ['es', 'está', 'soy', 'estoy'], answer: 'es', explanation: 'Ser listo = быть умным.' },
    { prompt: 'La sopa ___ muy rica.', options: ['es', 'está', 'son', 'están'], answer: 'está', explanation: 'Estar rico о еде = быть вкусным.' },
    { prompt: 'Ella ___ rica y tiene dos empresas.', options: ['es', 'está', 'soy', 'estoy'], answer: 'es', explanation: 'Ser rico о человеке = быть богатым.' },
    { prompt: '¿Dónde ___ el baño?', options: ['es', 'está', 'son', 'están'], answer: 'está', explanation: 'Вопрос «где?» → ESTAR.' },
    { prompt: '¿De dónde ___ tú?', options: ['eres', 'estás', 'es', 'está'], answer: 'eres', explanation: 'Происхождение → SER.' },
    { prompt: 'Vosotros ___ estudiantes.', options: ['sois', 'estáis', 'somos', 'estamos'], answer: 'sois', explanation: 'Роль/идентичность + vosotros → sois.' },
    { prompt: 'Vosotros ___ en casa.', options: ['sois', 'estáis', 'son', 'están'], answer: 'estáis', explanation: 'Местоположение + vosotros → estáis.' },
    { prompt: 'La mesa ___ de madera.', options: ['es', 'está', 'son', 'están'], answer: 'es', explanation: 'Материал → SER.' },
    { prompt: 'La puerta ___ abierta.', options: ['es', 'está', 'soy', 'estoy'], answer: 'está', explanation: 'Открыта как результат действия → ESTAR.' },
    { prompt: '___ las ocho de la tarde.', options: ['Son', 'Están', 'Es', 'Está'], answer: 'Son', explanation: 'Время → SER; с множественным числом horas используем son.' },
    { prompt: 'Ahora ___ aprendiendo español.', options: ['soy', 'estoy', 'es', 'está'], answer: 'estoy', explanation: 'Действие прямо сейчас: ESTAR + gerundio.' },
    { prompt: 'Este barrio normalmente ___ tranquilo.', options: ['es', 'está', 'son', 'están'], answer: 'es', explanation: 'Обычная характеристика района → SER.' },
    { prompt: 'El barrio ___ muy tranquilo hoy.', options: ['es', 'está', 'soy', 'estoy'], answer: 'está', explanation: 'Состояние именно сегодня → ESTAR.' },
  ],
  builder: [
    { translation: 'I am from Ukraine.', answer: ['Soy', 'de', 'Ucrania.'] },
    { translation: 'I am in Barcelona.', answer: ['Estoy', 'en', 'Barcelona.'] },
    { translation: 'We are students.', answer: ['Somos', 'estudiantes.'] },
    { translation: 'We are tired.', answer: ['Estamos', 'cansados.'] },
    { translation: 'Where is the bathroom?', answer: ['¿Dónde', 'está', 'el', 'baño?'] },
    { translation: 'Today is Tuesday.', answer: ['Hoy', 'es', 'martes.'] },
    { translation: 'You all are ready. (Spain)', answer: ['Vosotros', 'estáis', 'listos.'] },
    { translation: 'You all are students. (Spain)', answer: ['Vosotros', 'sois', 'estudiantes.'] },
    { translation: 'The door is open.', answer: ['La', 'puerta', 'está', 'abierta.'] },
    { translation: 'The table is made of wood.', answer: ['La', 'mesa', 'es', 'de', 'madera.'] },
    { translation: 'The film is boring.', answer: ['La', 'película', 'es', 'aburrida.'] },
    { translation: 'I am bored.', answer: ['Estoy', 'aburrido.'] },
  ],
  scene: {
    place: 'First day at university in Barcelona',
    speaker: 'Marta',
    line: '¡Hola! ¿Eres nuevo aquí? ¿Cómo estás?',
    note: 'Она использовала оба глагола: eres для личности, estás для состояния.',
    replies: [
      { text: 'Sí, soy nuevo. Estoy un poco nervioso, pero estoy bien.', feedback: 'Идеально: soy описывает тебя, estoy — чувства и состояние.', correct: true },
      { text: 'Sí, estoy nuevo. Soy nervioso ahora.', feedback: 'Поменяй местами: soy nuevo, estoy nervioso.', correct: false },
      { text: 'Sí, es nuevo y está Illia.', feedback: 'Здесь нужны формы первого лица: soy и estoy.', correct: false },
    ],
  },
}
