export const sixtyPhrasesPack = {
  id: 'everyday-60',
  title: '60 phrases for real life',
  eyebrow: 'Core marathon · A1–A2',
  description: 'The phrases that keep everyday Spanish moving — trained in both directions until they stick.',
  accent: 'mint',
  minutes: 55,
  icon: 'Sparkles',
  generatedQuiz: true,
  generatedBuilder: true,
  words: [
    { es: 'No pasa nada.', en: 'No worries. / It’s okay.', example: '—Perdón por llegar tarde. —No pasa nada.' },
    { es: 'A ver…', en: 'Let’s see… / Well…', example: 'A ver… ¿qué podemos hacer hoy?' },
    { es: 'Ni idea.', en: 'No idea.', example: '—¿Dónde está Pablo? —Ni idea.' },
    { es: 'Por si acaso.', en: 'Just in case.', example: 'Llevo un paraguas por si acaso.' },
    { es: 'Me da igual.', en: 'I don’t mind. / It’s all the same to me.', example: 'Pizza o pasta, me da igual.' },
    { es: 'Es lo que hay.', en: 'It is what it is.', example: 'No podemos cambiarlo. Es lo que hay.' },
    { es: '¿En serio?', en: 'Seriously?', example: '—He ganado dos entradas. —¿En serio?' },
    { es: '¡No me digas!', en: 'No way! / You don’t say!', example: '—Me mudo a Barcelona. —¡No me digas!' },
    { es: 'Me suena.', en: 'It sounds familiar.', example: 'Ese nombre me suena.' },
    { es: 'Poco a poco.', en: 'Little by little.', example: 'Estoy aprendiendo español poco a poco.' },
    { es: '¡Vale!', en: 'Okay! / Deal!', example: '—Nos vemos a las ocho. —¡Vale!' },
    { es: 'Claro que sí.', en: 'Of course. / Absolutely.', example: '—¿Puedes ayudarme? —Claro que sí.' },
    { es: '¿Qué te parece?', en: 'What do you think? / How does it sound?', example: 'Podemos ir mañana. ¿Qué te parece?' },
    { es: 'Tengo ganas de…', en: 'I feel like… / I’m looking forward to…', example: 'Tengo ganas de conocer la ciudad.' },
    { es: '¡Madre mía!', en: 'Oh my goodness! / Wow!', example: '¡Madre mía, qué calor hace!' },
    { es: 'A lo mejor.', en: 'Maybe. / Perhaps.', example: 'A lo mejor voy a la playa mañana.' },
    { es: 'Te echo de menos.', en: 'I miss you.', example: 'Hace mucho que no te veo. Te echo de menos.' },
    { es: '¡Qué guay!', en: 'How cool! / Awesome!', example: '—Tengo entradas para el concierto. —¡Qué guay!' },
    { es: '¡Qué pena!', en: 'What a shame!', example: 'No puedes venir. ¡Qué pena!' },
    { es: 'Buen provecho.', en: 'Enjoy your meal.', example: 'La comida ya está lista. ¡Buen provecho!' },

    { es: '¡Hola! ¿Qué tal?', en: 'Hello! How’s it going?', example: '¡Hola, Marta! ¿Qué tal?' },
    { es: 'Buenos días. / Buenas tardes. / Buenas noches.', en: 'Good morning. / Good afternoon. / Good evening.', example: 'Buenas tardes, tengo una reserva.' },
    { es: 'Por favor.', en: 'Please.', example: 'Un café con leche, por favor.' },
    { es: 'Muchas gracias. / De nada.', en: 'Thank you very much. / You’re welcome.', example: '—Muchas gracias. —De nada.' },
    { es: '¡Hasta luego!', en: 'See you later!', example: 'Me voy. ¡Hasta luego!' },
    { es: 'No entiendo. ¿Puedes repetir, por favor?', en: 'I don’t understand. Can you repeat, please?', example: 'No entiendo. ¿Puedes repetir, por favor?' },
    { es: '¿Cómo se dice … en español?', en: 'How do you say … in Spanish?', example: '¿Cómo se dice “receipt” en español?' },
    { es: '¿Hablas inglés?', en: 'Do you speak English?', example: 'Perdona, ¿hablas inglés?' },
    { es: 'Disculpe. / Perdón.', en: 'Excuse me. / Sorry.', example: 'Disculpe, ¿dónde está la estación?' },
    { es: 'Más despacio, por favor.', en: 'More slowly, please.', example: '¿Puedes hablar más despacio, por favor?' },
    { es: '¿Dónde está el baño?', en: 'Where is the bathroom?', example: 'Perdona, ¿dónde está el baño?' },
    { es: '¿Cuánto cuesta esto?', en: 'How much does this cost?', example: 'Me gusta. ¿Cuánto cuesta esto?' },
    { es: '¿Dónde está la estación?', en: 'Where is the station?', example: '¿Dónde está la estación de metro?' },
    { es: 'Me gustaría…', en: 'I would like…', example: 'Me gustaría un vaso de agua.' },
    { es: 'La cuenta, por favor.', en: 'The bill, please.', example: 'Camarero, la cuenta, por favor.' },
    { es: '¿Cómo te llamas? / Me llamo…', en: 'What’s your name? / My name is…', example: '¿Cómo te llamas? Me llamo Illia.' },
    { es: 'Mucho gusto. / Encantado.', en: 'Nice to meet you.', example: 'Me llamo Dani. Mucho gusto.' },
    { es: '¿De dónde eres?', en: 'Where are you from?', example: '¿De dónde eres? Soy de Ucrania.' },
    { es: '¡Muy bien! / ¡Perfecto!', en: 'Very good! / Perfect!', example: 'Nos vemos a las seis. ¡Perfecto!' },
    { es: '¿Qué me recomiendas?', en: 'What do you recommend?', example: 'Es mi primera vez aquí. ¿Qué me recomiendas?' },

    { es: '¿Me puedes ayudar, por favor?', en: 'Can you help me, please?', example: 'Perdona, ¿me puedes ayudar, por favor?' },
    { es: '¿A qué hora abre / cierra?', en: 'What time does it open / close?', example: '¿A qué hora cierra el supermercado?' },
    { es: '¿Tienes cambio de diez euros?', en: 'Do you have change for ten euros?', example: 'Perdona, ¿tienes cambio de diez euros?' },
    { es: 'No hablo mucho español.', en: 'I don’t speak much Spanish.', example: 'No hablo mucho español, pero estoy aprendiendo.' },
    { es: '¿Dónde puedo comprar un billete?', en: 'Where can I buy a ticket?', example: '¿Dónde puedo comprar un billete de metro?' },
    { es: '¿Qué es esto?', en: 'What is this?', example: 'No conozco este plato. ¿Qué es esto?' },
    { es: 'Estoy buscando una farmacia.', en: 'I’m looking for a pharmacy.', example: 'Perdona, estoy buscando una farmacia.' },
    { es: '¿A qué distancia está?', en: 'How far away is it?', example: '¿A qué distancia está la playa?' },
    { es: '¿Puedo pagar con tarjeta?', en: 'Can I pay by card?', example: '¿Puedo pagar con tarjeta o solo en efectivo?' },
    { es: 'Tengo una reserva a nombre de…', en: 'I have a reservation under the name…', example: 'Tengo una reserva a nombre de Illia.' },
    { es: '¿Qué ha pasado?', en: 'What happened?', example: 'Hay mucha gente aquí. ¿Qué ha pasado?' },
    { es: 'No te preocupes.', en: 'Don’t worry.', example: 'No te preocupes, tenemos tiempo.' },
    { es: '¿Me dejas pasar, por favor?', en: 'Could you let me through, please?', example: 'Disculpa, ¿me dejas pasar, por favor?' },
    { es: '¿Qué haces hoy?', en: 'What are you doing today?', example: '¿Qué haces hoy después de clase?' },
    { es: '¿Qué opinas?', en: 'What do you think?', example: 'A mí me gusta esta idea. ¿Qué opinas?' },
    { es: 'Es una lástima.', en: 'It’s a pity. / It’s a shame.', example: 'Es una lástima que no puedas venir.' },
    { es: '¡Qué buena idea!', en: 'What a great idea!', example: 'Podemos ir en bicicleta. ¡Qué buena idea!' },
    { es: '¿Tienes planes para el fin de semana?', en: 'Do you have plans for the weekend?', example: '¿Tienes planes para el fin de semana?' },
    { es: '¿Podrías escribirlo aquí?', en: 'Could you write it down here?', example: 'No entiendo el nombre. ¿Podrías escribirlo aquí?' },
    { es: '¡Cuídate mucho!', en: 'Take good care of yourself!', example: 'Nos vemos pronto. ¡Cuídate mucho!' },
  ],
  vocabulary: [
    { es: 'pasar', en: 'to happen / to pass' },
    { es: 'acaso', en: 'case / possibility (in “por si acaso”)' },
    { es: 'igual', en: 'equal / the same' },
    { es: 'sonar', en: 'to sound / ring' },
    { es: 'poco', en: 'little / not much' },
    { es: 'claro', en: 'clear / of course' },
    { es: 'parecer', en: 'to seem / appear' },
    { es: 'ganas', en: 'desire / urge' },
    { es: 'echar de menos', en: 'to miss someone or something' },
    { es: 'guay', en: 'cool / awesome' },
    { es: 'pena', en: 'pity / sorrow' },
    { es: 'provecho', en: 'benefit; used in “buen provecho”' },
    { es: 'entender', en: 'to understand' },
    { es: 'repetir', en: 'to repeat' },
    { es: 'despacio', en: 'slowly' },
    { es: 'baño', en: 'bathroom' },
    { es: 'costar', en: 'to cost' },
    { es: 'cuenta', en: 'bill / account' },
    { es: 'estación', en: 'station' },
    { es: 'llamarse', en: 'to be called' },
    { es: 'recomendar', en: 'to recommend' },
    { es: 'ayudar', en: 'to help' },
    { es: 'abrir', en: 'to open' },
    { es: 'cerrar', en: 'to close' },
    { es: 'cambio', en: 'change / exchange' },
    { es: 'billete', en: 'ticket / banknote' },
    { es: 'buscar', en: 'to look for' },
    { es: 'distancia', en: 'distance' },
    { es: 'tarjeta', en: 'card' },
    { es: 'reserva', en: 'reservation' },
    { es: 'preocuparse', en: 'to worry' },
    { es: 'dejar pasar', en: 'to let through' },
    { es: 'lástima', en: 'pity / shame' },
    { es: 'cuidarse', en: 'to take care of oneself' },
  ],
  quiz: [],
  builder: [],
}
